<?php
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/AppTable.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/qtip/jquery.qtip.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/static/css/qtip/jquery.qtip.min.css');

$this->headScript()->captureStart() ?>
function submitForm() {
  $('#loginas').submit();
}

$(document).ready(function () {

    $('span[title]').qtip();
    
});

<?php $this->headScript()->captureEnd();  
$effective_user_in_dashboard = false;
?>

<div class="docs-header">
  <div class="topic container-fluid">
    <div class="row">
      <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-6"><h4>Campaign Details  </h4></div>
      <div class="col-md-5 col-sm-5 text-right col-xs-6">
        <a href="<?php echo $this->basePath() ?>/demand/editcampaign/<?php echo $campaignpreviewid;?>/?ispreview=<?php echo $ispreview?>" class="btn btn-primary btn-margin mrg5T">Edit</a>
        <a href="javascript:;" class="btn btn-danger btn-margin mrg5T" onclick="DeleteCampaignModal(<?php echo $campaignpreviewid;?>,<?php echo $campaignname;?>)">Delete</a>
        <a href="<?php echo $this->basePath() ?>/demand/createbanner/<?php echo $campaignpreviewid;?>/?ispreview=<?php if ($ispreview=='1')echo 'true'?>" class="btn btn-success mrg5T">Create Ad</a>
      </div>
    </div>
  </div>
</div>

<?php if ($is_admin === true): ?>
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-8">

         <form name="loginas" id="loginas" action="<?php echo $this->basePath() ?>/demand/loginas" class="form-inline" >
          <span style="font-size: 12px; font-weight: bold;">LOG IN AS USER</span>
          <select name="userid" onchange="submitForm();" class="form-control">
            <option value="0">Admin (<?php echo $true_user_name; ?>)</option>
            <?php foreach ($user_id_list as $user_info_id => $user_info_name): ?>
              <option <?php 
              if ($user_info_id == $effective_id): 
                $effective_user_in_dashboard = true; 
                echo 'selected="selected"'; 
              endif; ?> value="<?php echo $user_info_id;?>"><?php echo $user_info_name;?></option>
            <?php endforeach; ?>
          </select>
         </form>
         
    </div>
  </div>
</div>
<?php endif; ?>



<div class="steps-container step1 ">
  <div class="container-fluid">
    <div class="row mrg20T">
      <div id="domain-details" class="col-md-10 col-md-offset-1 panel pad20T">
        <h4 class="underline mrg0T">Campaign Overview</h4>
        <div class="row">
          <div class="col-sm-3">Campaign Name: <strong><?php echo $campaignname;?></strong></div>
          <div class="col-sm-3">Status: 
            <strong>
            <?php
              if (!isset($campaignpreviewid)):
                echo "APROVED";
              elseif (isset($deleted) && $deleted == 1): 
                echo "DELETED"; 
              else: 
                echo "PENDING APPROVAL"; 
              endif;
            ?>
            </strong>
          </div>
          <div class="col-sm-3">Start Date: <strong><?php $date = date_create($startdate); echo date_format($date,"Y-m-d");?></strong></div> 
          <div class="col-sm-3">End Date: <strong><?php $date = date_create($enddate); echo date_format($date,"Y-m-d");?></strong></div>
        </div>
        <div class="row">
          <div class="col-sm-3">Impress Counter:<strong></strong></div>
          <div class="col-sm-3">Max Impressions:<strong><?php echo $maximpressions;?></strong></div>
          <div class="col-sm-3">Current Spend:<strong></strong></div>
          <div class="col-sm-3">Max Spend:<strong><?php echo $maxspend;?></strong></div>
        </div>
        <div class="row">
          <div class="col-sm-3">Maximum Target: <strong><?php if ($cpmtarget==1) echo 'CPM'; if ($cpctarget==1) echo ' CPC';?> </strong></div>
        </div>
        <br>
      </div>

    </div>
  </div>
  <div id="container" class="container-fluid">
    <div class="row mrg20T">
      <div class="col-md-10 col-md-offset-1 col-sm-12 panel">
        <div class="pull-left" style="margin: 10px 0 0 10px;">
          <?php if ($effective_id != 0 && $effective_user_in_dashboard === true): ?>

                    <form name="changeusermarkup" id="changeusermarkup" action="<?php echo $this->basePath() ?>/demand/changeusermarkup"class="form-inline" >
                      <input type="hidden" name="markupuserid" value="<?php echo $effective_id;?>" />
                  
                    <span style="font-size: 12px; font-weight: bold;">User Markup Rate:</span>
                    <input type="text"  style="text-align: right; width: 50px" name="user-markup" class="form-control" value="<?php echo $user_markup_rate;?>">%
                      <div style="display: inline;">
                        <input type="submit" name="user-markup-submit" class="btn actv  btn-small" value="Change User Markup" style="margin-left: 8px; margin-bottom: 10px;" title="The Rate that the Impressions Will be Marked up from the Bid Price (Your Profit)" />
                      </div>
                    </form>

          <?php endif; ?>
        </div>
        <div class="">      
          <br clear="all"/>

          <div id="selection-results" class="steps-box">
            <h4 class="underline mrg0T">Ads list</h4>

            <!-- Banner Table Here-->
            <table class="table table-bordered table-hover" data-url="<?php echo $this->basePath() ?>/demand/bannerlist/<?php  echo $campaignpreviewid; ?>/?ispreview=true" id="campaign-ad-table">
              <thead>
                <tr >
                  <th class="text-center">#</th>
                  <th class="text-center">Name</th>
                  <th class="text-center">Size</th>
                  <th class="text-center">Start/End Date</th>
                  <th class="text-center">Bid Amount</th>
                  <th class="text-center">Bid Counter</th>
                  <th class="text-center">Impression Counter</th>
                  <th class="text-center">Current Spend</th>
                </tr>
              </thead>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>

</div>

<div style="clear:both"></div>
<!-- Campaign Delete Modal -->
<input  type="hidden" name="modal_campaign_id" id="modal_campaign_id" value="0" />
<div class="modal fade" id="DeleteCampaignModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Delete Campaign</h4>
      </div>
      <div class="modal-body">
      <div id="campaign_alert_msg" class="alert alert-error" style="display: none;">Error</div>
    <p id="msg"></p>
<h5 style="color: #b94a48;">This action is a preview and must be approved!</h5>
      </div>
      <div class="modal-footer">
      <button type="button" data-loading-text="Processing..." id="campaign_yes_btn" class="btn btn-primary" onclick="deleteCampaignConfirm();">Yes</button>
        <button type="button" class="btn btn-default" id="campaign_no_btn" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>
<!-- Campaign Delete Modal -->

<!-- Banner Delete Modal -->
<input  type="hidden" name="modal_banner_id" id="modal_banner_id" value="0" />
<div class="modal fade" id="DeleteBannerModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Delete Banner</h4>
      </div>
      <div class="modal-body">
      <div id="banner_alert_msg" class="alert alert-error" style="display: none;">Error</div>
    <p id="msg"></p>
<h5 style="color: #b94a48;">This action is a preview and must be approved!</h5>
      </div>
      <div class="modal-footer">
      <button type="button" data-loading-text="Processing..." id="banner_yes_btn" class="btn btn-primary" onclick="deleteBannerConfirm();">Yes</button>
        <button type="button" class="btn btn-default" id="banner_no_btn" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>
<!-- Banner Delete Modal -->