<?php
$this->headScript()->appendFile($this->basePath() . '/static/js/3rdparty/jquery-ui-1.9.2.custom.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/static/css/jquery-ui/smoothness/jquery-ui-1.9.2.custom.min.css');
$this->headScript()->appendFile($this->basePath() . '/static/js/banner.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');


$preview_query = $ispreview == true ? "?ispreview=true" : "";

if ($ispreview == true):
	$ad_campaign_id = $campaignpreviewid;
else:
	$ad_campaign_id = $campaignid;
endif;

$enddate = date('Y-m-d', time() + (86400 * 30));
$minEndDate = explode("/", $enddate);

$this->headScript()->captureStart() ?>

$(function() {
	/*$( "#startdate" ).datepicker(
	{
		changeMonth: true,
		changeYear: true,
		showOtherMonths: true,
        selectOtherMonths: false,
        yearRange: "-1:+6",
	    onSelect: function(date){
	        var selectedDate = new Date(date);
	        var msecsInADay = 86400000;
	        var endDate = new Date(selectedDate.getTime() + msecsInADay);
	        $("#enddate").datepicker( "option", "minDate", endDate );
	    }
	});
	
	$( '#startdateicon' ).click(function() {
          $('#startdate').datepicker('show');
    });
    
    $( "#enddate" ).datepicker(
	{
		changeMonth: true,
		changeYear: true,
		showOtherMonths: true,
        selectOtherMonths: false,
        yearRange: "-1:+6",
        minDate:new Date(<?php echo $minEndDate[2];?>,<?php echo $minEndDate[0];?>,<?php echo $minEndDate[1];?>)
	});
	
	$( '#enddateicon' ).click(function() {
          $('#enddate').datepicker('show');
    });*/
});
<?php $this->headScript()->captureEnd();  ?>


<div class="docs-header">
  <div class="topic">
    <div class="container">
      <!-- <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-6">
      		<ul class="breadcrumb">
			    <li><a href="<?php //echo $this->basePath() ?>/demand/<?php //echo $preview_query; ?>">Ad Campaigns</a> <span class="divider">/</span></li>
			    <li><?php //echo $bread_crumb_info["BCAdCampaign"]; ?><span class="divider">/</span></li>
			     <li><a href="<?php //echo $this->basePath() ?>/demand/viewbanner/<?php //echo $ad_campaign_id; ?><?php //echo $preview_query; ?>">Banners</a><span class="divider">/</span></li>
			    <li class="active">Create Banner</li>
		    </ul>
      </div> -->
      <div ><h4>Create Banner</h4></div>
    </div>
  </div>
</div>
<div id="cdn_form_msg" class="alert alert-error" style="margin: 5px; display: none;"></div>
<div id="container" class="container">
<div class="row mrg20T">
<div class="col-md-8 col-md-offset-2 col-sm-12 panel">
<div class="panel-body">
<form id="bannerform" class="form-horizontal form-top-magin" name="bannerform" method="POST" action="<?php echo $this->basePath() ?>/demand/newbanner">
<fieldset>
<div class="panel-group" id="banner-form-accordion" role="tablist" aria-multiselectable="true">

  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-general-options">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#banner-form-accordion" href="#collapse-general-options" aria-expanded="true" aria-controls="collapse-general-options">
          General Options
        </a>
      </h4>
    </div>
    <div id="collapse-general-options" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-general-options">
      <div class="panel-body">

<div class="span7">
    <input type="hidden" name="campaignid" value="<?php echo $campaignid; ?>">
	<input type="hidden" name="campaignpreviewid" value="<?php echo $campaignpreviewid; ?>">
	<input type="hidden" name="ispreview" value="<?php echo $ispreview; ?>">

	<div class="form-group">
		<label class="col-sm-3 control-label"  for="bannername">Ad Name</label>
		<div class="col-sm-9">
			<input type="text" class="txtbox-width form-control" name="bannername">
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label"  for="adUrl">Upload Ad</label>
		<div class="col-sm-9">
			<input type="file" class="txtbox-width form-control" name="adUrl">
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label"  for="label">Label</label>
		<div class="col-sm-9">
			<input type="text" class="txtbox-width form-control" name="label">
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label"  for="altText">Alt text</label>
		<div class="col-sm-9">
			<input type="text" class="txtbox-width form-control" name="altText">
		</div>
	</div>


	  <div class="form-group">
		<label class="col-sm-3 control-label"  for="adname">Ad Delivery Type</label>
		<div class="col-sm-9">
		<select id="ImpressionType" name="ImpressionType" class="selbox-width form-control" onchange="switchImpressionType();">
			<option value="banner">Banner Ad</option>
			<option value="video" disabled>Video Ad</option>
		</select>
		</div>
	</div>

	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="startdate">Start Date</label>
	    <div class="col-sm-9">
	    <div class="row">
			<div class="col-sm-4">
		        <div class="">
				  <input name="startdate" id="startdate" class="form-control" size="16" type="date" value="<?php echo date('Y-m-d');?>"  />
				  
			   </div>
			</div>
			<div class="col-sm-8">
				<div class="form-group">
				    <label class="col-sm-6 control-label"  for="enddate">End Date</label>
				    <div class="col-sm-6">
			        <div class="">
					  <input name="enddate" id="enddate" class="form-control" size="16" type="date" value="<?php echo $enddate;?>" />
					  
				   </div>
				   </div>
				</div>
			</div>
	   </div>
	   </div>
	</div>
	

	 <div class="control-group nobanner" style="display: none">
		<label class="col-sm-3 control-label"  for="Mimes">Mimes : <span class="hlp"><small><i>(ctrl+shift to select mutliple)</i></small></span></label>
		<div class="col-sm-9">
			<select id="Mimes" name="Mimes[]" multiple class="zone-txtarea form-control" style="min-height: 170px">
			    <?php foreach ($mimes as $name): ?>
			        <?php if (in_array((string)$name, $current_mimes)): ?>
			            <option value="<?php echo $name;?>" selected="selected"><?php echo $name;?></option>
			        <?php else: ?>
			            <option value="<?php echo $name;?>"><?php echo $name;?></option>
			        <?php endif; ?>
			    <?php endforeach; ?>
			</select>
		</div>
	</div>
	 <div class="control-group nobanner" style="display: none">
		<label class="col-sm-3 control-label"  for="Protocols">Protocols : <span class="hlp"><small><i>(ctrl+shift to select mutliple)</i></small></span></label>
		<div class="col-sm-9">
			<select id="Protocols" name="Protocols[]" multiple class="zone-txtarea form-control" style="min-height: 120px">
			    <?php foreach ($protocols as $code => $name): ?>
			        <?php if (in_array((string)$code, $current_protocols)): ?>
			            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
			        <?php else: ?>
			            <option value="<?php echo $code;?>"><?php echo $name;?></option>
			        <?php endif; ?>
			    <?php endforeach; ?>
			</select>
		</div>
	</div>
	 <div class="control-group nobanner" style="display: none">
		<label class="col-sm-3 control-label"  for="ApisSupported">Apis Supported : <span class="hlp"><small><i>(ctrl+shift to select mutliple)</i></small></span></label>
		<div class="col-sm-9">
			<select id="ApisSupported" name="ApisSupported[]" multiple class="zone-txtarea form-control" style="min-height: 120px">
			    <?php foreach ($apis_supported as $code => $name): ?>
			        <?php if (in_array((string)$code, $current_apis_supported)): ?>
			            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
			        <?php else: ?>
			            <option value="<?php echo $code;?>"><?php echo $name;?></option>
			        <?php endif; ?>
			    <?php endforeach; ?>
			</select>
		</div>
	</div>
	<div class="control-group nobanner" style="display: none">
		<label class="col-sm-3 control-label"  for="StartDelay">Start Delay : </label>
		<div class="col-sm-9">
			<select id="StartDelay" name="StartDelay" class="zone-txtarea form-control">
			    <?php foreach ($start_delay as $code => $name): ?>
			        <?php if ((string)$code === $current_start_delay): ?>
			            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
			        <?php else: ?>
			            <option value="<?php echo $code;?>"><?php echo $name;?></option>
			        <?php endif; ?>
			    <?php endforeach; ?>
			</select>
		</div>
	</div>
	
	<?php if ($is_admin): ?>
	<div class="form-group novideo">
		<label class="col-sm-3 control-label"  for="adcampaigntype">What type of ad campaign banner is this?</label>
		<div class="col-sm-9">
		        <select id="adcampaigntype"  class="selbox-width form-control" name="adcampaigntype" onchange="switchAdCampaignType();">
		            <?php foreach ($adcampaigntype_options as $code => $name): ?>
		                <option value="<?php echo $code;?>"><?php echo $name;?></option>
		            <?php endforeach; ?>
		        </select>
		</div>
	        <div id="weight-box" class="novideo">
			    <label class="col-sm-3 control-label"  for="weight" class="control-label">Ad Display Priority</label>
			    <div class="controls">
			    <div class="col-sm-9">
			    <input type="text" value="5" size="5" maxlength="10" id="weight" name="weight" class="input-mini form-control">    </div> 
	    	</div>
	        <div id="zone-picker"></div>
		</div>
	</div>
	<?php endif; ?>
	<div class="form-group novideo">
		<label class="col-sm-3 control-label"  for="ismobile">Is this a mobile ad?</label>
		<div class="col-sm-9">
	        <select id="ismobile"  class="selbox-width form-control" name="ismobile" onchange="switchMobile(this);">
	            <?php foreach ($mobile_options as $code => $name): ?>
	                <option value="<?php echo $code;?>" <?php echo $name=="Desktop" ? "" : "disabled" ?> ><?php echo $name;?></option>
	            <?php endforeach; ?>
	        </select>
		</div>
	</div>
	<div class="form-group novideo">
		<label class="col-sm-3 control-label"  for="iabsize">IAB Size</label>
		<div class="col-sm-9">
			<div id="size-select">
				<select id="iabsize"  class="selbox-width form-control"  name="iabsize" onchange="formSelectSize(this);">
				    <option value="" selected="selected">[ SELECT A SIZE ]</option>
				    <?php foreach ($size_list as $shortcode => $name): ?>
				        <option value="<?php echo $shortcode;?>"><?php echo $name;?></option>
				    <?php endforeach; ?>
				</select>
			</div>
		</div>
	</div>

	</div>
	<div class="span7">
		<div class="form-group novideo">
		<label class="col-sm-3 control-label"  for="height">Height</label>
		<div class="col-sm-9">
			<input type="text" id="height" name="height" class="input-mini form-control">
		</div>
	</div>
	<div class="form-group novideo">
		<label class="col-sm-3 control-label"  for="width">Width</label>
		<div class="col-sm-9">
		<input type="text" id="width" name="width" class="input-mini form-control">
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label"  for="bidamount">Bid Amount ( CPM )</label>
		<div class="col-sm-9">
			<div class="input-prepend input-group">
			<span class="add-on input-group-addon">$</span>
			<input type="text" name="bidamount"  class="input-small form-control" value="0.25">
			</div>
		</div>
	</div>
	<div class="control-group nobanner" style="display: none">
		<label class="col-sm-3 control-label"  for="adtagtype">VAST Tag Type</label>
		<div class="col-sm-9">
			<div class="btn-group" role="group" aria-label="...">
			  <button type="button" onclick="switchImpressionType('xml');" class="btn btn-default">VAST XML</button>
			  <button type="button" onclick="switchImpressionType('url');" class="btn btn-default">VAST URL</button>
			</div>
		</div>
	</div>
	<div class="form-group">
		<label class="col-sm-3 control-label"  for="adtag">Ad Tag</label>
		<div class="col-sm-9">
		<span id="adtagwrapper">
			<textarea class="txtbox-width form-control"  id="adtag" name="adtag" rows="6"></textarea>
		</span>
		</div>
	</div>

	<div class="form-group">
		<label class="col-sm-3 control-label"  for="landingPageTLD">Landing Page TLD</label>
		<div class="col-sm-9">
			<input type="text" name="landingPageTLD"  class="form-control" >
		</div>
	</div>

	<div class="form-group novideo">
		<label class="col-sm-3 control-label"  for="iABAudienceCategory">IAB Audience Category</label>
		<div class="col-sm-9">
			<div id="size-select">
				<select id="iABAudienceCategory"  class="selbox-width form-control"  name="iABAudienceCategory" >
				    
				    <?php 
	                   foreach($vertical_map as $key=>$value): 
	                  echo '<option value="'. $key .'">'. $value .'</option>';
	                 endforeach;
                	?>
				</select>
			</div>
		</div>
	</div>

	<div class="form-group novideo">
		<label class="col-sm-3 control-label"  for="gEOCountry">GEO country</label>
		<div class="col-sm-9">
			<div id="size-select">
				<select id="gEOCountry"  class="selbox-width form-control"  name="gEOCountry" >
				    
				    <?php 
	                   foreach($geo_country as $key=>$value): 
	                  echo '<option value="'. $key .'">'. $value .'</option>';
	                 endforeach;
                	?>
				</select>
			</div>
		</div>
	</div>
	<div class="form-group novideo">
		<label class="col-sm-3 control-label"  for="timeZone">Timezone</label>
		<div class="col-sm-9">
			<div id="size-select">
				<select id="timeZone"  class="selbox-width form-control"  name="timeZone" >
				    <?php 
	                   foreach($timezone_options as $key=>$value): 
	                  echo '<option value="'. $key .'">'. $value .'</option>';
	                 endforeach;
                	?>
				</select>
			</div>
		</div>
	</div>

	 <div class="control-group nobanner" style="display: none">
		<label class="col-sm-3 control-label"  for="Delivery">Delivery : <span class="hlp"><small><i>(ctrl+shift to select mutliple)</i></small></span></label>
		<div class="col-sm-9">
			<select id="Delivery" name="Delivery[]" multiple class="zone-txtarea form-control" style="min-height: 50px">
			    <?php foreach ($delivery_methods as $code => $name): ?>
			        <?php if (in_array((string)$code, $current_delivery_methods)): ?>
			            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
			        <?php else: ?>
			            <option value="<?php echo $code;?>"><?php echo $name;?></option>
			        <?php endif; ?>
			    <?php endforeach; ?>
			</select>
		</div>
	</div>
	
	 <div class="control-group nobanner" style="display: none">
		<label class="col-sm-3 control-label"  for="Playback">Playback : <span class="hlp"><small><i>(ctrl+shift to select mutliple)</i></small></span></label>
		<div class="col-sm-9">
			<select id="Playback" name="Playback[]" multiple class="zone-txtarea form-control" style="min-height: 100px">
			    <?php foreach ($playback_methods as $code => $name): ?>
			        <?php if (in_array((string)$code, $current_playback_methods)): ?>
			            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
			        <?php else: ?>
			            <option value="<?php echo $code;?>"><?php echo $name;?></option>
			        <?php endif; ?>
			    <?php endforeach; ?>
			</select>
		</div>
	</div>
	
	<div class="control-group nobanner" style="display: none">
		<label class="col-sm-3 control-label"  for="Linearity">Linearity : </label>
		<div class="col-sm-9">
			<select id="Linearity" name="Linearity" class="zone-txtarea form-control">
			    <?php foreach ($linearity as $code => $name): ?>
			        <?php if ((string)$code === $current_linearity): ?>
			            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
			        <?php else: ?>
			            <option value="<?php echo $code;?>"><?php echo $name;?></option>
			        <?php endif; ?>
			    <?php endforeach; ?>
			</select>
		</div>
	</div>
	
<!-- 	<div class="form-group">
		<label class="col-sm-3 control-label"  for="landingpagetld" class="input">LandingPage TLD [top level domain]
		</label>
		<div class="col-sm-9">
			<input type="text" class="input-medium form-control" name="landingpagetld" value="nginad.com">
			<span class="hlp">
			<small><i>(eg. nginad.com - required by RTB [if not known just use the tld of the tag])</i></small></span><nobr></nobr>
		</div>
	</div> -->
	</div>
      </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-advance-options">
      <h4 class="panel-title">
        <a  data-toggle="collapse" data-parent="#banner-form-accordion" href="#collapse-advance-options" aria-expanded="true" aria-controls="collapse-advance-options">
          Advance Options
        </a>
      </h4>
    </div>
    <div id="collapse-advance-options" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-advance-options">
      <div class="panel-body">



	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="adTagType">Ad tag-type</label>
	    <div class="col-sm-9">
	    	<label class="radio-inline">
			  <input type="radio" name="adTagType" id="iframe" value="iframe" checked> Iframe
			</label>
			<label class="radio-inline">
			  <input type="radio" name="adTagType" id="javascript" value="javascript"> Javascript
			</label>
	   </div>
	</div>

	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="inAnIframe">In an Iframe</label>
	    <div class="col-sm-9">
	    	<label class="radio-inline">
			  <input type="radio" name="inAnIframe" id="iframe-no-preference" value="0" checked> No preference
			</label>
			<label class="radio-inline">
			  <input type="radio" name="inAnIframe" id="iframe-yes" value="1"> Yes
			</label>
			<label class="radio-inline">
			  <input type="radio" name="inAnIframe" id="iframe-no" value="2"> No
			</label>
	   </div>
	</div>

	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="multiNestedIframe">In Multi Nested Iframe</label>
	    <div class="col-sm-9">
	    	<label class="radio-inline">
			  <input type="radio" name="multiNestedIframe" id="multi-no-preference" value="0" checked> No preference
			</label>
			<label class="radio-inline">
			  <input type="radio" name="multiNestedIframe" id="multi-yes" value="1"> Yes
			</label>
			<label class="radio-inline">
			  <input type="radio" name="multiNestedIframe" id="multi-no" value="2"> No
			</label>
	   </div>
	</div>

	<div class="form-group">
	    <div class="col-sm-9 col-md-offset-3">
	    	<div class="checkbox">
			  <label>
			    <input type="checkbox" value="1" name="frequencyCap" onchange="frequency_cap_check()">Frequency Cap in last 24 hours 
			  </label>
			</div>
			
	   </div>
	</div>

	<div class="form-group" style="display: none;">
	    <label class="col-sm-3 control-label"  for="FreCapShowTime">Show times</label>
	    <div class="col-sm-9">
	    	<input type="number" name="FreCapShowTime" id="FreCapShowTime" class="form-control" >
	   </div>
	</div>
	<div class="form-group" style="display: none;">
	    <label class="col-sm-3 control-label"  for="FreCapTimeHr">Time duration (hour)</label>
	    <div class="col-sm-9">
	    	<div class="row">
	    		<label class="col-sm-2 control-label"  for="FreCapTimeFromHr">from</label>
			    <div class="col-sm-4">
			    	<input type="number" name="FreCapTimeFromHr" id="FreCapTimeFromHr" class="form-control" >
			   </div>
			   <label class="col-sm-2 control-label"  for="FreCapTimeToHr">to</label>
			    <div class="col-sm-4">
			    	
			    	<input type="number" name="FreCapTimeToHr" id="FreCapTimeToHr" class="form-control" >
			   </div>
	   </div>
	   </div>
	</div>

	<div class="form-group" style="display: none;">
		<label class="col-sm-3 control-label"  for="freCapApply">Apply</label>
	    <div class="col-sm-9">
	    	<div class="checkbox-inline">
			  <label>
			    <input type="checkbox" value="1" name="freCapCampaignApply">By campaign
			  </label>
			</div>
			<div class="checkbox-inline">
			  <label>
			    <input type="checkbox" value="1" name="freCapZoneApply">By zone 
			  </label>
			</div>
	   </div>
	</div>


      </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-position-options">
      <h4 class="panel-title">
        <a  data-toggle="collapse" data-parent="#banner-form-accordion" href="#collapse-position-options" aria-expanded="true" aria-controls="collapse-position-options">
          Position Options
        </a>
      </h4>
    </div>
    <div id="collapse-position-options" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-position-options">
      <div class="panel-body">



	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="adTagType">Ad position</label>
	    <div class="col-sm-9">
	    	<label class="radio-inline">
			  <input type="radio" name="adPosLeft" id="Min-Left" value="0" checked> Min Left
			</label>
			<label class="radio-inline">
			  <input type="radio" name="adPosLeft" id="Max-Left" value="1"> Max Left
			</label>	
			<br>   
	    	<label class="radio-inline">
			  <input type="radio" name="adPostTop" id="Min-Top" value="0" checked> Min Top
			</label>
			<label class="radio-inline">
			  <input type="radio" name="adPostTop" id="Max-Top" value="1"> Max Top
			</label>
	   </div>
	</div>

	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="foldPosition">Fold position</label>
	    <div class="col-sm-9">
	    	<select id="foldPosition"  class="selbox-width form-control"  name="foldPosition">
			
			    <?php foreach ($fold_position as $value => $name): ?>
			        <option value="<?php echo $value;?>"><?php echo $name;?></option>
			    <?php endforeach; ?>
			</select>
	   </div>
	</div>
      </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-resolution-options">
      <h4 class="panel-title">
        <a  data-toggle="collapse" data-parent="#banner-form-accordion" href="#collapse-resolution-options" aria-expanded="true" aria-controls="collapse-resolution-options">
          Resolution Options
        </a>
      </h4>
    </div>
    <div id="collapse-resolution-options" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-resolution-options">
      <div class="panel-body">
	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="resolutionMinW">Min screen res with</label>
	    <div class="col-sm-9">
	    	<input type="number" name="resolutionMinW"  class="form-control" >
	   </div>
	</div>

	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="resolutionMaxW">Max screen res with</label>
	    <div class="col-sm-9">
	    	<input type="number" name="resolutionMaxW"  class="form-control" >
	   </div>
	</div>
	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="resolutionMinH">Min screen res height</label>
	    <div class="col-sm-9">
	    	<input type="number" name="resolutionMinH"  class="form-control" >
	   </div>
	</div>
	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="resolutionMaxH">Max screen res height</label>
	    <div class="col-sm-9">
	    	<input type="number" name="resolutionMaxH"  class="form-control" >
	   </div>
	</div>


      </div>
    </div>
</div>

<div class="panel panel-default">
    <div class="panel-heading" role="tab" id="heading-other-options">
      <h4 class="panel-title">
        <a  data-toggle="collapse" data-parent="#banner-form-accordion" href="#collapse-other-options" aria-expanded="true" aria-controls="collapse-other-options">
          Other Options
        </a>
      </h4>
    </div>
    <div id="collapse-other-options" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="heading-other-options">
      <div class="panel-body">
	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="httpLang">HTTP Language</label>
	    <div class="col-sm-9">
	    	<input type="text" name="httpLang" id="httpLang"  class="form-control" >
	   </div>
	</div>

	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="browerAgentGrep">Browser User Agent Grep</label>
	    <div class="col-sm-9">
	    	<input type="number" name="browerAgentGrep" id="browerAgentGrep"  class="form-control" >
	   </div>
	</div>
	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="cookieGrep">Cookie Grep</label>
	    <div class="col-sm-9">
	    	<input type="number" name="cookieGrep" id="cookieGrep" class="form-control" >
	   </div>
	</div>
	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="resolutionMaxH">Pmp Enable</label>
	    <div class="col-sm-9">
	    	<label class="radio-inline">
			  <input type="radio" name="pmpEnable" id="no-preference" value="0" checked> No Preference
			</label>
			<label class="radio-inline">
			  <input type="radio" name="pmpEnable" id="PMP-Enable-On" value="1"> PMP Enable On
			</label>		
	    	<label class="radio-inline">
			  <input type="radio" name="pmpEnable" id="PMP-Enable-Off" value="2"> PMP Enable Off
			</label>
	   </div>
	</div>

	<div class="form-group">
	    <label class="col-sm-3 control-label"  for="secure">Secure</label>
	    <div class="col-sm-9">
	    	<label class="radio-inline">
			  <input type="radio" name="secure" id="Secure-no-preference" value="0" checked> No Preference
			</label>
			<label class="radio-inline">
			  <input type="radio" name="secure" id="Secure-Secure-On" value="1"> https:// Secure on
			</label>		
	    	<label class="radio-inline">
			  <input type="radio" name="secure" id="Secure-Secure-Off" value="2"> https:// Secure off
			</label>
	   </div>
	</div>


      </div>
    </div>
</div>


	</div>

	<div class="span12">
	<div class="form-group text-center">
		<p>
	   <input type="submit" class="btn btn-primary" name="B1" value="Create New Banner" /></p>
	   </div>
	</div>




</fieldset>
</form>
</div>
</div>
</div>
</div>
</div>



