<?php
$this->headLink()->appendStylesheet($this->basePath() . '/static/css/jquery-ui/smoothness/jquery-ui-1.9.2.custom.min.css');
$this->headScript()->appendFile($this->basePath() . '/static/js/3rdparty/jquery-ui-1.9.2.custom.min.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');

$enddate = date('m/d/Y', time() + (86400 * 30));
$minEndDate = explode("/", $enddate);

$this->headScript()->captureStart();?>
$(function() {
});
<?php $this->headScript()->captureEnd();?>
<style type="text/css">
	/*form label.error, form input.submit {
margin-left: 253px;
} */
</style>
<div class="docs-header">
  <div class="topic">
    <div class="row">
      <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-6"><h4>Create Campaign</h4></div>
    </div>
  </div>
</div>
 <div class="container">
  <div class="row">
    <br />
    <div class="col-md-8 col-md-offset-2 panel panel-default">
      <div class="panel-body">
<!--         <?php 
            if($error_message != "" && $error_message !== null && isset($error_message)):
              echo '<div id="cdn_form_success" class="alert alert-danger" style="margin: 15px;">'. $error_message .'</div>';
            endif;
        ?> -->
        <div id="cdn_form_msg" class="alert alert-danger" style="margin: 15px; display:none;"></div>
        <form id="campaign" class="form-horizontal form-top-magin" name="campaignform" method="POST" action="<?php echo $this->basePath() ?>/demand/newcampaign" novalidate="novalidate">
          <div class="form-group">
            <label for="campaignname" class="control-label col-sm-3">Campaign Name</label>
            <div class="controls col-sm-7">
              <input type="text" value="" maxlength="255" class="form-control" id="campaignname" name="campaignname">    
            </div>
          </div>
          <div class="form-group">
            <label for="startdate" class="control-label col-sm-3">Start Date</label>
            <div class="controls col-sm-7">
              <input type="date" value="" maxlength="255" class="form-control" id="startdate" name="startdate">
            </div>
          </div>
          <div class="form-group">
            <label for="enddate" class="control-label col-sm-3">End Date</label>
            <div class="controls col-sm-7">
              <input type="date" value="" maxlength="255" class="form-control" id="enddate" name="enddate">
            </div>
          </div>

          <div class="form-group">
            <label for="customername" class="control-label col-sm-3">Customer Name <br><sup>(Use this field for your own customer reference if any)</sup></label>
            <div class="controls col-sm-7">
              <input type="text" value="" maxlength="255" class="form-control" id="customername" name="customername">
            </div>
          </div>

          <div class="form-group">
            <label for="customerid" class="control-label col-sm-3">Customer Id <br><sup>(Use this field for your own customer reference if any)</sup></label>
            <div class="controls col-sm-7">
              <input type="text" value="" maxlength="255" class="form-control" id="customerid" name="customerid">
            </div>
          </div>

          <div class="form-group">
            <label for="maximpressions" class="control-label col-sm-3">Maximum Impressions <br><sup>(Maximum campaign impressions before the bids stop)</sup></label>
            <div class="controls col-sm-7">
              <input type="number" value="" maxlength="255" class="form-control" id="maximpressions" name="maximpressions">
            </div>
          </div>

          <div class="form-group">
            <label for="maxtarget" class="control-label col-sm-3">Maximum target</label>
            <div class="controls col-sm-7">
              <label for="cpmtarget"><input type="checkbox" id="cpmtarget" name="cpmtarget" class="inline"/> CPM</label>
              <label for="cpctarget"><input type="checkbox" id="cpctarget" name="cpctarget" class="inline"/> CPC</label>
            </div>
          </div>

          <div class="form-group">
            <label for="maxspend" class="control-label col-sm-3">Maximum spend<br><sup>(Maximum campaign $$$ spent before the bids stop)</sup></label>
            <div class="controls col-sm-7">
              <input type="number" value="" maxlength="255" class="form-control" id="maxspend" name="maxspend">
            </div>
          </div>

          <div class="form-group text-center">
            <div class="controls">
              <button name="submit" type="submit" class="btn btn-primary btn-margin" id="submitbutton">Create New Campaign</button>
            </div>
          </div>
        </form>        
      </div>
    </div>
  </div>
</div>

