<?php
$this->headLink()->appendStylesheet($this->basePath() . '/static/css/jquery-ui/smoothness/jquery-ui-1.9.2.custom.min.css');
$this->headScript()->appendFile($this->basePath() . '/static/js/3rdparty/jquery-ui-1.9.2.custom.min.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');
//$this->headScript()->appendFile('http://cdn.jsdelivr.net/webshim/1.12.4/extras/modernizr-custom.js');
//$this->headScript()->appendFile('http://cdn.jsdelivr.net/webshim/1.12.4/polyfiller.js');


$enddate = date('m/d/Y', time() + (86400 * 30));
$minEndDate = explode("/", $enddate);

$this->headScript()->captureStart();?>
$(function() {
  //webshims.setOptions('waitReady', false);
  //webshims.setOptions('forms-ext', {types: 'date'});
  //webshims.polyfill('forms forms-ext');
    $( "#startdate" ).datepicker(
  {
    changeMonth: true,
    changeYear: true,
    showOtherMonths: true,
        selectOtherMonths: false,
        yearRange: "-1:+6",
      onSelect: function(date){
          var selectedDate = new Date(date);
          var msecsInADay = 86400000;
          var endDate = new Date(selectedDate.getTime() + msecsInADay);
          $("#enddate").datepicker( "option", "minDate", endDate );
      }
  });
  
  $( '#startdateicon' ).click(function() {
          $('#startdate').datepicker('show');
    });
    
    $( "#enddate" ).datepicker(
  {
    changeMonth: true,
    changeYear: true,
    showOtherMonths: true,
        selectOtherMonths: false,
        yearRange: "-1:+6",
        minDate:new Date(<?php echo $minEndDate[2];?>,<?php echo $minEndDate[0];?>,<?php echo $minEndDate[1];?>)
  });
  
  $( '#enddateicon' ).click(function() {
          $('#enddate').datepicker('show');
    });
});
<?php $this->headScript()->captureEnd();?>
<style type="text/css">
	/*form label.error, form input.submit {
margin-left: 253px;
} */
</style>
<div class="docs-header">
  <div class="topic container-fluid">
    <div class="row">
      <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-6"><h4><?php echo $this->layout()->_t->translate("Create Campaign");?></h4></div>
    </div>
  </div>
</div>
 <div class="container">
  <div class="row">
    <br />
    <div class="col-md-8 col-md-offset-2 panel panel-default">
      <div class="panel-body">
<!--         <?php 
            if($error_message != "" && $error_message !== null && isset($error_message)):
              echo '<div id="cdn_form_success" class="alert alert-danger" style="margin: 15px;">'. $error_message .'</div>';
            endif;
        ?> -->
        <div id="cdn_form_msg" class="alert alert-danger" style="margin: 15px; display:none;"></div>
        <form id="campaign" class="form-horizontal form-top-magin" name="campaignform" method="POST" action="<?php echo $this->basePath() ?>/demand/newcampaign" novalidate="novalidate">
          <h4 class="underline mrg0T"><?php echo $this->layout()->_t->translate("General Options");?></h4>
          <div class="form-group">
            <label for="campaignname" class="control-label col-sm-3"><?php echo $this->layout()->_t->translate("Campaign Name");?>*</label>
            <div class="controls col-sm-7">
              <input type="text" value="" maxlength="255" class="form-control" id="campaignname" name="campaignname">    
            </div>
          </div>
          <?php if ($is_admin === true): ?>
            <div class="form-group">
              <label for="campaignmarkup" class="control-label col-sm-3"><?php echo $this->layout()->_t->translate("Campaign Markup");?></label>
              <div class="controls col-sm-7">
                <input type="text" value="" maxlength="255" class="form-control" id="campaignmarkup" name="campaignmarkup">    
              </div>
            </div>
        <?php endif;?>
          <div class="form-group">
            <label for="startdate" class="control-label col-sm-3"><?php echo $this->layout()->_t->translate("Start Date");?>*</label>
            <div class="controls col-sm-7">
              <!-- <input type="date" value="" maxlength="255" class="form-control" id="startdate" name="startdate"> -->
              <div class="input-append date">
                <input name="startdate" id="startdate" class="span2 form-control" class="" type="text" value="<?php echo date('m/d/Y');?>" readonly="readonly" />
                <span class="add-on" id="startdateicon"><i class="icon-calendar"></i></span>
               </div>
            </div>
          </div>
          <div class="form-group">
            <label for="enddate" class="control-label col-sm-3"><?php echo $this->layout()->_t->translate("End Date");?>*</label>
            <div class="controls col-sm-7">
              <!-- <input type="date" value="" maxlength="255" class="form-control" id="enddate" name="enddate"> -->
              <div class="input-append date">
                <input name="enddate" id="enddate" class="span2 form-control" size="16" type="text" value="<?php echo $enddate;?>" readonly="readonly" />
                <span class="add-on" id="enddateicon"><i class="icon-calendar"></i></span>
               </div>
            </div>
          </div>

          <div class="form-group">
            <label for="maximpressions" class="control-label col-sm-3"><?php echo $this->layout()->_t->translate("Maximum Impressions");?>* <br><sup>(<?php echo $this->layout()->_t->translate("Maximum campaign impressions before the bids stop");?>)</sup></label>
            <div class="controls col-sm-7">
              <input type="number" value="" maxlength="255" class="form-control" id="maximpressions" name="maximpressions">
            </div>
          </div>

          <div class="form-group">
            <label for="maxtarget" class="control-label col-sm-3"><?php echo $this->layout()->_t->translate("Maximum target");?>*</label>
            <div class="controls col-sm-7">
              <label for="cpmtarget"><input type="checkbox" id="cpmtarget" name="cpmtarget" class="inline" checked/> CPM</label>
              <label for="cpctarget"><input type="checkbox" id="cpctarget" name="cpctarget" class="inline"/> CPC</label>
            </div>
          </div>

          <div class="form-group">
            <label for="maxspend" class="control-label col-sm-3"><?php echo $this->layout()->_t->translate("Maximum spend");?>*<br><sup>(<?php echo $this->layout()->_t->translate("Maximum campaign $$$ spent before the bids stop");?>)</sup></label>
            <div class="controls col-sm-7">
              <input type="number" value="" maxlength="255" class="form-control" id="maxspend" name="maxspend">
            </div>
          </div>
          <h4 class="underline mrg0T"><?php echo $this->layout()->_t->translate("Advance Options");?></h4>

          <div class="form-group">
            <label for="customername" class="control-label col-sm-3"><?php echo $this->layout()->_t->translate("Customer Name");?> <br><sup>(<?php echo $this->layout()->_t->translate("Use this field for your own customer reference if any");?>)</sup></label>
            <div class="controls col-sm-7">
              <input type="text" value="" maxlength="255" class="form-control" id="customername" name="customername">
            </div>
          </div>

          <div class="form-group">
            <label for="customerid" class="control-label col-sm-3"><?php echo $this->layout()->_t->translate("Customer Id");?> <br><sup>(<?php echo $this->layout()->_t->translate("Use this field for your own customer reference if any");?>)</sup></label>
            <div class="controls col-sm-7">
              <input type="text" value="" maxlength="255" class="form-control" id="customerid" name="customerid">
            </div>
          </div>
          <div class="form-group text-center">
            <div class="controls">
              <button name="submit" type="submit" class="btn btn-primary btn-margin" id="submitbutton"><?php echo $this->layout()->_t->translate("Create New Campaign");?></button>
              <?php if (array_key_exists('HTTP_REFERER',$_SERVER)): ?>
                <a href="<?php echo $_SERVER['HTTP_REFERER']  ?>" class="btn btn-margin">
                <?php echo $this->layout()->_t->translate("Cancel");?></a>
              <?php else: ?>
                <a href="<?php echo $this->basePath() . '/demand' ?>" class="btn btn-margin">
                <?php echo $this->layout()->_t->translate("Cancel");?></a>
              <?php endif; ?>
            </div>
          </div>
        </form>        
      </div>
    </div>
  </div>
</div>

