<?php

$this->headScript()->appendFile($this->basePath() . '/js/filter.js');

$preview_query = $ispreview == true ? "?ispreview=true" : "";
if ($ispreview == true):
	$rtb_banner_id = $bannerpreviewid;
	$ad_campaign_id = $campaignpreviewid;
else:
	$rtb_banner_id = $bannerid;
	$ad_campaign_id = $campaignid;
endif;

$this->headScript()->captureStart(); ?>
var currentStates = "<?php echo $current_states; ?>";
<?php $this->headScript()->captureEnd();  ?>

  <ul class="breadcrumb">
    <li><a href="<?php echo $this->basePath() ?>/demand/<?php echo $preview_query; ?>"><?php echo $this->layout()->_t->translate("Ad Campaigns");?></a><span class="divider">/</span></li>
    <li><?php echo $bread_crumb_info["BCAdCampaign"]; ?><span class="divider">/</span></li>
    <li><a href="<?php echo $this->basePath() ?>/demand/viewbanner/<?php echo $ad_campaign_id; ?><?php echo $preview_query; ?>"><?php echo $this->layout()->_t->translate("Banners");?></a><span class="divider">/</span></li>
    <li><?php echo $bread_crumb_info["BCBanner"]; ?><span class="divider">/</span></li>
    <li><?php echo $this->layout()->_t->translate("Edit Delivery Filter");?></li>
    </ul>
<div class="formbox">
<form method="POST" action="<?php echo $this->basePath() ?>/demand/editdeliveryfilter">
<fieldset>
<div class="span7">
    <input type="hidden" name="bannerid" value="<?php echo $bannerid; ?>">
	<input type="hidden" name="bannerpreviewid" value="<?php echo $bannerpreviewid; ?>">
	<input type="hidden" name="ispreview" value="<?php echo (string)$ispreview; ?>">
   <div class="control-group">
		<label for="vertical"><?php echo $this->layout()->_t->translate("Vertical");?> : <span class="hlp"><small><i>(<?php echo $this->layout()->_t->translate("ctrl+shift to select mutliple verticals");?>)</i></small></span></label>
<select id="vertical" name="vertical[]" multiple class="zone-txtarea" style="min-height: 200px">
    <?php foreach ($vertical_options as $code => $name): ?>
        <?php if (in_array((string)$code, $current_verticals)): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>

	</div>

<div class="control-group">
		<label for="geocountry"><?php echo $this->layout()->_t->translate("Geo Country");?> : <span class="hlp"><small><i>(<?php echo $this->layout()->_t->translate("ctrl+shift to select mutliple countries");?>)</i></small></span></label>
<select id="geocountry" name="geocountry[]" class="zone-txtarea" multiple style="min-height: 200px" onchange="populateStates();">
    <option value="">[ <?php echo $this->layout()->_t->translate("SELECT A COUNTRY");?> ]</option>
    <?php foreach ($countrylist as $shortcode => $name): ?>
        <?php if (in_array((string)$shortcode, $current_countries)): ?>
            <option value="<?php echo $shortcode?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $shortcode?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
	</div>
<div class="control-group">
		<label for="geostate"><?php echo $this->layout()->_t->translate("Geo State");?> : <span class="hlp"><small><i>(<?php echo $this->layout()->_t->translate("ctrl+shift to select mutliple states");?>)</i></small></span></label>
		<div id="state-select" style="margin-bottom: 30px;">

  </div>
	</div>
	<div class="control-group">
		<label for="geocity"><?php echo $this->layout()->_t->translate("Geo City");?> : <span class="hlp"><small><i>(<?php echo $this->layout()->_t->translate("comma separate multiple cities");?>)</i></small></span></label>
		<input type="text" id="geocity" name="geocity" value="<?php echo $geocity_option;?>" class="zone-txtbox">
	</div>
<div class="control-group">
		<label for="adtagtype"><?php echo $this->layout()->_t->translate("Ad Tag Type");?></label>
<select id="adtagtype" name="adtagtype" class="zone-txtarea">
    <?php foreach ($adtagtype_options as $code => $name): ?>
        <?php if ((string)$code === $current_adtagtype): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
	</div>
	<div class="control-group">
		<label for="adpositionminleft"><?php echo $this->layout()->_t->translate("Ad Position Min Left");?> : <span class="hlp"><small><i>(<?php echo $this->layout()->_t->translate("eg. 100 [in px]");?>)</i></small></span></label>
		<input type="text" name="adpositionminleft" value="<?php echo $adpositionminleft_option;?>" class="input-mini">
	</div>
	<div class="control-group">
		<label for="adpositionmaxleft"><?php echo $this->layout()->_t->translate("Ad Position Max Left");?> : <span class="hlp"><small><i>(<?php echo $this->layout()->_t->translate("eg. 100 [in px]");?>)</i></small></span></label>
		<input type="text" name="adpositionmaxleft" value="<?php echo $adpositionmaxleft_option;?>" class="input-mini">
	</div>
	<div class="control-group">
		<label for="adpositionmintop"><?php echo $this->layout()->_t->translate("Ad Position Min Top");?> : <span class="hlp"><small><i>(<?php echo $this->layout()->_t->translate("eg. 100 [in px");?>])</i></small></span></label>
		<input type="text" name="adpositionmintop" value="<?php echo $adpositionmintop_option;?>" class="input-mini">
	</div>
	<div class="control-group">
		<label for="adpositionmaxtop"><?php echo $this->layout()->_t->translate("Ad Position Max Top");?> : <span class="hlp"><small><i>(<?php echo $this->layout()->_t->translate("eg. 100 [in px");?>])</i></small></span></label>
		<input type="text" name="adpositionmaxtop" value="<?php echo $adpositionmaxtop_option;?>" class="input-mini">
	</div>
	<div class="control-group">
		<label for="foldpos"><?php echo $this->layout()->_t->translate("Fold Position");?></label>
<select id="foldpos" name="foldpos" class="zone-txtarea">
    <?php foreach ($foldpos_options as $code => $name): ?>
        <?php if ((string)$code === $current_foldpos): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>

	</div>
<div class="control-group">
		<label for="frequency"><?php echo $this->layout()->_t->translate("Frequency in last 24 hours");?></label>
		<input type="text" name="frequency" value="<?php echo $frequency_option;?>" class="input-mini">
	</div>
	</div>
	<div class="span7">
	<div>
		<label for="timezone"><?php echo $this->layout()->_t->translate("Timezone");?></label>
<select id="timezone" name="timezone[]" class="zone-txtarea" multiple style="min-height: 200px">
    <?php foreach ($timezone_options as $code => $name): ?>
        <?php if (in_array((string)$code, $current_timezones)): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
	</div>
	<div class="control-group">
		<label for="iniframe"><?php echo $this->layout()->_t->translate("In An IFrame?");?></label>
<select id="iniframe" name="iniframe" class="zone-txtarea">
    <?php foreach ($iniframe_options as $code => $name): ?>
        <?php if ((string)$code === $current_iniframe): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>

	</div>
<div class="control-group">
		<label for="inmultiplenestediframes"><?php echo $this->layout()->_t->translate("In Multiple Nested IFrames?");?></label>
<select id="inmultiplenestediframes" name="inmultiplenestediframes" class="zone-txtarea">
    <?php foreach ($inmultiplenestediframes_options as $code => $name): ?>
        <?php if ((string)$code === $current_inmultiplenestediframes): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>

	</div>
<div class="control-group">
		<label for="minscreenresolutionwidth"><?php echo $this->layout()->_t->translate("Min Screen Resolution Width");?> : <span class="hlp"><small><i>(<?php echo $this->layout()->_t->translate("eg. 500 [in px]");?>)</i></small></span></label>
		<input type="text" name="minscreenresolutionwidth" value="<?php echo $minscreenresolutionwidth_option;?>" class="input-mini">
	</div>
<div class="control-group">
		<label for="maxscreenresolutionwidth"><?php echo $this->layout()->_t->translate("Max Screen Resolution Width ");?>: <span class="hlp"><small><i>(<?php echo $this->layout()->_t->translate("eg. 1400 [in px]");?>)</i></small></span></label>
		<input type="text" name="maxscreenresolutionwidth" value="<?php echo $maxscreenresolutionwidth_option;?>" class="input-mini">
	</div>
<div class="control-group">
		<label for="minscreenresolutionheight"><?php echo $this->layout()->_t->translate("Min Screen Resolution Height");?> : <span class="hlp"><small><i>(<?php echo $this->layout()->_t->translate("eg. 300 [in px]");?>)</i></small></span></label>
		<input type="text" name="minscreenresolutionheight" value="<?php echo $minscreenresolutionheight_option;?>" class="input-mini">
	</div>
<div class="control-group">
		<label for="maxscreenresolutionheight"><?php echo $this->layout()->_t->translate("Max Screen Resolution Height");?> : <span class="hlp"><small><i>(<?php echo $this->layout()->_t->translate("eg. 1200 [in px]");?>)</i></small></span></label>
		<input type="text" name="maxscreenresolutionheight" value="<?php echo $maxscreenresolutionheight_option;?>" class="input-mini">
	</div>
	<div class="control-group">
		<label for="httplanguage"><?php echo $this->layout()->_t->translate("Http Language");?> : <span class="hlp"><small><i>( <?php echo $this->layout()->_t->translate("Example: en-us,en;q=0.5");?> )</i></small></span></label>
		<input type="text" name="httplanguage" value="<?php echo $httplanguage_option;?>" class="input-medium">
	</div>

<div class="control-group">
		<label for="browseruseragentgrep"><?php echo $this->layout()->_t->translate("Browser User Agent Grep");?> : <span class="hlp"><small><i>( <?php echo $this->layout()->_t->translate("Non-Empty matches UserAgent String, Example: Firefox/23");?> )</i></small></span></label>
		<input type="text" name="browseruseragentgrep" value="<?php echo $browseruseragentgrep_option;?>" class="zone-txtbox">
	</div>

	<div class="control-group">
		<label for="cookiegrep"><?php echo $this->layout()->_t->translate("Cookie Grep");?> : <span class="hlp"><small><i>( <?php echo $this->layout()->_t->translate("Non-Empty matches Cookie String, Example: pcv:1|uid:123");?> )</i></small></span></label>
		<input type="text" name="cookiegrep" value="<?php echo $cookiegrep_option;?>" class="zone-txtbox">
	</div>

<div class="control-group">
		<label for="pmpenable"><?php echo $this->layout()->_t->translate("Pmp Enable");?></label>
<select id="pmpenable" name="pmpenable" class="zone-txtarea"> 
    <?php foreach ($pmpenable_options as $code => $name): ?>
        <?php if ((string)$code === $current_pmpenable): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>

	</div>
   <div class="control-group">
		<label for="secure"><?php echo $this->layout()->_t->translate("Secure");?></label>
<select id="secure" name="secure"  class="zone-txtarea">
    <?php foreach ($secure_options as $code => $name): ?>
        <?php if ((string)$code === $current_secure): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>

	</div>

    <div class="control-group">
		<label for="optout"><?php echo $this->layout()->_t->translate("Optout");?></label>
<select id="optout" name="optout" class="zone-txtarea">
    <?php foreach ($optout_options as $code => $name): ?>
        <?php if ((string)$code === $current_optout): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>

	</div>
	</div>
	<div class="span12">
<div class="control-group">
	   <input type="submit" class="btn btn-primary" name="B1" value="<?php echo $this->layout()->_t->translate("Edit Banner Filter Settings");?>" />
	</div>
	</div>
</fieldset>
</form>
</div>