<?php
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/AppTable.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/qtip/jquery.qtip.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/static/css/qtip/jquery.qtip.min.css');

$this->headScript()->captureStart() ?>
function submitForm() {
	$('#loginas').submit();
}

$(document).ready(function () {

    $('span[title]').qtip();
    
});

<?php $this->headScript()->captureEnd();  
$effective_user_in_dashboard = false;
?>
<div class="docs-header">
  <div class="topic">
    <div class="row">
      <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-6"><h4>Campaigns List</h4></div>
      <div class="col-md-5 col-sm-5 text-right col-xs-6"><a href="<?php echo $this->basePath() ?>/demand/createcampaign" class="btn btn-success mrg5T">Create Campaign</a></div>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-md-4 col-md-offset-8">
         <?php if ($is_admin === true): ?>
        
         <form name="loginas" id="loginas" action="<?php echo $this->basePath() ?>/demand/loginas" class="form-inline" >
          <span style="font-size: 12px; font-weight: bold;">LOG IN AS USER</span>
          <select name="userid" onchange="submitForm();" class="form-control">
            <option value="0">Admin (<?php echo $true_user_name; ?>)</option>
            <?php foreach ($user_id_list as $user_info_id => $user_info_name): ?>
              <option <?php 
              if ($user_info_id == $effective_id): 
                $effective_user_in_dashboard = true; 
                echo 'selected="selected"'; 
              endif; ?> value="<?php echo $user_info_id;?>"><?php echo $user_info_name;?></option>
            <?php endforeach; ?>
          </select>
         </form>
         <?php endif; ?>
    </div>
  </div>
</div>




<div class="steps-container step1">

<div id="container">
<div class="row mrg20T">
<div class="col-md-10 col-md-offset-1 col-sm-12 panel">
<div class="pull-left" style="margin: 10px 0 0 10px;">
  <?php if ($effective_id != 0 && $effective_user_in_dashboard === true): ?>

            <form name="changeusermarkup" id="changeusermarkup" action="<?php echo $this->basePath() ?>/demand/changeusermarkup"class="form-inline" >
              <input type="hidden" name="markupuserid" value="<?php echo $effective_id;?>" />
          
            <span style="font-size: 12px; font-weight: bold;">User Markup Rate:</span>
            <input type="text"  style="text-align: right; width: 50px" name="user-markup" class="form-control" value="<?php echo $user_markup_rate;?>">%
              <div style="display: inline;">
                <input type="submit" name="user-markup-submit" class="btn actv  btn-small" value="Change User Markup" style="margin-left: 8px; margin-bottom: 10px;" title="The Rate that the Impressions Will be Marked up from the Bid Price (Your Profit)" />
              </div>
            </form>

  <?php endif; ?>
</div>
    <div class="formbox">      
      <br clear="all"/>

    <div class="table-filter row">
      <div class="col-sm-4">
        Ad Statistic:
        <select id="campaign-statistic" onchange="DomainTable.reload_table()">
          <option value="0">Today</option>
          <option value="1">Yesterday</option>
          <option value="2">This week</option>
          <option value="3">Last week</option>
        </select>
      </div>
    </div>

    <div id="selection-results" class="steps-box">
      <table id="campaign-table" class="table table-hover table-striped table-bordered table-margin" data-url="<?php echo $this->basePath() ?>/demand/campaignlist">
        <thead>
          <tr>
            <?php if ($is_admin === true): ?>
              <th>
                USER ID
              </th>
              <th>
                ADMIN ACTION
              </th>
            <?php endif; ?>
            <?php if ($is_admin === true && $effective_id != 0): ?>
              <th>
                CAMPAIGN MARKUP
              </th>
            <?php endif; ?>
              <th style="text-align:center;">
                Id
              </th>
              <th style="text-align:center;">
                Name
              </th>
              <th>
                Status
              </th>
              <th>
                Start Date
              </th>
              <th>
                End Date
              </th>
              <th>
                Impressions Counter
              </th>
              <th>
                Max Impressions
              </th>
              <th>
                Current Spend
              </th>
              <th>
                Max Spend
              </th>         
          </tr>
        </thead>
      </table>
    </div>
    </div>
    </div>
    </div>
</div>



<div style="clear:both"></div>
<!-- Campaign Delete Modal -->
<input  type="hidden" name="modal_campaign_id" id="modal_campaign_id" value="0" />
<div class="modal fade" id="DeleteCampaignModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Delete Campaign</h4>
      </div>
      <div class="modal-body">
      <div id="campaign_alert_msg" class="alert alert-error" style="display: none;">Error</div>
		<p id="msg"></p>
<h5 style="color: #b94a48;">This action is a preview and must be approved!</h5>
      </div>
      <div class="modal-footer">
      <button type="button" data-loading-text="Processing..." id="campaign_yes_btn" class="btn btn-primary" onclick="deleteCampaignConfirm();">Yes</button>
        <button type="button" class="btn btn-default" id="campaign_no_btn" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>
<!-- Campaign Delete Modal -->