<?php
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/AppTable.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/qtip/jquery.qtip.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/static/css/qtip/jquery.qtip.min.css');

$this->headScript()->captureStart() ?>
function submitForm() {
	$('#loginas').submit();
}

$(document).ready(function () {

    $('span[title]').qtip();
    
});

<?php $this->headScript()->captureEnd();  
$effective_user_in_dashboard = false;
?>
<div class="docs-header">
  <div class="topic container-fluid">
    <div class="row">
      <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-6"><h4><?php echo $this->layout()->_t->translate("Campaigns List");?></h4></div>
      <?php
        if ($is_admin === false):
      ?>
      <div class="col-md-5 col-sm-5 text-right col-xs-6"><a href="<?php echo $this->basePath() ?>/demand/createcampaign" class="btn btn-success mrg5T"><?php echo $this->layout()->_t->translate("Create Campaign");?></a></div>
      <?php
        endif;
      ?>
    </div>
  </div>
</div>

<div class="steps-container step1">
<div id="container" class="container-fluid">
<div class="row mrg20T">
<div class="col-md-10 col-md-offset-1 col-sm-12 panel">
<div class="pull-left" style="margin: 10px 0 0 10px;">
  <?php if ($effective_id != 0 && $effective_user_in_dashboard === true): ?>

            <form name="changeusermarkup" id="changeusermarkup" action="<?php echo $this->basePath() ?>/demand/changeusermarkup"class="form-inline" >
              <input type="hidden" name="markupuserid" value="<?php echo $effective_id;?>" />
          
            <span style="font-size: 12px; font-weight: bold;"><?php echo $this->layout()->_t->translate("User Markup Rate:");?></span>
            <input type="text"  style="text-align: right; width: 50px" name="user-markup" class="form-control" value="<?php echo $user_markup_rate;?>">%
              <div style="display: inline;">
                <input type="submit" name="user-markup-submit" class="btn actv  btn-small" value="Change User Markup" style="margin-left: 8px; margin-bottom: 10px;" title="The Rate that the Impressions Will be Marked up from the Bid Price (Your Profit)" />
              </div>
            </form>

  <?php endif; ?>
</div>
    <div class="formbox">      
      <br clear="all"/>

    <div class="table-filter row">
      <div class="col-sm-4">
        <?php echo $this->layout()->_t->translate("Status:");?>
        <select id="campaign-status" onchange="CampaignTable.reload_table()">
          <option value><?php echo $this->layout()->_t->translate("All");?></option>
          <option value="0"><?php echo $this->layout()->_t->translate("Pending approval");?></option>
          <?php
            if ($is_admin === true):
          ?>
            <option value="1"><?php echo $this->layout()->_t->translate("Deleted");?></option>
          <?php endif; ?>
          <option value="2"><?php echo $this->layout()->_t->translate("Approved");?></option>
        </select>
      </div>
    </div>

    <div id="selection-results" class="steps-box">
      <table id="campaign-table" class="table table-hover table-striped table-bordered table-margin" data-url="<?php echo $this->basePath() ?>/demand/campaignlist">
        <thead>
          <tr>
              <th style="text-align:center;">
                #
              </th>
              <th style="text-align:center;">
                <?php echo $this->layout()->_t->translate("Name");?>
              </th>
              <th>
                <?php echo $this->layout()->_t->translate(" Campaign markup");?>
              </th>
              <th>
                <?php echo $this->layout()->_t->translate("User Name");?>
              </th>
              <th>
                <?php echo $this->layout()->_t->translate("Start Date");?>
              </th>
              <th>
                <?php echo $this->layout()->_t->translate("End Date");?>
              </th>
              <th>
                <?php echo $this->layout()->_t->translate("Impressions Counter");?>
              </th>
              <th>
                <?php echo $this->layout()->_t->translate("Max Impressions");?>
              </th>
              <th>
                <?php echo $this->layout()->_t->translate("Current Spend");?>
              </th>
              <th>
                <?php echo $this->layout()->_t->translate("Max Spend");?>
              </th>
              <th>
                <?php echo $this->layout()->_t->translate("Status");?>
              </th>
          </tr>
        </thead>
      </table>
    </div>
    </div>
    </div>
    </div>
</div>



<div style="clear:both"></div>
<!-- Campaign Delete Modal -->
<input  type="hidden" name="modal_campaign_id" id="modal_campaign_id" value="0" />
<div class="modal fade" id="DeleteCampaignModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel"><?php echo $this->layout()->_t->translate("Delete Campaign");?></h4>
      </div>
      <div class="modal-body">
      <div id="campaign_alert_msg" class="alert alert-error" style="display: none;"><?php echo $this->layout()->_t->translate("Error");?></div>
		<p id="msg"></p>
<h5 style="color: #b94a48;"><?php echo $this->layout()->_t->translate("This action is a preview and must be approved!");?></h5>
      </div>
      <div class="modal-footer">
      <button type="button" data-loading-text="Processing..." id="campaign_yes_btn" class="btn btn-primary" onclick="deleteCampaignConfirm();"><?php echo $this->layout()->_t->translate("Yes");?></button>
        <button type="button" class="btn btn-default" id="campaign_no_btn" data-dismiss="modal"><?php echo $this->layout()->_t->translate("No");?></button>
      </div>
    </div>
  </div>
</div>
<!-- Campaign Delete Modal -->