<?php
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/AppTable.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/qtip/jquery.qtip.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/static/css/qtip/jquery.qtip.min.css');

$this->headScript()->captureStart() ?>
function submitForm() {
  $('#loginas').submit();
}

$(document).ready(function () {

    $('span[title]').qtip();
    
});

<?php $this->headScript()->captureEnd();  
$effective_user_in_dashboard = false;
?>
<div class="docs-header">
  <div class="topic container-fluid">
    <div class="row">
      <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-6"><h4><?php echo $this->layout()->_t->translate("Report");?></h4></div>
      
    </div>
  </div>
</div>
<div class="steps-container step1 ">
  <div class="container-fluid">
    <div class="row mrg20T">
      <div id="revenue-overview" class="col-md-10 col-md-offset-1 panel pad20T">
        <p class="underline mrg0T" style="padding-bottom: 3px;">
          <span class="admin-titles"><?php echo $this->layout()->_t->translate("Overview")?>   </span>
            <select id="time-filter" onchange="ReportDemandTable.reload_table()">
              <option selected value><?php echo $this->layout()->_t->translate("All time")?></option>
              <option value="0"><?php echo $this->layout()->_t->translate("Today"); ?></option>
              <option value="1" selected><?php echo $this->layout()->_t->translate("Yesterday"); ?></option>
              <option value="2"><?php echo $this->layout()->_t->translate("This week"); ?></option>
              <option value="3"><?php echo $this->layout()->_t->translate("Last week"); ?></option>
              <option value="4"><?php echo $this->layout()->_t->translate("This month"); ?></option>
              <option value="5"><?php echo $this->layout()->_t->translate("Last month"); ?></option>
              <option value="6"><?php echo $this->layout()->_t->translate("This year"); ?></option>
        </select> 
        </p>
        <div class="row">
            <div class="col-sm-3"><?php echo $this->layout()->_t->translate("Outcome (USD): $");?><strong id="Outcomes">0</strong></div>
            <div class="col-sm-3"><?php echo $this->layout()->_t->translate("Click Total: "); ?><strong id="ClickTotal">0</strong> </div>
            <div class="col-sm-3"><?php echo $this->layout()->_t->translate("Impression Total: ");?><strong id="ImpTotal">0</strong> </div>
        </div>
        <br>
      </div>

    </div>
  </div>
  <div class="container-fluid">
    <div class="row mrg20T">
      <div id="income-list" class="col-md-10 col-md-offset-1 panel pad20T">
        <h4 class="underline mrg0T"><?php echo $this->layout()->_t->translate("Outcome List");?></h4>

        <table id="report-demand-table" class="table table-hover table-striped table-bordered table-margin" data-url="<?php echo $this->basePath() ?>/demand/reportlist?UserID=<?php echo $user_id ?>&CampaignID=<?php echo $campaign_id ?>">
          <thead>
            <tr>

              <th style="text-align:center;">#</th>
              <th style="text-align:center;"><?php echo $this->layout()->_t->translate("Ad-Campaign");?></th>
              <th style="text-align:center;"><?php echo $this->layout()->_t->translate("Ad-Banner");?></th>
              <th style="text-align:center;"><?php echo $this->layout()->_t->translate("Click Count");?></th>
              <th style="text-align:center;"><?php echo $this->layout()->_t->translate("Imp Count");?></th>
              <th style="text-align:center;"><?php echo $this->layout()->_t->translate("Outcome");?></th>
              <th style="text-align:center;"><?php echo $this->layout()->_t->translate("Date");?></th>

            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>

</div>
