<?php
$this->headScript()->appendFile($this->basePath() . '/static/js/3rdparty/jquery-ui-1.9.2.custom.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/static/css/jquery-ui/smoothness/jquery-ui-1.9.2.custom.min.css');
$this->headScript()->appendFile($this->basePath() . '/static/js/banner.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');


?>


<div class="docs-header">
  <div class="topic">
    <div class="container">
      <div ><h4><?php echo $campaignbanner_preview->Name;?> (<?php echo $campaignbanner_preview->AdCampaignBannerPreviewID;?>)</h4></div>
    </div>
  </div>
</div>

<div id="main-container">
	<div class="formbox">
    	<div class="container">
   			<div class="row">
      		<br />
      		<div class="col-md-8 col-md-offset-2 panel panel-default">
        		<div class="panel-body">
    			    <form id="ad" class="form-horizontal form-top-magin" name="ad" method="post" action="">
    			    	<?php if ($campaignbanner_preview->AdUrl != ""): ?>
	    			    	<h4 class="underline mrg0T"><?php echo $this->layout()->_t->translate("Banner Preview");?></h4>
	    			    	<img src="<?php echo $this->basePath().'/' . $campaignbanner_preview->AdUrl ?>" alt="<?php echo $campaignbanner_preview->AltText ?>" height="<?php echo $campaignbanner_preview->Height ?>" width="<?php echo $campaignbanner_preview->Width ?>" class="img-responsive center-block">
	    			    <?php endif; ?>
	    				<br>
						<h4 class="underline mrg0T"><?php echo $this->layout()->_t->translate("General Options");?></h4>
						<div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Ad Name");?></label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->Name;?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Label");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->Label;?></label>
						    </div>
						 </div>
						<div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Alt Text");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->AltText;?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Ad delivery type");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label">
						      	<?php 
						      		if ($campaignbanner_preview->ImpressionType == 'banner'):
						      			echo 'Banner Ad';
						      		elseif ($campaignbanner_preview->ImpressionType == 'video'):
						      			echo 'Video Ad';
						      		endif;
						      	?>
						      </label>
						    </div>
						 </div>
						<div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Start Date");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label">
						      	<?php
						      		$date = date_create($campaignbanner_preview->StartDate); 
						      		echo date_format($date,"Y-m-d"); 
						      	?>
						      </label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("End Date");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label">
						      	<?php
						   			$date = date_create($campaignbanner_preview->EndDate); 
						      		echo date_format($date,"Y-m-d"); 
						      	?>
						      </label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Device Ad type");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label">
						      	<?php 
						      		if ($campaignbanner_preview->IsMobile == '0'):
						      			echo 'Desktop';
						      		elseif ($campaignbanner_preview->IsMobile == '1'):
						      			echo 'Mobile';
						      		endif;
						      	?>
						      </label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("IAB Size");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->IABSize?></label>
						    </div>
						 </div>	
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Bid amount");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->BidAmount?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Daily Target");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->TargetDaily?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Maximum Target");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->TargetMax?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Daily Budget");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->DailyBudget?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Maximum Budget");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->MaximumBudget?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Ad tag");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->AdTag?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Landing page TLD");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->LandingPageTLD?></label>
						    </div>
						 </div>	
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("IAB Audiences Category");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo (isset($campaignbanner_preview->IABAudienceCategory) && $campaignbanner_preview->IABAudienceCategory != '') ? \util\DeliveryFilterOptions::$vertical_map[ $campaignbanner_preview->IABAudienceCategory ] : "" ?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("GEO Country");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo (isset($campaignbanner_preview->GEOCountry) && $campaignbanner_preview->GEOCountry != '') ? \util\DeliveryFilterOptions::$geo_country[ $campaignbanner_preview->GEOCountry ] : "" ?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Timezone");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo (isset($campaignbanner_preview->TimeZone) && $campaignbanner_preview->TimeZone != '') ? \util\DeliveryFilterOptions::$timezone_options[  $campaignbanner_preview->TimeZone ] : "" ?></label>
						    </div>
						 </div>	
					</form>
        		</div>
        	</div>
        </div>
    </div>


	<div class="formbox">
    	<div class="container">
   			<div class="row">
      		<br />
      		<div class="col-md-8 col-md-offset-2 panel panel-default">
        		<div class="panel-body">
    			    <form id="ad" class="form-horizontal form-top-magin" name="ad" method="post" action="">
						<h4 class="underline mrg0T"><?php echo $this->layout()->_t->translate("Advance Options");?></h4>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4">Ad tag-type </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->AdTagType?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("In an Iframe");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label">
						      	<?php 
						      		if($campaignbanner_preview->InAnIframe == '0'):
						      			echo "false";
						      		elseif ($campaignbanner_preview->InAnIframe == '1'):
						      			echo 'true';
						      		endif;
						      	?>
						      </label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("In Multiple Nested IFrames");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label">
						      	<?php 
						      		if($campaignbanner_preview->MultiNestedIframe == '0'):
						      			echo "No preference";
						      		elseif ($campaignbanner_preview->MultiNestedIframe == '1'):
						      			echo 'Yes';
						      		elseif ($campaignbanner_preview->MultiNestedIframe == '2'):
						      			echo 'No';
						      		endif;
						      	?>
						    </div>
						 </div>	
					</form>
        		</div>
        	</div>
        </div>
    </div>

	<div class="formbox">
    	<div class="container">
   			<div class="row">
      		<br />
      		<div class="col-md-8 col-md-offset-2 panel panel-default">
        		<div class="panel-body">
    			    <form id="ad" class="form-horizontal form-top-magin" name="ad" method="post" action="">
						<h4 class="underline mrg0T"><?php echo $this->layout()->_t->translate("Position Options");?></h4>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4">Ad position </label>
						    <div class="controls col-sm-8">
						      <label class="control-label">
						      	<?php
						      		if ($campaignbanner_preview->AdPostLeft == '0'):
						      			echo 'Min Left';
						      		elseif ($campaignbanner_preview->AdPostLeft == '1'):
						      			echo 'Max Left';
						      		endif;

						      		if ($campaignbanner_preview->AdPostTop == '0'):
						      			echo ' - Min Top';
						      		elseif ($campaignbanner_preview->AdPostTop == '1'):
						      			echo ' - Max Top';
						      		endif;
						      	?>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Fold position");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label">
						      	<?php
						      		if ($campaignbanner_preview->FoldPosition == '1'):
						      			echo 'Not available/ applicable';
						      		elseif ($campaignbanner_preview->FoldPosition == '2'):
						      			echo 'Completely Above the Fold';
						      		elseif ($campaignbanner_preview->FoldPosition == '3'):
						      			echo 'Completely Below the Fold';
						      		elseif ($campaignbanner_preview->FoldPosition == '4'):
						      			echo 'Partially Above the Fold';
						      		endif;
						      	?></label>
						    </div>
						 </div>	
					</form>
        		</div>
        	</div>
        </div>
    </div>

	<div class="formbox">
    	<div class="container">
   			<div class="row">
      		<br />
      		<div class="col-md-8 col-md-offset-2 panel panel-default">
        		<div class="panel-body">
    			    <form id="ad" class="form-horizontal form-top-magin" name="ad" method="post" action="">
						<h4 class="underline mrg0T"><?php echo $this->layout()->_t->translate("Resolution Options");?></h4>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4">Min screen res width </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->ResolutionMinW?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Max screen res width");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->ResolutionMaxW?></label>
						    </div>
						 </div>	
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Min screen res height");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->ResolutionMinH?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Max screen res height");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->ResolutionMaxH?></label>
						    </div>
						 </div>	
					</form>
        		</div>
        	</div>
        </div>
    </div>

	<div class="formbox">
    	<div class="container">
   			<div class="row">
      		<br />
      		<div class="col-md-8 col-md-offset-2 panel panel-default">
        		<div class="panel-body">
    			    <form id="ad" class="form-horizontal form-top-magin" name="ad" method="post" action="">
						<h4 class="underline mrg0T"><?php echo $this->layout()->_t->translate("Other Options");?></h4>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("HTTP language");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->HttpLang?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Browser User Agent Grep");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->BrowerAgentGrep?></label>
						    </div>
						 </div>	
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Cookie Grep");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->CookieGrep?></label>
						    </div>
						 </div>
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Pmp enable");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->PmpEnable?></label>
						    </div>
						 </div>	
						 <div class="form-group">
						    <label for="adname" class="control-label col-sm-4"><?php echo $this->layout()->_t->translate("Secure");?> </label>
						    <div class="controls col-sm-8">
						      <label class="control-label"><?php echo $campaignbanner_preview->Secure?></label>
						    </div>
						 </div>	
					</form>
        		</div>
        	</div>
        </div>
    </div>  
</div>