<?php

$children = $this->viewModel()->getCurrent()->getChildren();
$child = null;
if (isset($children[0])):
	$child = $children[0];
endif;
$extra_main_content_class = "";
$home_dashboard_view = "demand";
if ($child != null && isset($child->dashboard_view)):
	$home_dashboard_view = $child->dashboard_view;
endif;

$home_link = $home_dashboard_view;
if ($home_link == "account"):
	$home_link = "users/" . $home_dashboard_view;
elseif ($home_link == "login" || $home_link == "company"):
	$home_link = "";
endif;

if ($child != null && isset($child->center_class)):
	$extra_main_content_class = " " . $child->center_class;
endif;

$user_name = $user_data = $userRole = null;
if(isset($child->user_identity)):
	//$user_name = strtoupper($child->user_identity->getUsername());
	
	$user_data = unserialize($child->user_identity->serialize());
	$user_name = strtoupper($user_data->user_fullname);
	
	$userRole = $child->user_identity->getRoles();
	$userRole = $userRole[0];
endif;

echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <base href="<?php echo $this->basePath() ?>" >
        <?php echo $this->headTitle('BGate')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'href' => $this->basePath() . '/images/favicon.png')); ?>

<link href="<?php echo $this->basePath() . '/static/bootstrap/dist/css/bootstrap.css' ?>" media="screen" rel="stylesheet" type="text/css">
<link href="<?php echo $this->basePath() . '/static/bootflat/css/bootflat.min.css' ?>" media="screen" rel="stylesheet" type="text/css">
<link href="<?php echo $this->basePath() . '/static/bgate/site.css' ?>" media="screen" rel="stylesheet" type="text/css">
<link href="<?php echo $this->basePath() . '/static/bgate/spacing.css' ?>" media="screen" rel="stylesheet" type="text/css">
<link href="<?php echo $this->basePath() . '/static/css/dataTables.bootstrap.css' ?>" media="screen" rel="stylesheet" type="text/css">

        <script> /* lvduit */ var basePath = '<?php echo $this->basePath() ?>'; </script> 

        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/static/js/3rdparty/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/static/js/3rdparty/jquery.validate.min.js')
                                      ->prependFile($this->basePath() . '/static/js/3rdparty/bootstrap.js')
                                      ->prependFile($this->basePath() . '/static/bootflat/js/icheck.min.js')
                                      ->prependFile($this->basePath() . '/static/js/dataTables.bootstrap.js')
                                      ->prependFile($this->basePath() . '/static/js/jquery.dataTables.js')
                                      ->prependFile($this->basePath() . '/static/js/3rdparty/jquery-1.11.1.min.js');

                                       ?>
       <!--<link href='//fonts.googleapis.com/css?family=Cabin' rel='stylesheet' type='text/css'>-->
       <link href='//fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>                               
    </head>
    <body class="demand-dashboard">
      <div class="navbar navbar-default navbar-custom">

            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php echo $this->basePath() ?>/<?php echo $home_link; ?>">
                        <img src="<?php echo $this->basePath() ?>/static/images/bda_logo.png" height="45">
                    </a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <?php if ($this->Login_bool() == false):?>
                        <li class="<?php if($home_dashboard_view == " signup ") echo "active ";?>"><a class="navlink" href="<?php echo $this->basePath() ?>/signup">Signup</a></li>
                        <li class="divider-vertical"></li>
                        <?php else:?>
                        <?php if ($userRole=='admin' || $userRole=='superadmin'): ?>
                            <li class="<?php if($home_dashboard_view == " demand ") echo "active ";?>">
                                <a class="navlink" href="<?php echo $this->basePath() ?>/manager/index">
                                    <?php echo $this->layout()->_t->translate("Dashboard");?>
                                </a>
                            </li>         
                            <li class="divider-vertical"></li>
                        <?php endif;?>
                        <?php if ($user_data != null && $user_data->DemandCustomerInfoID != null): ?>
                            <li class="<?php if($home_dashboard_view == " demand ") echo "active ";?>">
                                <a class="navlink" href="<?php echo $this->basePath() ?>/demand/dashboard">
                                    <?php echo $this->layout()->_t->translate("Dashboard");?>
                                </a>
                            </li>         
                            <li class="divider-vertical"></li>
                        <?php endif;?>
                        <?php if (($user_data != null && $user_data->DemandCustomerInfoID != null) || $userRole=='admin' || $userRole=='superadmin'): ?>
                        <li class="<?php if($home_dashboard_view == " demand ") echo "active ";?>"><a class="navlink" href="<?php echo $this->basePath() ?>/demand"><?php echo $this->layout()->_t->translate("Campaign");?></a></li>
                        <li class="divider-vertical"></li>
                        <?php endif;?>

                        <?php if ($user_data != null && $user_data->DemandCustomerInfoID != null): ?>
                        <li class="<?php if($home_dashboard_view == " publisher ") echo "active ";?>"><a class="navlink" href="<?php echo $this->basePath() ?>/demand/report"><?php echo $this->layout()->_t->translate("Report");?></a></li>
                        <li class="divider-vertical"></li>
                        <?php endif;?>


                        <?php if ($user_data != null && $user_data->PublisherInfoID != null): ?>
                            <li class="<?php if($home_dashboard_view == " publisher ") echo "active ";?>">
                                <a class="navlink" href="<?php echo $this->basePath() ?>/publisher/dashboard">
                                    <?php echo $this->layout()->_t->translate("Dashboard");?>
                                </a>
                            </li>
                            
                            <li class="divider-vertical"></li>
                        <?php endif;?>

                        <?php if (($user_data != null && $user_data->PublisherInfoID != null) || $userRole=='admin' || $userRole=='superadmin'): ?>
                        <li class="<?php if($home_dashboard_view == " publisher ") echo "active ";?>"><a class="navlink" href="<?php echo $this->basePath() ?>/publisher"><?php echo $this->layout()->_t->translate("Domain");?></a></li>
                        <li class="divider-vertical"></li>
                        <?php endif;?>

                        <?php if ($user_data != null && $user_data->PublisherInfoID != null): ?>
                        <li class="<?php if($home_dashboard_view == " publisher ") echo "active ";?>"><a class="navlink" href="<?php echo $this->basePath() ?>/publisher/report"><?php echo $this->layout()->_t->translate("Report");?></a></li>
                        <li class="divider-vertical"></li>
                        <?php endif;?>

                        <?php if ($userRole=='admin' || $userRole=='superadmin'): ?>
                            <li class="<?php if($home_dashboard_view == " demand ") echo "active ";?>">
                                <a class="navlink" href="<?php echo $this->basePath() ?>/users/publishers">
                                    <?php echo $this->layout()->_t->translate("Publisher List");?>
                                </a>
                            </li>         
                            <li class="divider-vertical"></li>
                        <?php endif;?>
                        <?php if ($userRole=='admin' || $userRole=='superadmin'): ?>
                            <li class="<?php if($home_dashboard_view == " demand ") echo "active ";?>">
                                <a class="navlink" href="<?php echo $this->basePath() ?>/users/customers">
                                    <?php echo $this->layout()->_t->translate("Customer List");?>
                                </a>
                            </li>         
                            <li class="divider-vertical"></li>
                        <?php endif;?>

                        <li class="divider-vertical"></li>
                        <?php endif;?>
                        <li class="<?php if($home_dashboard_view == " login ") echo "active ";?><?php if($home_dashboard_view == "account ") echo "active ";?>">
                            <?php if ($this->Login_bool() == true):?>
                            <a data-toggle="dropdown" class="dropdown-toggle navlink">
                                <?php echo $user_name;?> <span class="caret"></span></a>
                            <ul class="dropdown-menu pull-right">
                                <?php if ($userRole!='admin' && $userRole!='superadmin'): ?>
                                  <li><a href="<?php echo $this->basePath() ?>/users/account"><?php echo $this->layout()->_t->translate("Account Settings");?></a></li>
                                <?php endif; ?>
                                <base></base>
<!--                                 <?php if($userRole=='admin' || $userRole=='superadmin' ): ?>
                                <li><a href="<?php echo $this->basePath() ?>/users/publishers">Publisher List</a></li>
                                <li><a href="<?php echo $this->basePath() ?>/users/customers">Customer List</a></li>
                                <?php endif;?> -->
                                <li><a href="<?php echo $this->url('login/process', array('action'=>'logout')); ?>"><?php echo $this->layout()->_t->translate("Logout");?></a></li>
                            </ul>
                            <?php else: ?>
                            <a class="navlink" href="<?php echo $this->url('login/process', array('action'=>'login')); ?>">Login</a>
                            <?php endif; ?>
                        </li>
                    </ul>
                </div>
            </div>

      </div>


        <!--div class="container bottom-container">
        	<div class="compLayout<?php echo $extra_main_content_class; ?>" id="main-container">

              <?php if (isset($child) && $child != null && isset($child->user_id_list)):?>
              <h4 class="headbreadcrumb blue-color">
              <?php if (isset($child->header_title)):	
              	echo $child->header_title;
               endif; ?>
                  <br clear="all">
                  <div class="pull-right black-color negative-margin"> <?php 
                      // If Admin, show which account you are creating for.
                          if($child->impersonate_id == "0" || $child->impersonate_id == null || !isset($child->user_id_list[intval($child->effective_id)])):
                              echo "<img src='static/images/man-icon.png' /> " . $child->true_user_name;
                          else:
                              echo "<img src='static/images/man-icon.png' /> " . $child->user_id_list[intval($child->effective_id)];
                          	if ($child->is_admin === true):
                          		echo " (" . $child->effective_id . ")";
                          	endif;
                          endif;
                      ?>
                      </div> <div class="pull-right">
                        <br clear="all">
                     
                     </div>
              </h4>
              <?php endif; ?>
            </div>
          </div-->
	            <?php echo $this->content; ?>
            
	            <footer class="footer">
	            <div class="">
                  

                  <div class="footer-copyright text-center">Copyright © 2015 ISLab. <?php echo $this->translate('All rights reserved.') ?></div>

              </div>
            </footer>
           
        
<!-- Domain Delete Modal -->
<input  type="hidden" name="modal_domain_id" id="modal_domain_id" value="0" />
<div class="modal fade" id="DeleteDomainModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Delete Domain</h4>
      </div>
      <div class="modal-body">
      <div id="domain_alert_msg" class="alert alert-error" style="display: none;">Error</div>
    <p id="msg"></p>
<h5 style="color: #b94a48;">This action is IMMEDIATE and NOT REVERSABLE!</h5>
      </div>
      <div class="modal-footer">
      <button type="button" data-loading-text="Processing..." id="domain_yes_btn" class="btn btn-primary" onclick="deleteDomainConfirm();">Yes</button>
        <button type="button" class="btn btn-default" id="domain_no_btn" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>
<!-- Domain Delete Modal -->
        <?php echo $this->inlineScript() ?>
		<?php echo file_get_contents("app/DashboardManager/view/support/support.js"); ?>
    </body>
</html>
