<div class="docs-header">
  <div class="topic">
    <div class="row">
      <div class="col-sm-5 col-xs-offset-1"><h4>Ad-zone - <?php echo $editResultObj->AdName . " (" . $editResultObj->PublisherAdZoneID .")" ?></h4></div>
      <div class="col-sm-5 text-right">
          <a href="<?php echo $this->basePath() ?>/publisher/zone/<?php echo $domain_obj->PublisherWebsiteID ?>/edit/<?php echo $editResultObj->PublisherAdZoneID ?>" class="btn btn-primary btn-margin mrg5T">Edit</a> &nbsp;
          
      </div>
       
          
        </div>
  </div>
</div>
<?php
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/zone.js');
$this->headScript()->captureStart() ?>
$(function() {
  $("form.form-horizontal").validate({
     ignore: ".ignore"
  })
  switchImpressionType();
});
<?php $this->headScript()->captureEnd();  ?>
   <!-- <ul class="breadcrumb breadcrumb-heading">
    <li><a href="/publisher/">Domains</a><span class="divider">/</span></li>
    <li><a href="/publisher/zone/<?php echo $domain_obj->PublisherWebsiteID;?>"><?php echo $domain_obj->WebDomain;?></a><span class="divider">/</span></li>
    <li><a href="/publisher/zone/<?php echo $domain_obj->PublisherWebsiteID;?>">Zones</a><span class="divider">/</span></li>
    <li><?php echo $editResultObj->AdName;?><span class="divider">/</span></li>
    <li>Edit Zone</li>
    </ul> -->
<?php 
    if($error_message != "" && $error_message !== null && isset($error_message)):
      echo '<div id="cdn_form_success" class="alert alert-error" style="margin: 5px;">'. $error_message .'</div>';
    endif;
?>
<div id="cdn_form_msg" class="alert alert-error" style="margin: 5px; display:none;"></div>
    <div id="main-container">

    <div class="formbox">
    <div class="container">
    <div class="row">
      <br />
      <div class="col-md-8 col-md-offset-2 panel panel-default">
        <div class="panel-body">
    <form id="ad" class="form-horizontal form-top-magin" name="ad" method="post" action="/publisher/zone/<?php echo $editResultObj->PublisherWebsiteID;?>/edit/<?php echo $editResultObj->PublisherAdZoneID;?>/">
    <div class="form-group">
    <label for="adname" class="control-label col-sm-3">Ad Name</label>
    <div class="controls col-sm-7">
      <label class="control-label" ><?php echo $editResultObj->AdName;?></label>
    </div>
    </div>
    <div class="form-group">
    <label for="adname" class="control-label col-sm-3">Ad Delivery Type</label>
    <div class="controls col-sm-7 error">
      <label class="control-label" ><?php echo $editResultObj->ImpressionType ?></label>
    </div>
    </div>
<div class="form-group">
    <label for="Description" class="control-label col-sm-3">Description</label>
    <div class="controls col-sm-7">
      <label class="control-label" ><?php echo $editResultObj->Description;?></label>   
    </div>
    </div>
<div class="form-group" id="passback-cg">
    <label for="PassbackAdTag" id="passbackTag" class="control-label col-sm-3">Passback Ad Tag</label>
    <div class="controls col-sm-7">
 <label class="control-label" ><?php echo $editResultObj->PassbackAdTag;?></label>    </div>
    </div>
    <div class="form-group" id="floor-cg">
              <label for="FloorPrice" class="control-label col-sm-3">Floor Price</label>
              <div class="controls col-sm-7">
              <label class="control-label" >$<?php echo $editResultObj->FloorPrice;?></label></div>
            </div>
    <?php if ($is_admin): ?>
    <div class="form-group">
    <label for="PublisherAdZoneTypeID" class="control-label col-sm-3">Zone type?</label>
    <div class="controls col-sm-7">
        <select id="PublisherAdZoneTypeID"  class="selbox-width" name="PublisherAdZoneTypeID" onchange="switchPublisherAdZoneType();">
            <?php foreach ($publisheradzonetype_options as $code => $name): ?>
                <?php if ((string)$code === $current_publisheradzonetype): ?>
                    <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
                <?php else: ?>
                    <option value="<?php echo $code;?>"><?php echo $name;?></option>
                <?php endif; ?>
            <?php endforeach; ?>
        </select>
        <div id="banner-picker"></div>
       </div>
      </div>
    <?php endif; ?>
<!--     <div class="form-group">
     <label for="IsMobileFlag" class="control-label col-sm-3">Is Mobile?</label>
    <div class="controls col-sm-7">
    <label><input type="radio" <?php if($editResultObj->IsMobileFlag == "0"): echo 'checked="checked"';endif;?> value="0" id="IsMobileFlag" name="IsMobileFlag">No</label>
    <label><input type="radio" <?php if($editResultObj->IsMobileFlag == "1"): echo 'checked="checked"';endif;?> value="1" name="IsMobileFlag">Yes</label> 
       </div>
    </div> -->
     
     <div class="form-group novideo">
     <label for="Templates" class="control-label col-sm-3">Templates</label>
    <div class="controls col-sm-7">
      <label class="control-label" ><?php echo $AdTemplateList[$editResultObj->AdTemplateID];?></label>
  </div>
    </div>
    
    <div class="form-group">
    <label for="Width" class="control-label col-sm-3">Ad Width</label>
    <div class="controls col-sm-7">
    <label class="control-label" ><?php echo $editResultObj->Width?></label>
    </div>
    </div>   
    
    <div class="form-group">
    <label for="Height" class="control-label col-sm-3">Ad Height</label>
    <div class="controls col-sm-7">
    <label class="control-label" ><?php echo $editResultObj->Height;?></label>
    </div>
    </div>
    
    <div class="form-group nobanner" style="display: none;">
    <label for="MinDuration" class="control-label col-sm-3">Minimum Ad Duration : <span class="hlp"><small><i>(required)</i></small></span></label>
    <div class="controls col-sm-7">
    <input type="text" value="<?php echo $current_min_duration;?>" class="input-mini" size="5" maxlength="10" id="MinDuration" name="MinDuration">
    </div> 
    </div>  
    
    <div class="form-group nobanner" style="display: none;">
    <label for="MaxDuration" class="control-label col-sm-3">Maximum Ad Duration : <span class="hlp"><small><i>(required)</i></small></span></label>
    <div class="controls col-sm-7">
    <input type="text" value="<?php echo $current_max_duration;?>" class="input-mini" size="5" maxlength="10" id="MaxDuration" name="MaxDuration">   </div>
    </div>
    
      <div class="form-group nobanner" style="display: none;">
    <label for="Mimes" class="control-label col-sm-3">Mimes : <span class="hlp"><small><i>(required, ctrl+shift to select mutliple)</i></small></span></label>
    <div class="controls col-sm-7">
<select id="Mimes" name="Mimes[]" multiple class="form-control" style="min-height: 170px">
     <?php if (!count($current_mimes)): ?>
      <?php foreach ($mimes as $name): ?>
        <option value="<?php echo $name;?>" selected="selected"><?php echo $name;?></option>
      <?php endforeach; ?>
     <?php else: ?>
      <?php foreach ($mimes as $name): ?>
          <?php if (in_array((string)$name, $current_mimes)): ?>
              <option value="<?php echo $name;?>" selected="selected"><?php echo $name;?></option>
          <?php else: ?>
              <option value="<?php echo $name;?>"><?php echo $name;?></option>
          <?php endif; ?>
      <?php endforeach; ?>
    <?php endif; ?>
</select>
  </div>
  </div> 
  
   <div class="form-group nobanner" style="display: none;">
    <label for="Protocols" class="control-label col-sm-3">Protocols : <span class="hlp"><small><i>(ctrl+shift to select mutliple)</i></small></span></label>
    <div class="controls col-sm-7">
<select id="Protocols" name="Protocols[]" multiple class="form-control" style="min-height: 50px">
    <?php foreach ($protocols as $code => $name): ?>
        <?php if (in_array((string)$code, $current_protocols)): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
  </div>
  </div> 
  
   <div class="form-group nobanner" style="display: none;">
    <label for="ApisSupported" class="control-label col-sm-3">Apis Supported : <span class="hlp"><small><i>(ctrl+shift to select mutliple)</i></small></span></label>
<div class="controls col-sm-7">
  <select id="ApisSupported" name="ApisSupported[]" multiple class="form-control" style="min-height: 130px">
    <?php foreach ($apis_supported as $code => $name): ?>
        <?php if (in_array((string)$code, $current_apis_supported)): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
  </div>
  </div>
  
   <div class="form-group nobanner" style="display: none;">
    <label for="Delivery" class="control-label col-sm-3">Video Delivery : <span class="hlp"><small><i>(ctrl+shift to select mutliple)</i></small></span></label>
<div class="controls col-sm-7">
<select id="Delivery" name="Delivery[]" multiple class="form-control" style="min-height: 50px">
    <?php foreach ($delivery_methods as $code => $name): ?>
        <?php if (in_array((string)$code, $current_delivery_methods)): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
  </div>
  </div>
  
   <div class="form-group nobanner" style="display: none;">
    <label for="Playback" class="control-label col-sm-3">Video Playback : <span class="hlp"><small><i>(ctrl+shift to select mutliple)</i></small></span></label>
    <div class="controls col-sm-7">
    <select id="Playback" name="Playback[]" multiple class="form-control" style="min-height: 90px">
    <?php foreach ($playback_methods as $code => $name): ?>
        <?php if (in_array((string)$code, $current_playback_methods)): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
  </div>
  </div>
  
   <div class="form-group nobanner" style="display: none;">
    <label for="StartDelay" class="control-label col-sm-3">Start Delay :</label>
    <div class="controls col-sm-7">
<select id="StartDelay" name="StartDelay">
    <?php foreach ($start_delay as $code => $name): ?>
        <?php if ((string)$code == $current_start_delay): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
  </div>
  </div>
  
   <div class="form-group nobanner" style="display: none;">
    <label for="Linearity" class="control-label col-sm-3">Linearity :</label>
    <div class="controls col-sm-7">
<select id="Linearity" name="Linearity">
    <?php foreach ($linearity as $code => $name): ?>
        <?php if ((string)$code == $current_start_delay): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
  </div>
  </div>
  
   <div class="form-group nobanner" style="display: none;">
    <label for="FoldPos" class="control-label col-sm-3">Fold Position :</label>
    <div class="controls col-sm-7">
<select id="FoldPos" name="FoldPos">
    <?php foreach ($fold_pos as $code => $name): ?>
        <?php if ((string)$code == $current_fold_pos): ?>
            <option value="<?php echo $code;?>" selected="selected"><?php echo $name;?></option>
        <?php else: ?>
            <option value="<?php echo $code;?>"><?php echo $name;?></option>
        <?php endif; ?>
    <?php endforeach; ?>
</select>
  </div>
  </div>

    <div class="form-group">
    <label  class="control-label col-sm-3">Total requests</label>
    <div class="controls col-sm-7">
    <label class="control-label" ><?php echo $editResultObj->TotalRequests;?></label>
    </div>
    </div>

    <div class="form-group">
    <label  class="control-label col-sm-3">Total Impressions Filled</label>
    <div class="controls col-sm-7">
    <label class="control-label" ><?php echo $editResultObj->TotalImpressionsFilled;?></label>
    </div>
    </div>

    <div class="form-group">
    <label  class="control-label col-sm-3">Revenue</label>
    <div class="controls col-sm-7">
    <label class="control-label" >$<strong id="adzone-revenue"></strong></label>
    </div>
    </div>

    <div class="form-group">
    <label  class="control-label col-sm-3">Created At</label>
    <div class="controls col-sm-7">
    <label class="control-label" ><?php echo $editResultObj->DateCreated;?></label>
    </div>
    </div>

    <div class="form-group">
    <label class="control-label col-sm-3">Updated At</label>
    <div class="controls col-sm-7">
    <label class="control-label" ><?php echo $editResultObj->DateUpdated;?></label>
    </div>
    </div>
<hr>
<div class="form-group text-center">
    <div class="controls">
    
    <a class="btn btn-margin" href="<?php echo $this->basePath() ?>/publisher/zone/<?php echo $domain_obj->PublisherWebsiteID;?>">Back</a> 
    </div>
    </div>
    <input type="hidden" value="0" name="AdOwnerID">
    <input type="hidden" value="<?php echo $editResultObj->PublisherAdZoneID;?>" name="PublisherAdZoneID" id="PublisherAdZoneID">
    <input type="hidden" value="<?php echo $domain_obj->PublisherWebsiteID;?>" name="PublisherWebsiteID">
</form> 
</div>
    </div>
    </div>
    </div>
    </div>
    </div>

