<?php
$this->headScript()->prependFile($this->basePath() . '/static/js/script.js');
$this->headScript()->prependFile($this->basePath() . '/static/js/signup.js');
?>

<div class="docs-header">
  <div class="topic">
      <div class="container">
    
        <h4>Create Your Publisher Account.</h4>

      </div>
      <!-- <div class="topic__infos">
        <div class="container">
          <a href="<?php echo $this->basePath() ?>/signup/customer">Demand Customers Sign-up Here</a>
        </div>
      </div> -->
    </div>
</div>

<div class="container">
  <div class="row">
    <br />
    <div class="col-md-8 col-md-offset-2 panel panel-default">
        <div class="panel-body">
          <form id="signupform" name="signupform" class="form-horizontal form-top-magin" method="post" action="<?php echo $this->basePath() ?>/signup/newuser">
            <?php 
                if(isset($error_msg) && $error_msg != null):
                
                  echo '<div id="cdn_form_error" class="alert alert-danger" style="margin: 5px;">'.$error_msg.'</div>';
                endif;
                if(isset($success_msg) && $success_msg != null):
                
                  echo '<div id="cdn_form_success" class="alert alert-success" style="margin: 5px;">Account created successfully. You will receive a welcome email when your account is approved by our Ad Operations Team</div>';
                endif;
            ?>
            <div id="cdn_form_dynamic_msg" class="alert alert-danger" style="margin: 5px; display:none;"></div>
            <div id="cdn_form_msg" class="alert alert-danger" style="margin: 5px; display:none;"></div>

            <div class="form-group mrg20B mrg10T underline">
              <h4 class="mrg0A">Account Information</h4>    
            </div>
            
            <div class="form-group">
                <label for="Email" class="control-label col-sm-3">Email</label>
                <div class="controls col-sm-7">
                <input type="text" value="" class="form-control" maxlength="50" name="Email" id="Email" placeholder="me@example.com">
                </div>
            </div>
            <div class="form-group">
                <label for="Username" class="control-label col-sm-3">Username</label>
                <div class="controls col-sm-7">
                  <input type="text" value="" class="form-control" maxlength="50" name="user_login" id="user_login" placeholder="username">
                </div>
            </div>
            <div class="form-group">
                <label for="password" class="control-label col-sm-3">Password</label>
                <div class="controls col-sm-7">
                  <input type="password" value="" class="form-control" name="Password" id="Password">    
                </div>
            </div> 

            <div class="form-group">
                <label for="Confirm_password" class="control-label col-sm-3">Confirm Password</label>
                <div class="controls col-sm-7">
                <input type="Password" value=""  class="form-control" name="Confirm_password" id="Confirm_password">    </div>
            </div> 
            
            <div class="form-group mrg20B underline">
              <h4 class="mrg0A">Contact Information</h4>    
            </div>
            <div class="form-group">
                <label for="FirstName" class="control-label col-sm-3">First Name</label>
                <div class="controls col-sm-7">
                <input type="text" value="" class="form-control" maxlength="100" name="FirstName" id="FirstName">    </div>
            </div>
            <div class="form-group">
                <label for="LastName" class="control-label col-sm-3">Last Name</label>
                <div class="controls col-sm-7">
                <input type="text" value="" class="form-control" maxlength="100" name="LastName" id="LastName">    </div>
            </div>
            <div class="form-group">
                <label for="Country" class="control-label col-sm-3">Country</label>
                <div class="controls col-sm-7">
                <!-- <input type="text" value="" class="form-control" name="Country" id="Country">   -->

                <select id="Country"  class="selbox-width form-control"  name="Country" >         
                        <?php foreach($country as $key => $value): ?>                   
                            <?php //if ((string)$key === $banner->GEOCountry): ?>
                            <!-- <option value="<?php echo $key;?>" selected="selected"><?php echo $value;?></option> -->
                            <?php //else: ?>
                                <option value="<?php echo $key;?>"><?php echo $value;?></option>
                            <?php //endif; ?>
                        <?php endforeach;?>
                </select>

                </div>
            </div>
            <div class="form-group">
                <label for="City" class="control-label col-sm-3">City</label>
                <div class="controls col-sm-7">
                <input type="text" value="" class="form-control" maxlength="100" name="City" id="City">    </div>
            </div>
            <div class="form-group">
                <label for="Addr" class="control-label col-sm-3">Address</label>
                <div class="controls col-sm-7">
                <input type="text" value="" class="form-control" maxlength="255" name="Addr" id="Addr">    </div>
            </div>
            
            <div class="form-group mrg20B underline">
              <h4 class="mrg0A">Main WebSite Information</h4>    
            </div>

            <div class="form-group">
                <label for="Domain" class="control-label col-sm-3">Website</label>
                <div class="controls col-sm-7">
                <input type="text" value="" class="form-control" maxlength="50" name="Domain" id="Domain" placeholder="example.com">    </div>
            </div>
            <div class="form-group">
                <label for="Domain" class="control-label col-sm-3">Website Describe</label>
                <div class="controls col-sm-7">
                  <textarea  rows="4" class="form-control" name="DomainDescribe" id="DomainDescribe"></textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="IABCategory" class="control-label col-sm-3">IABCategory</label>
                <div class="controls col-sm-7">
                <select id="IABCategory" class="form-control" name="IABCategory">
                   <?php 
                   foreach($vertical_map as $key=>$value): 
                  echo '<option value="'. $key .'">'. $value .'</option>';
                 endforeach;
                 ?>
              </select>
              </div>

            </div> 
            <hr>
            <div class="form-group">
              <label style="display: inline" class=" checked"> <input id="accept-agreement" type="checkbox" class="" name="aggreement" value="1" />&nbsp;By checking this box I confirm I have read, understand, acknowledge and accept <a href="">Privacy policy</a> and <a href="">User Agreement</a></label>
            </div>
              <div class="text-center">
               <button name="b1" type="button" class="btn btn-success btn-lg signupform" id="submitbutton" disabled>Create Account</button>
              </div>
            
          
          </form>
        </div>

    </div>
  </div>
</div>

<br />