<div class="container" id="privacy-container">
    <div class="row">
      <br>

      <div class="col-md-10 col-md-offset-1 panel panel-default">
        <div class="panel-body">
          <h2 class="mrg10T mrg10B text-center">BDA Privacy
          Policy</h2>

          <div class="row">
            <div class="col-md-3">
              <nav class="bs-docs-sidebar hidden-print hidden-xs hidden-sm">
                <ul class="nav bs-docs-sidenav">
                  <li><a href="#">Introduction</a></li>

                  <li><a href="#bgate-collect-info">What Information does BGATE collect?</a></li>

                  <li><a href="#bgate-share-info">Does BGATE share my information?</a></li>

                  <li><a href="#bgate-cookie">Does BGATE use cookies?</a></li>

                  <li><a href="#stop-using-bgate">Want to stop seeing ads delivered through BGATE?</a></li>

                  <li><a href="#bgate-use-beacon">Does BGATE use web beacons?</a></li>

                  <li><a href="#bgate-policy-other-site">Does the BGATE privacy apply to other sites?</a></li>

                  <li><a href="#access-pii">How do I access my PII?</a></li>

                  <li><a href="#info-secure">Is my information secure?</a></li>

                  <li><a href="#info-transfered">Will my information be transferred?</a></li>

                  <li><a href="#what-if-bgate-change-policy">What if BGATE changes this privacy policy?</a></li>

                  <li><a href="#contact-us">Contact Us</a></li>
                </ul>
              </nav>
            </div>

            <div class="col-md-9">
              <div id="bgate-collect-info">
                <h4 class="underline">Introduction</h4>

                <p><strong>BDA</strong> <strong>JSC</strong> .,
                (“<strong>BDA</strong>”, “<strong>BGATE</strong>”,
                “<strong>we</strong>”, or “<strong>our</strong>”) values the
                privacy of our users, members, and others who visit and use
                <a href="http://www.bda.com.vn">www.bda.com.vn</a> (the
                “<strong>BGATE</strong> <strong>Site</strong>”) (collectively
                or individually “<strong>Users</strong>” or
                “<strong>you</strong>”). The BGATE Site may contain information
                regarding a variety of services offered by BGATE (collectively
                the “<strong>Services</strong>”). This statement
                (“<strong>Privacy Policy</strong>”) governs information you
                provide to us or that we learn from your use of the BGATE Site
                and tells you how we may collect, use, and in some instances
                share this information.</p>
              </div>

              <div>
                <h4 class="underline">What Information does BGATE collect?</h4>

                <p><span style=
                "text-decoration: underline">Registration</span><br>
                In order to use the Services, you must first complete the
                registration form, and choose a password. During registration,
                you must provide contact information, such as your name, phone
                number, company name and website. We use this information to
                create your account, and to contact you in regards to the
                Services.</p>

                <p><span style="text-decoration: underline">Orders</span><br>
                If you wish to fund your account, you must provide your address
                and financial information (e.g. credit card number; expiry
                date; etc). We use this information for billing purposes, and
                to process your order. If we have trouble processing an order,
                we will use the information we collected to contact you.</p>

                <p><span style="text-decoration: underline">Surveys or
                Contests</span><br>
                From time to time, we may provide you the opportunity to
                participate in contests or surveys on our site. If you
                participate, we may request certain personally identifiable
                information from you. Participation in these surveys or
                contests is completely voluntary, and you therefore have a
                choice whether or not to disclose this information. We use this
                information to notify contest winners and award prizes, and to
                process and analyze survey results.</p>

                <p>We use a third party service provider to conduct these
                surveys or contests; that company is prohibited from using our
                users’ personally identifiable information for any other
                purpose.</p>

                <p><span style="text-decoration: underline">Other
                Sources</span><br>
                We collect usage data about you whenever you interact with our
                Services. This may include which of our pages you visit, what
                you click on, when you performed those actions, and so on.
                Additionally, like most websites today, our web servers keep
                log files that record data each time a device accesses those
                servers. The log files contain data about the nature of each
                access, including originating IP addresses.</p>

                <p>We collect data from the device and application you use to
                access our services, such as your IP address and browser type.
                We may also infer your geographic location based on your IP
                address.</p>

                <p>If you arrive at our website from an external source (such
                as a link on another website or in an email), we record
                information about the source that referred you to us.</p>

                <p>We use third party tracking services that employ cookies and
                page tags (also known as <a href=
                "http://en.wikipedia.org/wiki/Web_bug" target="_blank">web
                beacons</a>) to collect aggregated and anonymized data about
                visitors to our websites. This data includes usage and user
                statistics, but not personally identifiable information.</p>

                <p><span style="text-decoration: underline">Uses of
                Information</span><br>
                In addition to the above-noted reasons, we use the information
                we collect to provide you with the Services. This includes
                providing you with customer support, which requires us to
                access your information to assist you (such as with campaign
                creation or technical troubleshooting).</p>

                <p>We also use your information for the following purposes:</p>

                <p>1. To monitor and improve our services and features. We
                internally perform statistical and other analysis on
                information we collect (including usage data, device data,
                referral data, and information from page tags) to analyze and
                measure user behavior and trends, to understand how people use
                our services, and to monitor, troubleshoot and improve our
                Services.</p>

                <p>2. To assist the enforcement of our Terms of Service.</p>

                <p>3. To prevent potentially illegal activities.</p>

                <p>4. To screen for undesirable or abusive activity.</p>

                <p>5. To create new services, features or content. We may use
                any information you provide us (e.g. via email or through our
                ticketing system) to create and provide new services, features
                or content. For example, we may publish interesting
                observations from the surveys for informational or marketing
                purposes. When we do this, we will not personally identify you,
                unless we first receive your permission.</p>

                <p>6. To contact you about your service or account. We
                occasionally send you communications of a transactional nature
                (e.g. service-related announcements, billing-related matters,
                changes to our services or policies, welcome emails when you
                first register, etc). You can’t opt out of these
                communications, since they are necessary in order for us to
                effectively provide our services to you.</p>

                <p>7. To contact you for marketing purposes (if you opt-in on
                our registration page). We will only do this if you have given
                us your express permission to contact you for this purpose.</p>

                <p id="bgate-share-info">8. To respond to legal requests and prevent harm. If we
                receive a subpoena or other legal request, we may need to
                inspect the data we hold to determine how to respond.</p>
              </div>

              <div>
                <h4 class="underline">Does BGATE share my information?</h4>
                  <p>
                      <u>Aggregate Information (non-personally identifiable)</u>
                      <br/>
                      We share aggregate information about our users for marketing purposes. We also share aggregate information with third party providers, in order to provide
                      the services (as noted above).
                  </p>
                  <p>
                      We do not link aggregate user data with personally identifiable information.
                  </p>
                  <p>
                      <u>Personally identifiable information</u>
                      <br/>
                      We share personally identifiable information (PII) with certain third parties, in order to provide you with the Services. For example, we use a credit card
                      processing company to bill you for the Services, and share PII with them in order to do so. They do not retain, share, store or use PII for any other
                      purpose. In certain instances, we may share PII with our suppliers (data and inventory exchanges). Finally, we share PII with our parent company and
                      subsidiaries, for record-keeping purposes, billing purposes, and for general business purposes.
                  </p>
                  <p id="bgate-cookie">
                      <u>Legal Disclaimer</u>
                      <br/>
                      We reserve the right to disclose your PII as required by law, and when we believe that disclosure is necessary to protect our rights and/or to comply with
                      any applicable judicial proceeding, court order, or legal process.
                  </p>
              </div>

              <div>
                <h4 class="underline">Does BGATE use cookies?</h4>
                <p>
                    Yes. “Cookies” are pieces of information (actually, alphanumeric identifiers) generated by web servers, and stored on your web browser for future access.
                    Cookies cannot view or retrieve data from other cookies, nor can they capture files or data stored on your computer. We do not link the information that we
                    store in cookies to any PII that you submit while on our site.
                </p>
                <p>
                    We use both session ID cookies and persistent cookies. We use session cookies to make it easier for you to navigate our site. A session ID cookie expires
                    when you close your browser. A persistent cookie remains on your hard drive for an extended period of time. You can remove persistent cookies by following
                    directions provided in your web browser’s “help” file.
                </p>
                <p>
                    We set a persistent cookie to store your passwords, so you don’t have to enter it more than once. Persistent cookies also enable us to track and target the
                    interests of our users to enhance the experience on our site.
                </p>
                <p id="stop-using-bgate">
                    If you reject cookies, you may still use our site, but your ability to use some areas of our site will be limited.
                </p>
                <p >
                For more information on cookies, see:    <a href="http://www.allaboutcookies.org/faqs/cookie-file.html" target="_blank">http://www.allaboutcookies.org/faqs/cookie-file.html</a>
                </p>
              </div>


              <div>
                <h4 class="underline">Want to stop seeing ads delivered through BGATE?</h4>
                <p>
    There is more than one way to opt out of cookies: manually delete your cookies by following the instructions contained in the “Help” section of your
    browser. We will no longer deliver ads targeted to your preferences and usage patterns.
</p>
<p id="bgate-use-beacon">
    In order to opt-out you must have cookies enabled: In order for the opt-out process to work correctly on your computer, the browser must be set to accept
    third party cookies. If you use a different computer, change web browsers or delete this cookie, you will need to opt-out again.
</p>
              </div>


              <div>
                <h4 class="underline">Does BGATE use web beacons (aka clear GIFs or web bugs)?</h4>
                <p>
    Yes. “Web beacons” are small images (generally a single transparent pixel) with a unique identifier, served to you as part of a web page or other document.
    Web beacons may be used in parts of our Services for purposes such as site traffic reporting, unique visitor counts, advertising auditing and reporting,
    and personalization. In certain instances, we may tie the information gathered by web beacons to PII.
</p>
<p id="bgate-policy-other-site">
    Through our partners, we use web beacons in our HTML-based emails to let us know which emails recipients have opened. This allows us to gauge the
    effectiveness of certain communications and the effectiveness of our marketing campaigns.
</p>
<p>
For more information on web beacons, see:    <a href="http://www.allaboutcookies.org/faqs/beacons.html" target="_blank">http://www.allaboutcookies.org/faqs/beacons.html</a>
</p>
              </div>


              <div>
                <h4 class="underline">Does the BGATE privacy apply to other sites?</h4>
                <p>
    This sites contains links to other sites that are not owned or controlled by BGATE. We are not responsible for the privacy practices of such other sites.
</p>
<p id="access-pii">
    We encourage you to be aware when you leave our site, and to read the privacy statements of each and every site that collects personally identifiable
    information.
</p>
<p>
    This privacy statement applies only to information collected by BGATE.
</p>
              </div>

              <div>
                <h4 class="underline">How do I access my PII?</h4>
                <p>
    You have the right to access, update, and correct inaccuracies in your PII in our custody and control, subject to certain exceptions prescribed by law. You
may request access, updating and corrections of inaccuracies in the personal information we have in our custody or control by emailing us at    <a id="info-secure" href="mailto:privacy@bda.com.vn.">privacy@bda.com.vn.</a> We may request certain personal information for the purposes of verifying your identity when
    requesting access to or correction of your personal information records.
</p>
<p>
    If your personally identifiable information changes, or if you no longer desire our Services, you may correct, update, delete or deactivate it by emailing
    us at <a href="mailto:privacy@bda.com.vn.">privacy@bda.com.vn.</a>
</p>
              </div>

              <div>
                <h4 class="underline">Is my information secure?</h4>
                <p>
    Yes, the portions of our website (and our other Services) that handle sensitive confidential information are secure. We are committed to maintaining the
    security of your information and have measures in place to protect against the loss, misuse, and alteration of the information under our control. We employ
    industry-standard techniques to protect our systems from intrusion by unauthorized individuals. Our data center utilizes state-of-the-art physical security
    measures to prevent unauthorized access to the facility. In addition, all information is stored in a secure location behind firewalls and other
    sophisticated security systems with limited (need-to-know) administrative access. All BGATE employees who have access to, or are associated with, the
    processing of personal information are contractually obligated to respect the confidentiality of your information and abide by the privacy standards we
    have established.
</p>
<p>
    Please be aware that no security measures are perfect or impenetrable. Therefore, while we strive to use commercially acceptable means to protect your
    personal information, we cannot guarantee its absolute security.
</p>
              </div>

              <div>
                <h4 class="underline">Will my information be transferred?</h4>
                <p id="what-if-bgate-change-policy">
    In the event that BGATE (or its parent or subsidiary companies) goes through a business transition, such as a merger, acquisition by another company, or
    sale of all or a portion of its assets, your personally identifiable information will likely be among the assets transferred. You will be notified via
    prominent notice on our site for 30 days of any such change in ownership or control of your personal information.
</p>
              </div>

              <div>
                <h4 class="underline">What if BGATE changes this privacy policy?</h4>
                <p id="contact-us">We reserve the right to modify this privacy statement at any time, so please review it frequently. If we decide to change our privacy policy, we will post the updated version, together with an updated Effective Date, on this page. We encourage you to check this page periodically for any changes.
                </p>
              </div>

              <div>
                <h4 class="underline">Contact Us</h4>
                <p>
    If you have any questions or suggestions regarding our privacy policy, please contact us:
</p>
<p>
    <h5>BGATE</h5>
    Attn: Privacy Officer
    <br/>
    27 Duc Dien S, Phuc Dien Ward., Tu Liem North District,
</p>
<p>
    Ha Noi, Vietnam
</p>
<p>
    <a href="mailto:privacy@bda.com.vn">privacy@bda.com.vn</a>
</p>
              </div>

              <div>
              </div>

              <div>
              </div>              

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>