<?php
$this->headScript()->prependFile($this->basePath() . '/static/js/script.js');
$this->headScript()->prependFile($this->basePath() . '/static/js/AppTable.js');
?>
<div class="docs-header">
	<div class="topic">
	    <div class="container">
	        <div ><h4><?php echo $this->layout()->_t->translate("Payment");?></h4></div>
	    </div>
	</div>
</div>
<div class="container-fluid mrg20T ">
  <div class="row">
    <div class="panel col-md-10 col-md-offset-1">
      <div class="panel-body">
        <p class="underline mrg0T" style="padding-bottom: 3px;">
          <span class="admin-titles"><?php echo $this->layout()->_t->translate("You balance");?>: $<?php echo $balance; ?></span>
        </p>
        <div id="payment-form" class="" >
          <div id="cdn_form_msg" class="alert alert-danger" style="display:none;"><?php echo $this->layout()->_t->translate("Required fields are missing.");?></div>
          <div class="form-group">
              <label for="exampleInputEmail1" class=" control-label"><?php echo $this->layout()->_t->translate("Add money to your account");?></label>
              <!-- <div class="col-sm-10"> -->
              <div class="input-group">
                <span class="input-group-addon" id="basic-addon1">$</span>
                 <input type="number" class="form-control" name="Amount" id="Amount" placeholder="Enter Amount" onchange="payment_form_value()">
              </div>
               
              <!-- </div> -->
            </div>
          <div class="form-group">
                <p class="text-center">
                <a data-href="<?php echo $paypal_url;?>" class="btn btn-default disabled" id="method-payal">
                  <img src="<?php echo $this->basePath() .'/';?>static/images/payal.svg" alt="payal" style="height:32px">
                </a>
                <a data-href="<?php echo $onepay_url;?>" class="btn btn-default disabled" id="method-onepay">
                  <img src="<?php echo $this->basePath() .'/';?>static/images/onepay.png" alt="onepay" style="height:32px">
                </a>
                </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

  <div class="container-fluid">
    <div class="row mrg20T">
      <div id="revenue-overview" class="col-md-10 col-md-offset-1 panel pad20T">
        <p class="underline mrg0T" style="padding-bottom: 3px;">          
        <span class="admin-titles"><?php echo $this->layout()->_t->translate("Transaction log");?> </span>
            <select id="time-filter" onchange="PaymentTable.reload_table()">
              <option selected value><?php echo $this->layout()->_t->translate("All time");?></option>
              <option value="0"><?php echo $this->layout()->_t->translate("Today");?></option>
              <option value="1"><?php echo $this->layout()->_t->translate("Yesterday");?></option>
              <option value="2"><?php echo $this->layout()->_t->translate("This week");?></option>
              <option value="3"><?php echo $this->layout()->_t->translate("Last week");?></option>
              <option value="4"><?php echo $this->layout()->_t->translate("This month");?></option>
              <option value="5"><?php echo $this->layout()->_t->translate("Last month");?></option>
              <option value="6"><?php echo $this->layout()->_t->translate("This year");?></option>
            </select> 
        </p>
        <div class="">
          <table id="payment-table" class="table table-striped table-bordered table-margin" data-url="<?php echo $this->basePath() ?>/payment/paymentinit">
            <thead>
              <tr>
               <th>
    				      <?php echo $this->layout()->_t->translate("ID");?>
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("Payment Method");?>  
               </th>
               <th>
                	<?php echo $this->layout()->_t->translate("Type");?>	
               </th>
                <th>
                	<?php echo $this->layout()->_t->translate("Amount");?>
               </th>
               <th>
               	  <?php echo $this->layout()->_t->translate("Description");?>  
               </th>
               <th>
               	  <?php echo $this->layout()->_t->translate("DateCreated");?>  
               </th>
              </tr>
            </thead>
          </table>
        </div>
        <br>
      </div>

    </div>
  </div>
