<?php
$this->headScript()->prependFile($this->basePath() . '/static/js/script.js');
?>
<div class="docs-header">
	<div class="topic">
	    <div class="container">
	        <div ><h4>Payment</h4></div>
	    </div>
	</div>
</div>

<div class="container mrg20T ">
	<div class="row">
		<div class="panel col-md-8 col-md-offset-2">
			<div class="panel-body">

				<form id="payment-form" class="form-horizontal" method="post">
					<div id="cdn_form_msg" class="alert alert-danger" style="display:none;">Required fields are missing.</div>
					<div class="form-group">
					    <label for="exampleInputEmail1" class="col-sm-2 control-label">Amount</label>
					    <div class="col-sm-10">
					    	<input type="number" class="form-control" name="Amount" id="Amount" placeholder="Enter Amount">
					    </div>
					  </div>
					<div class="form-group">
					    <label for="exampleInputEmail1" class="col-sm-2 control-label">Method</label>
						<div class="col-sm-10">
							<div class="radio">
								<label>
								    <input type="radio" name="method" id="method-payal" value="0" checked>
								    payal
								</label>
							</div>
							<div class="radio">
								<label>
								    <input type="radio" name="method" id="method-onepay" value="1">
								    onepay
								</label>
							</div>
						</div>
					</div>
					<hr>
					<div class="form-group text-center">
					    <div class="controls">
					        <button name="submit" type="submit" class="btn btn-primary btn-margin" id="submitbutton">Payment</button> 
					        <a href="http://localhost/bgate/manager/index" class="btn btn-margin">Cancel</a>
					    </div>
					</div>

				</form>
			</div>
		</div>
	</div>
</div>