<?php
$this->headScript()->prependFile($this->basePath() . '/static/js/script.js');
?>
<div class="docs-header">
	<div class="topic">
	    <div class="container">
	        <div ><h4><?php echo $this->layout()->_t->translate("Payment");?></h4></div>
           
	    </div>
	</div>
</div>

<div class="container">
<div class="b-thanks">
    <h1><strong><a><?php echo $this->layout()->_t->translate("TRANSACTION RESULT!");?></a></strong></h1>
    <h3><strong><?php echo $transaction->Result; ?></strong></h3>
    
    <h4><i><?php echo $transaction->ResponseDescription;?></i></h4>
    
    <p>
        <?php echo $this->layout()->_t->translate("Thank you for payment!");?>
    </p>
    <p class="text-center"><a href="<?php echo $callback;?>" class="btn btn-default mrg5T">
        <span class="glyphicon glyphicon-share-alt"></span> <?php echo $this->layout()->_t->translate("Payment");?></a>
    </p>
</div>
</div>