<?php
$this->headScript()->prependFile($this->basePath() . '/static/js/script.js');
?>
<div class="docs-header">
	<div class="topic">
	    <div class="container">
	        <div ><h4>Payment</h4></div>
	    </div>
	</div>
</div>

<div class="container">
<div class="b-thanks">
    <h1><strong><a>TRANSACTION RESULT!</a></strong></h1>
    <h3><strong><?php echo $transaction->TransactionDetail; ?></strong></h3>
    <p>
        Thank you for payment! <br>
        <small><?php echo $transaction->ResponseDescription;?></small>
    </p>

</div>
</div>