<?php
/**
 * BGate Project
 * 
 * @version 1.x
 * @author ISLab UIT
 * @copyright (C) 2015 
 */

namespace util;

class DeliveryFilterOptions {

    public static $foldpos_options = array(
    		""=>"Not available/applicable",
    		"1"=>"Completely Above the Fold",
    		"2"=>"Completely Below the Fold",
    		"3"=>"Partially Above the Fold"
    );

    public static $adtagtype_options = array(
    		""=>"None",
    		"JavaScript"=>"JavaScript",
    		"Iframe"=>"IFrame"
    );

    public static $iniframe_options = array(
    		""=>"No Preference",
    		"0"=>"No IFrame Ads",
    		"1"=>"Yes IFrame Ads"
    );

    public static $inmultiplenestediframes_options = array(
    		""=>"No Preference",
    		"0"=>"No Multiple Nested IFrame Ads",
    		"1"=>"Yes Multiple Nested IFrame Ads"
    );

    public static $timezone_options = array(
    		""=>"None",
    		"-12"=>"(GMT -12:00) Eniwetok, Kwajalein",
    		"-11"=>"(GMT -11:00) Midway Island, Samoa",
    		"-10"=>"(GMT -10:00) Hawaii",
    		"-9"=>"(GMT -9:00) Alaska",
    		"-8"=>"(GMT -8:00) Pacific Time (US &amp; Canada)",
    		"-7"=>"(GMT -7:00) Mountain Time (US &amp; Canada)",
    		"-6"=>"(GMT -6:00) Central Time (US &amp; Canada), Mexico City",
    		"-5"=>"(GMT -5:00) Eastern Time (US &amp; Canada), Bogota, Lima",
    		"-4"=>"(GMT -4:00) Atlantic Time (Canada), Caracas, La Paz",
    		"-3.5"=>"(GMT -3:30) Newfoundland",
    		"-3"=>"(GMT -3:00) Brazil, Buenos Aires, Georgetown",
    		"-2"=>"(GMT -2:00) Mid-Atlantic",
    		"-1"=>"(GMT -1:00 hour) Azores, Cape Verde Islands",
    		"0"=>"(GMT) Western Europe Time, London, Lisbon, Casablanca",
    		"1"=>"(GMT +1:00 hour) Brussels, Copenhagen, Madrid, Paris",
    		"2"=>"(GMT +2:00) Kaliningrad, South Africa",
    		"3"=>"(GMT +3:00) Baghdad, Riyadh, Moscow, St. Petersburg",
    		"3"=>"(GMT +3:30) Tehran",
    		"4"=>"(GMT +4:00) Abu Dhabi, Muscat, Baku, Tbilisi",
    		"4.5"=>"(GMT +4:30) Kabul",
    		"5"=>"(GMT +5:00) Ekaterinburg, Islamabad, Karachi, Tashkent",
    		"5.5"=>"(GMT +5:30) Bombay, Calcutta, Madras, New Delhi",
    		"5.75"=>"(GMT +5:45) Kathmandu",
    		"6"=>"(GMT +6:00) Almaty, Dhaka, Colombo",
    		"7"=>"(GMT +7:00) Bangkok, Hanoi, Jakarta",
    		"8"=>"(GMT +8:00) Beijing, Perth, Singapore, Hong Kong",
    		"9"=>"(GMT +9:00) Tokyo, Seoul, Osaka, Sapporo, Yakutsk",
    		"9.5"=>"(GMT +9:30) Adelaide, Darwin",
    		"10"=>"(GMT +10:00) Eastern Australia, Guam, Vladivostok",
    		"11"=>"(GMT +11:00) Magadan, Solomon Islands, New Caledonia",
    		"12"=>"(GMT +12:00) Auckland, Wellington, Fiji, Kamchatka"
    );

    public static $pmpenable_options = array(
    		""=>"No Preference",
    		"0"=>"PMP Enable Off",
    		"1"=>"PMP Enable On"
    );

    public static $secure_options = array(
    		""=>"No Preference",
    		"0"=>"https:// Secure Off",
    		"1"=>"https:// Secure On"
    );

    public static $optout_options = array(
    		""=>"No Preference",
    		"0"=>"Accept Users who have not Opted Out",
    		"1"=>"Accept OptOut Users"
    );

    public static $vertical_options = array(
    		""=>"No Preference",
    		"1"=>"Not Applicable",
            "2"=>"Automotive",
            "3"=>"Business and Finance",
            "8"=>"Education",
            "9"=>"Employment and Career",
            "10"=>"Entertainment and Leisure",
            "12"=>"Gaming",
            "14"=>"Health and Fitness",
            "16"=>"Home and Garden",
            "18"=>"Men's Interest",
            "21"=>"Music",
            "23"=>"News",
            "24"=>"Parenting and Family",
            "27"=>"Real Estate",
            "28"=>"Reference",
            "29"=>"Food and Dining",
            "31"=>"Shopping",
            "32"=>"Social Networking",
            "33"=>"Sports",
            "34"=>"Technology",
            "36"=>"Travel",
            "38"=>"Women's Interest"
    );
    
    public static $vertical_map = array(
    		/*
			 * also covers 1-x for sub-categories
			 * get the first 4-5 chars substring and
			 * only compare the main categories
			 *
			 * Ex: IAB10-2 becomes IAB10 and matches to 16
			 */
				
			"IAB1"=>"Arts & Entertainment",  			
			"IAB2"=>"Automotive",			
			"IAB3"=>"Business",			 
			"IAB4"=>"Careers",			
			"IAB5"=>"Education",			
			"IAB6"=>"Family & Parenting",			
			"IAB7"=>"Health & Fitness",			
			"IAB8"=>"Food & Drink",			
			"IAB9"=>"Hobbies & Interests",			
			"IAB10"=>"Home & Garden",			
			"IAB11"=>"Law, Gov't & Politics",		
			"IAB12"=>"News",			
			"IAB13"=>"Personal Finance",			
			"IAB14"=>"Society",			 
			"IAB15"=>"Science",			
			"IAB16"=>"Pets",			
			"IAB16"=>"Sports",			
			"IAB18"=>"Style & Fashion",			
			"IAB19"=>"Technology & Computing",			
			"IAB20"=>"Travel",			
			"IAB21"=>"Real Estate",			
			"IAB22"=>"Shopping",			
			"IAB23"=>"Religion & Spirituality",			
			"IAB24"=>"Uncategorized",			
			"IAB25"=>"Non-Standard Content",			
			"IAB26"=>"Illegal Content"
    );
    
     public static $optout_options3 = array(
    		""=>"No Preference",
    		"0"=>"Accept Users who have not Opted Out",
    		"1"=>"Accept OptOut Users"
    );
    
    public static $partner_type = array(
                "1" =>"ad network",
                "2" =>"brand manager for digital",
                "3" =>"self-serve",
                "4" =>"marketing manager"
    );
    public static $geo_country = array(
        '' => "No Preference",
        'AFG'=>'Afghanistan',
        'ALA'=>'Åland',
        'ALB'=>'Albania',
        'DZA'=>'Algeria',
        'ASM'=>'American Samoa',
        'AND'=>'Andorra',
        'AGO'=>'Angola',
        'AIA'=>'Anguilla',
        'ATA'=>'Antarctica',
        'ATG'=>'Antigua and Barbuda',
        'ARG'=>'Argentina',
        'ARM'=>'Armenia',
        'ABW'=>'Aruba',
        'AUS'=>'Australia',
        'AUT'=>'Austria',
        'AZE'=>'Azerbaijan',
        'BHS'=>'Bahamas',
        'BHR'=>'Bahrain',
        'BGD'=>'Bangladesh',
        'BRB'=>'Barbados',
        'BLR'=>'Belarus',
        'BEL'=>'Belgium',
        'BLZ'=>'Belize',
        'BEN'=>'Benin',
        'BMU'=>'Bermuda',
        'BTN'=>'Bhutan',
        'BOL'=>'Bolivia',
        'BES'=>'Bonaire',
        'BIH'=>'Bosnia and Herzegovina',
        'BWA'=>'Botswana',
        'BVT'=>'Bouvet Island',
        'BRA'=>'Brazil',
        'IOT'=>'British Indian Ocean Territory',
        'VGB'=>'British Virgin Islands',
        'BRN'=>'Brunei',
        'BGR'=>'Bulgaria',
        'BFA'=>'Burkina Faso',
        'BDI'=>'Burundi',
        'KHM'=>'Cambodia',
        'CMR'=>'Cameroon',
        'CAN'=>'Canada',
        'CPV'=>'Cape Verde',
        'CYM'=>'Cayman Islands',
        'CAF'=>'Central African Republic',
        'TCD'=>'Chad',
        'CHL'=>'Chile',
        'CHN'=>'China',
        'CXR'=>'Christmas Island',
        'CCK'=>'Cocos [Keeling] Islands',
        'COL'=>'Colombia',
        'COM'=>'Comoros',
        'COK'=>'Cook Islands',
        'CRI'=>'Costa Rica',
        'HRV'=>'Croatia',
        'CUB'=>'Cuba',
        'CUW'=>'Curacao',
        'CYP'=>'Cyprus',
        'CZE'=>'Czech Republic',
        'COD'=>'Democratic Republic of the Congo',
        'DNK'=>'Denmark',
        'DJI'=>'Djibouti',
        'DMA'=>'Dominica',
        'DOM'=>'Dominican Republic',
        'TLS'=>'East Timor',
        'ECU'=>'Ecuador',
        'EGY'=>'Egypt',
        'SLV'=>'El Salvador',
        'GNQ'=>'Equatorial Guinea',
        'ERI'=>'Eritrea',
        'EST'=>'Estonia',
        'ETH'=>'Ethiopia',
        'FLK'=>'Falkland Islands',
        'FRO'=>'Faroe Islands',
        'FJI'=>'Fiji',
        'FIN'=>'Finland',
        'FRA'=>'France',
        'GUF'=>'French Guiana',
        'PYF'=>'French Polynesia',
        'ATF'=>'French Southern Territories',
        'GAB'=>'Gabon',
        'GMB'=>'Gambia',
        'GEO'=>'Georgia',
        'DEU'=>'Germany',
        'GHA'=>'Ghana',
        'GIB'=>'Gibraltar',
        'GRC'=>'Greece',
        'GRL'=>'Greenland',
        'GRD'=>'Grenada',
        'GLP'=>'Guadeloupe',
        'GUM'=>'Guam',
        'GTM'=>'Guatemala',
        'GGY'=>'Guernsey',
        'GIN'=>'Guinea',
        'GNB'=>'Guinea-Bissau',
        'GUY'=>'Guyana',
        'HTI'=>'Haiti',
        'HMD'=>'Heard Island and McDonald Islands',
        'HND'=>'Honduras',
        'HKG'=>'Hong Kong',
        'HUN'=>'Hungary',
        'ISL'=>'Iceland',
        'IND'=>'India',
        'IDN'=>'Indonesia',
        'IRN'=>'Iran',
        'IRQ'=>'Iraq',
        'IRL'=>'Ireland',
        'IMN'=>'Isle of Man',
        'ISR'=>'Israel',
        'ITA'=>'Italy',
        'CIV'=>'Ivory Coast',
        'JAM'=>'Jamaica',
        'JPN'=>'Japan',
        'JEY'=>'Jersey',
        'JOR'=>'Jordan',
        'KAZ'=>'Kazakhstan',
        'KEN'=>'Kenya',
        'KIR'=>'Kiribati',
        'XKX'=>'Kosovo',
        'KWT'=>'Kuwait',
        'KGZ'=>'Kyrgyzstan',
        'LAO'=>'Laos',
        'LVA'=>'Latvia',
        'LBN'=>'Lebanon',
        'LSO'=>'Lesotho',
        'LBR'=>'Liberia',
        'LBY'=>'Libya',
        'LIE'=>'Liechtenstein',
        'LTU'=>'Lithuania',
        'LUX'=>'Luxembourg',
        'MAC'=>'Macao',
        'MKD'=>'Macedonia',
        'MDG'=>'Madagascar',
        'MWI'=>'Malawi',
        'MYS'=>'Malaysia',
        'MDV'=>'Maldives',
        'MLI'=>'Mali',
        'MLT'=>'Malta',
        'MHL'=>'Marshall Islands',
        'MTQ'=>'Martinique',
        'MRT'=>'Mauritania',
        'MUS'=>'Mauritius',
        'MYT'=>'Mayotte',
        'MEX'=>'Mexico',
        'FSM'=>'Micronesia',
        'MDA'=>'Moldova',
        'MCO'=>'Monaco',
        'MNG'=>'Mongolia',
        'MNE'=>'Montenegro',
        'MSR'=>'Montserrat',
        'MAR'=>'Morocco',
        'MOZ'=>'Mozambique',
        'MMR'=>'Myanmar [Burma]',
        'NAM'=>'Namibia',
        'NRU'=>'Nauru',
        'NPL'=>'Nepal',
        'NLD'=>'Netherlands',
        'NCL'=>'New Caledonia',
        'NZL'=>'New Zealand',
        'NIC'=>'Nicaragua',
        'NER'=>'Niger',
        'NGA'=>'Nigeria',
        'NIU'=>'Niue',
        'NFK'=>'Norfolk Island',
        'PRK'=>'North Korea',
        'MNP'=>'Northern Mariana Islands',
        'NOR'=>'Norway',
        'OMN'=>'Oman',
        'PAK'=>'Pakistan',
        'PLW'=>'Palau',
        'PSE'=>'Palestine',
        'PAN'=>'Panama',
        'PNG'=>'Papua New Guinea',
        'PRY'=>'Paraguay',
        'PER'=>'Peru',
        'PHL'=>'Philippines',
        'PCN'=>'Pitcairn Islands',
        'POL'=>'Poland',
        'PRT'=>'Portugal',
        'PRI'=>'Puerto Rico',
        'QAT'=>'Qatar',
        'COG'=>'Republic of the Congo',
        'REU'=>'Réunion',
        'ROU'=>'Romania',
        'RUS'=>'Russia',
        'RWA'=>'Rwanda',
        'BLM'=>'Saint Barthélemy',
        'SHN'=>'Saint Helena',
        'KNA'=>'Saint Kitts and Nevis',
        'LCA'=>'Saint Lucia',
        'MAF'=>'Saint Martin',
        'SPM'=>'Saint Pierre and Miquelon',
        'VCT'=>'Saint Vincent and the Grenadines',
        'WSM'=>'Samoa',
        'SMR'=>'San Marino',
        'STP'=>'São Tomé and Príncipe',
        'SAU'=>'Saudi Arabia',
        'SEN'=>'Senegal',
        'SRB'=>'Serbia',
        'SYC'=>'Seychelles',
        'SLE'=>'Sierra Leone',
        'SGP'=>'Singapore',
        'SXM'=>'Sint Maarten',
        'SVK'=>'Slovakia',
        'SVN'=>'Slovenia',
        'SLB'=>'Solomon Islands',
        'SOM'=>'Somalia',
        'ZAF'=>'South Africa',
        'SGS'=>'South Georgia and the South Sandwich Islands',
        'KOR'=>'South Korea',
        'SSD'=>'South Sudan',
        'ESP'=>'Spain',
        'LKA'=>'Sri Lanka',
        'SDN'=>'Sudan',
        'SUR'=>'Suriname',
        'SJM'=>'Svalbard and Jan Mayen',
        'SWZ'=>'Swaziland',
        'SWE'=>'Sweden',
        'CHE'=>'Switzerland',
        'SYR'=>'Syria',
        'TWN'=>'Taiwan',
        'TJK'=>'Tajikistan',
        'TZA'=>'Tanzania',
        'THA'=>'Thailand',
        'TGO'=>'Togo',
        'TKL'=>'Tokelau',
        'TON'=>'Tonga',
        'TTO'=>'Trinidad and Tobago',
        'TUN'=>'Tunisia',
        'TUR'=>'Turkey',
        'TKM'=>'Turkmenistan',
        'TCA'=>'Turks and Caicos Islands',
        'TUV'=>'Tuvalu',
        'UMI'=>'U.S. Minor Outlying Islands',
        'VIR'=>'U.S. Virgin Islands',
        'UGA'=>'Uganda',
        'UKR'=>'Ukraine',
        'ARE'=>'United Arab Emirates',
        'GBR'=>'United Kingdom',
        'USA'=>'United States',
        'URY'=>'Uruguay',
        'UZB'=>'Uzbekistan',
        'VUT'=>'Vanuatu',
        'VAT'=>'Vatican City',
        'VEN'=>'Venezuela',
        'VNM'=>'Vietnam',
        'WLF'=>'Wallis and Futuna',
        'ESH'=>'Western Sahara',
        'YEM'=>'Yemen',
        'ZMB'=>'Zambia',
        'ZWE'=>'Zimbabwe'
    );
    public static $fold_position = array(
        "1" =>"Not available/ applicable",
        "2" =>"Completely Above the Fold",
        "3" =>"Completely Below the Fold",
        "4" =>"Partially Above the Fold"
    );

    public static $time_filter = array(
        "1" =>"A day ago",
        "2" =>"A week ago",
        "3" =>"A Month ago",
        "4" =>"All",
    );
}

?>