<div class="docs-header">
  <div class="topic">
        <div class="container">
          <h4>New Domain</h4>
        </div>
  </div>
</div>

<?php
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');


$this->headScript()->captureStart(); ?>
/*$(function(){
    $('#dpsd').datepicker().datepicker().on('show', popup);
    $('#dped').datepicker().datepicker().on('show', popup);
});*/


<?php $this->headScript()->captureEnd();  ?>
  

 <div class="container">
  <div class="row">
    <br />
    <div class="col-md-8 col-md-offset-2 panel panel-default">
      <div class="panel-body">
        <?php 
            if($error_message != "" && $error_message !== null && isset($error_message)):
              echo '<div id="cdn_form_success" class="alert alert-danger" style="margin: 15px;">'. $error_message .'</div>';
            endif;
        ?>
        <div id="cdn_form_msg" class="alert alert-danger" style="margin: 15px; display:none;"></div>
        <form id="domain" class="form-horizontal form-top-magin" name="domain" method="post" action="<?php echo $this->basePath() ?>/publisher/createdomain" novalidate="novalidate">
          <input type="hidden" value="" name="PublisherWebsiteID">
          <div class="form-group">
            <label for="webdomain" class="control-label col-sm-3">Web Domain <sup>(*)</sup></label>
            <div class="controls col-sm-7">
              <input type="text" value="" maxlength="255" class="form-control" id="WebDomain" name="WebDomain">    
            </div>
          </div>
          
          <div class="form-group">
            <label for="desc" class="control-label col-sm-3">Description<sup>(*)</sup></label>
            <div class="controls col-sm-7">
              <textarea maxlength="5000" class="form-control" id="Description" name="Description"></textarea>    
            </div>
          </div> 

          <div class="form-group">
            <label for="IABCategory" class="control-label col-sm-3">IABCategory</label>
            <div class="controls col-sm-7">
              <select class="form-control" id="IABCategory" name="IABCategory">
                <?php 
                   foreach($vertical_map as $key=>$value): 
                  echo '<option value="'. $key .'">'. $value .'</option>';
                 endforeach;
                 ?>
              </select>
            </div>
          </div>  
            <hr>
          <div class="form-group text-center">
            <div class="controls">
              <button name="submit" type="submit" class="btn btn-primary btn-margin" id="submitbutton">Create New Domain</button> &nbsp;
              <?php if (array_key_exists('HTTP_REFERER',$_SERVER)): ?>
                <a href="<?php echo $_SERVER['HTTP_REFERER']  ?>" class="btn btn-margin">Cancel</a>
              <?php else: ?>
                <a href="<?php echo $this->basePath() . '/publisher' ?>" class="btn btn-margin">Cancel</a>
              <?php endif; ?>
            </div>
          </div>
          <input type="hidden" value="<?php echo $domain_owner_id;?>" name="DomainOwnerID">
        </form>
      </div>
    </div>
  </div>
</div>