<div class="docs-header">
  <div class="topic">
        <div class="container">
          <h4>Edit Domain</h4>
        </div>
  </div>
</div>

<?php
$this->headScript()->appendFile($this->basePath() . '/js/script.js');

$this->headScript()->captureStart() ?>
<?php $this->headScript()->captureEnd();  ?>

<?php 
    if($error_message != "" && $error_message !== null && isset($error_message)):
      echo '<div id="cdn_form_success" class="alert alert-error" style="margin: 5px;">'. $error_message .'</div>';
    endif;

?>
<?php  /*if($is_admin) { ?>
    <div>
        <?php 
        // If Admin, show which account you are creating for.
            if($impersonate_id == "0" || $impersonate_id == null)
                echo "User: " . $true_user_name;
            else
                echo "User: " . $user_id_list[$impersonate_id];
        ?>
    </div>
    <?php }*/ ?>
 <div id="cdn_form_msg" class="alert alert-error" style="margin: 5px; display:none;"></div>
 <div class="container">
  <div class="row">
    <br />
    <div class="col-md-8 col-md-offset-2 panel panel-default">
        <div class="panel-body">
 
          <form id="domain" class="form-horizontal form-top-magin" name="domain" method="post" action="/publisher/editdomain/<?php echo $editResultObj->PublisherWebsiteID;?>/" novalidate="novalidate">
            
            <div class="form-group">
              <label for="webdomain" class="control-label col-sm-3">Web Domain</label>
              <div class="controls col-sm-7">
                <input type="text" value="<?php echo $editResultObj->WebDomain;?>" maxlength="255"  class="form-control"  id="WebDomain" name="WebDomain">    
              </div>
            </div>
            <div class="form-group">
                <label for="desc" class="control-label col-sm-3">Description</label>
                <div class="controls col-sm-7">
                  <textarea maxlength="5000"  class="form-control" id="Description" name="Description"><?php echo $editResultObj->Description;?></textarea>    
                </div>
            </div>     
            <div class="form-group">
              <label for="IABCategory" class="control-label col-sm-3">IABCategory</label>
              <div class="controls col-sm-7">
                <select class="form-control" id="IABCategory" name="IABCategory">
                  <?php 
                     foreach($vertical_map as $key=>$value):
                      $selected = '';
                      if($editResultObj->IABCategory == $key):
                        $selected = 'selected';
                      endif; 
                    echo '<option value="'. $key .'" '.$selected.'>'. $value .'</option>';
                   endforeach;
                  ?>
                </select>
              </div>
            </div>  
            
            <div class="form-group text-center">
              <div class="controls">
                <button name="submit" type="submit" class="btn btn-primary btn-margin" id="submitbutton">Update Domain</button>
              </div>
            </div>
            <input type="hidden" value="<?php echo $editResultObj->DomainOwnerID;?>" name="DomainOwnerID">
            <input type="hidden" value="<?php echo $editResultObj->PublisherWebsiteID;?>" name="PublisherWebsiteID">
          </form>
      </div>
    </div>
  </div>
</div>
