<?php
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/AppTable.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/qtip/jquery.qtip.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/static/css/qtip/jquery.qtip.min.css');

$this->headScript()->captureStart() ?>
function submitForm() {
  $('#loginas').submit();
}

$(document).ready(function () {

    $('span[title]').qtip();
    
});

<?php $this->headScript()->captureEnd();  
$effective_user_in_dashboard = false;
?>
<div class="docs-header">
  <div class="topic">
    <div class="row">
      <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-6"><h4>Domain List</h4></div>
      <div class="col-md-5 col-sm-5 text-right col-xs-6"><a href="<?php echo $this->basePath() ?>/publisher/createdomain" class="btn btn-success mrg5T">Create Domain</a></div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
      <div class="col-md-4 col-md-offset-8">
           <?php if ($is_admin === true): ?>
          
           <form name="loginas" id="loginas" action="<?php echo $this->basePath() ?>/publisher/loginas" class="form-inline" >
            <span style="font-size: 12px; font-weight: bold;">LOG IN AS USER</span>
            <select name="userid" onchange="submitForm();" class="form-control">
              <option value="0">Admin (<?php echo $true_user_name; ?>)</option>
              <?php foreach ($user_id_list as $user_info_id => $user_info_name): ?>
                <option <?php 
                if ($user_info_id == $effective_id): 
                  $effective_user_in_dashboard = true; 
                  echo 'selected="selected"'; 
                endif; ?> value="<?php echo $user_info_id;?>"><?php echo $user_info_name;?></option>
              <?php endforeach; ?>
            </select>
           </form>

       <?php endif; ?>
      </div>
  </div>
</div>




<div class="steps-container step1">

<div id="container">
<div class="row mrg20T">
<div class="col-md-10 col-md-offset-1 col-sm-12 panel">
<div class="pull-left" style="margin: 10px 0 0 10px;">
    <?php if ($effective_id != 0 && $effective_user_in_dashboard === true): ?>
        <div>
        <form name="changepublishermarkup" id="changepublishermarkup" action="<?php echo $this->basePath() ?>/publisher/changepublishermarkup"class="forms pull-right" >
          <input type="hidden" name="markuppublisherinfoid" value="<?php echo $publisher_info_id;?>" />
      
        <span style="font-size: 12px; font-weight: bold;">Publisher Markup Rate:</span>  <input type="text"  style="text-align: right" name="publisher-markup" class="span1" value="<?php echo $publisher_markup_rate;?>">%
          <div style="display: inline;">
            <input type="submit" name="publisher-markup-submit" class="btn actv  btn-small" value="Change Publisher Markup" style="width: 180px; margin-left: 8px; margin-bottom: 10px;" />
            <span style="cursor: pointer;" title="The Rate that the Impressions Will be Marked up from the Bid Price and Floor Prices (Your Profit)"><img style="border: 0; margin-bottom: 10px;" src="/images/tooltip.jpg" /></span>
          </div>
        
        </form>
        </div>
        <div style="position: relative;">
        <form name="changepublisherimpressionsnetworkloss" id="changepublisherimpressionsnetworkloss" action="<?php echo $this->basePath() ?>/publisher/changepublisherimpressionsnetworkloss"class="forms pull-right" >
          <input type="hidden" name="networkimpressionslosspublisherinfoid" value="<?php echo $publisher_info_id;?>" />
      
        <span style="font-size: 12px; font-weight: bold;">Publisher Impressions Network Loss Rate:</span>  <input type="text"  style="text-align: right" name="publisher-impressions-network-loss" class="span1" value="<?php echo $publisher_impressions_network_loss_rate;?>">%
          
          <div style="display: inline;">
            <input type="submit" name="publisher-impressions-network-loss-submit" class="btn actv  btn-small" value="Change Network Loss Rate" style="width: 180px; margin-left: 8px; margin-bottom: 10px;" />
            <span style="cursor: pointer;" title="Harmonizes lost impressions due to client network issues so SSPs numbers match the numbers in NginAd Reports"><img style="border: 0; margin-bottom: 10px;" src="/images/tooltip.jpg" /></span>
          </div>
        </form>
        </div>

    <?php endif; ?>
  </div>
    <div class="formbox">      
      <br clear="all"/>

    <div class="table-filter row">
      <div class="col-sm-4">
        Status:
        <select id="domain-status" onchange="DomainTable.reload_table()">
          <option value="">All</option>
          <option value="1">Auto-approved</option>
          <option value="2">Stop</option>
          <option value="3">Running</option>
        </select>
      </div>
      <div class="col-sm-8">
        IAB Category:
        <select id="domain-IABCategory" onchange="DomainTable.reload_table()">
          <option value="">All</option>
            <?php  foreach($vertical_map as $key=>$value): 
                echo '<option value="'. $key .'">'. $value .'</option>';
             endforeach; ?>
        </select>  
      </div>
      
      <!-- <div class="col-sm-4">
        Create Date:
        <select id="domain-createdate">
          <option value="">All</option>
          <option value="1">Today</option>
          <option value="2">Yesterday</option>
          <option value="3">Last week</option>
          <option value="4">This month</option>
          <option value="5">Last month</option>
          <option value="6">Custom</option>
        </select>    
      </div> -->
    </div>

    <div id="selection-results" class="steps-box">

        <table id="domain-table" class="table table-hover table-bordered table-margin" data-url="<?php echo $this->basePath() ?>/publisher/domainlist">
          <thead>
            <tr>
            <?php 
            foreach($domain_list['header'] as $order => $title):
              if ($title == "Domain Markup" || $title == "Imps Loss Rate"):
                echo "\n<th style=\"text-align:center; width: 110px\">" . $title . "</th>\n";
              else:
                echo "\n<th style=\"text-align:center;\">" . $title . "</th>\n";
              endif;
            endforeach;
            ?>
            </tr>
            </thead>
            
        </table>
    </div>
    </div>
    </div>
    </div>
</div>
