<?php
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/AppTable.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/qtip/jquery.qtip.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/static/css/qtip/jquery.qtip.min.css');

$this->headScript()->captureStart() ?>
function submitForm() {
  $('#loginas').submit();
}

$(document).ready(function () {

    $('span[title]').qtip();
    
});

<?php $this->headScript()->captureEnd();  
$effective_user_in_dashboard = false;
?>
<div class="docs-header">
  <div class="topic">
    <div class="row">
      <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-6"><h4>Report</h4></div>
      
    </div>
  </div>
</div>
<div class="steps-container step1 ">
  <div class="container-fluid">
    <div class="row mrg20T">
      <div id="revenue-overview" class="col-md-10 col-md-offset-1 panel pad20T">
        <p class="underline mrg0T" style="padding-bottom: 3px;">
          <span class="admin-titles">Overview </span>
            <select id="time-filter" onchange="ReportPublisherTable.reload_table()">
              <option selected value>All time</option>
              <option value="0">Today</option>
              <option value="1">Yesterday</option>
              <option value="2">This week</option>
              <option value="3">Last week</option>
              <option value="4">This month</option>
              <option value="5">Last month</option>
              <option value="6">This year</option>
        </select>
        </p>
        <div class="row">
          <div class="col-sm-3">Income (USD): $<strong id="Income">0</strong></div>
          <div class="col-sm-3">Click Total: <strong id="ClickTotal">0</strong> </div>
          <div class="col-sm-3">Impression Total: <strong id="ImpTotal">0</strong> </div>
        </div>
        <br>
      </div>

    </div>
  </div>
  <div class="container-fluid">
    <div class="row mrg20T">
      <div id="income-list" class="col-md-10 col-md-offset-1 panel pad20T">
        <p class="underline mrg0T" style="padding-bottom: 3px;">
          <span class="admin-titles">Income List </span>
        <table id="report-publisher-table" class="table table-hover table-striped table-bordered table-margin" data-url="<?php echo $this->basePath() ?>/publisher/reportlist">

          <thead>
            <tr >
              <?php 
              foreach($table_list as $order => $title):
                  echo "\n<th style=\"text-align:center;\">" . $title . "</th>\n";
              endforeach;
              ?>
            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row mrg20T">
      <div id="income-list" class="col-md-10 col-md-offset-1 panel pad20T">
        <p class="underline mrg0T" style="padding-bottom: 3px;">
          <span class="admin-titles">Withdrawal History </span>
          <span class="admin-titles pull-right"><button class="btn btn-success" style="margin: -12px 3px 0px 5px;" onclick="$('#PayoutModal').modal('show')">Withdraw</button></span>
          <span class="admin-titles pull-right">Balance: $<?php echo $user_balance;?></span>

        <table id="user-payout-table" class="table table-hover table-striped table-bordered table-margin" data-url="<?php echo $this->basePath() ?>/publisher/payoutlist">
          <thead>
            <tr >
              <th class="text-center">#</th>
              <th class="text-center">Date</th>
              <th class="text-center">Amount</th>
              <th class="text-center">Status</th>
            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>

</div>


<!-- User Payout Modal -->
<div class="modal fade" id="PayoutModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Withdraw</h4>
        <hr>
      </div>
      <div class="modal-body">
        <form id="domain" class="form-horizontal form-top-magin" name="domain" method="post" action="/bgate/publisher/payoutprocess" novalidate="novalidate">
          <input type="hidden" value="" name="UserPayoutID">
          <div class="form-group">
            <label for="Amount" class="control-label col-sm-3">Amount</label>
            <div class="controls col-sm-7">
              <input type="text" value="" maxlength="255" class="form-control" id="Amount" name="Amount">    
            </div>
          </div>
          <hr>
          <div class="form-group text-center">
            <div class="controls">
              <button name="submit" type="submit" class="btn btn-primary btn-margin" id="submitbutton">Submit</button> &nbsp;
              <a class="btn btn-margin" data-dismiss="modal">Cancel</a>
            </div>
          </div>
          </form>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>



