<div class="docs-header">
  <div class="topic">
        <div class="container">
          <h4>User Information</h4>
        </div>
  </div>
</div>

<?php
$this->headScript()->prependFile($this->basePath() . '/js/script.js');
?>

<div class="bs-docs-example">
      <?php 
      if(isset($success_msg) && $success_msg != null):
            echo '<div id="cdn_form_success" class="alert alert-success" style="margin: 5px;">Account updated successfully.</div>';
        endif;
        ?>

<div id="cdn_form_msg" class="alert alert-error" style="margin: 5px; display:none;"></div>
<div class="container">
  <div class="row">
    <br />
    <div class="col-md-8 col-md-offset-2 panel panel-default">
        <div class="panel-body">
      <form id="accountform" name="accountform" class="form-horizontal form-top-magin" method="POST" action="/users/account">
        <fieldset>
          <div class="form-group mrg20B mrg10T underline">
            <h4 class="mrg0A">Account Information</h4>    
          </div>

          <div class="form-group">
              <label for="Email" class="control-label col-sm-3">Email</label>
              <div class="controls col-sm-7">
              <input type="text" class="form-control" name="email" value="<?php echo $user_data->user_email;?>" readonly="readonly">
              </div>
          </div>

          <div class="form-group">
              <label for="name" class="control-label col-sm-3">Username</label>
              <div class="controls col-sm-7">
              <input id="name" type="text" class="form-control" name="name" value="<?php echo $user_data->user_fullname;?>" >
              </div>
          </div>

          <div class="form-group">
              <label for="name" class="control-label col-sm-3">Password</label>
              <div class="controls col-sm-7 mrg5T">
                <a class="" href="<?php echo $this->basePath() ?>/users/changepassword">Change your password</a>
              </div>
          </div>
          <div class="form-group mrg20B underline">
              <h4 class="mrg0A">Contact Information</h4>    
            </div>
            <div class="form-group">
                <label for="FirstName" class="control-label col-sm-3">First Name</label>
                <div class="controls col-sm-7">
                <input type="text" value="" class="form-control" maxlength="100" name="FirstName" id="FirstName">    </div>
            </div>
            <div class="form-group">
                <label for="LastName" class="control-label col-sm-3">Last Name</label>
                <div class="controls col-sm-7">
                <input type="text" value="" class="form-control" maxlength="100" name="LastName" id="LastName">    </div>
            </div>
            <div class="form-group">
                <label for="Country" class="control-label col-sm-3">Country</label>
                <div class="controls col-sm-7">
                <input type="text" value="" class="form-control"name="Country" id="Country">    
                </div>
            </div>
            <div class="form-group">
                <label for="City" class="control-label col-sm-3">City</label>
                <div class="controls col-sm-7">
                <input type="text" value="" class="form-control" maxlength="100" name="City" id="City">    </div>
            </div>
            <div class="form-group">
                <label for="Addr" class="control-label col-sm-3">Address</label>
                <div class="controls col-sm-7">
                <input type="text" value="" class="form-control" maxlength="255" name="Addr" id="Addr">    </div>
            </div>
            <div class="form-group mrg20B underline">
              <h4 class="mrg0A">Site Information</h4>    
            </div>

            <div class="form-group">
                <label for="Name" class="control-label col-sm-3">Publisher Name</label>
                <div class="controls col-sm-7">
                <input type="text" value="" class="form-control" maxlength="100" name="Name" id="Name" placeholder="Name">    </div>
            </div>
            <div class="form-group">
                <label for="Domain" class="control-label col-sm-3">Website</label>
                <div class="controls col-sm-7">
                <input type="text" value="" class="form-control" maxlength="50" name="Domain" id="Domain" placeholder="example.com">    </div>
            </div>
            <div class="form-group">
                <label for="Domain" class="control-label col-sm-3">Website Describe</label>
                <div class="controls col-sm-7">
                  <textarea  rows="4" class="form-control" name="DomainDescribe" id="DomainDescribe"></textarea>
                </div>
            </div>
            <div class="form-group">
                <label for="IABCategory" class="control-label col-sm-3">IABCategory</label>
                <div class="controls col-sm-7">
                <select id="IABCategory" class="form-control" name="IABCategory">
                   <?php 
                   foreach($vertical_map as $key=>$value): 
                  echo '<option value="'. $key .'">'. $value .'</option>';
                 endforeach;
                 ?>
              </select>
              </div>

            </div> 
          <hr>
          <div class="form-group text-center">
             <input type="submit" class="btn btn-primary" name="update" value="Update account" />
          </div>
        </fieldset>
        <input type="hidden" name="user_id" value="<?php echo $user_data->user_id;?>">
        </form>        
         
     </div>
     </div>
     </div>
     </div>
     </div>

