<div class="docs-header">
  <div class="topic">
        <div class="container">
          <h4>Change Password</h4>
        </div>
  </div>
</div>

<?php
$this->headScript()->prependFile($this->basePath() . '/js/script.js');
?>
<div class="bs-docs-example">
            <!-- <ul class="nav nav-tabs" id="myTab">
              <li><a  href="/users/account">Profile</a></li>
              <li class="active"><a data-toggle="tab" href="#change_password">Change Password</a></li>
              <li><a href="/users/websites">Websites</a></li>
            </ul> -->
            <div class="tab-content" id="myTabContent">
              <div id="change_password" class="tab-pane fade active in">
               <?php 
                if(isset($error_msg) && $error_msg != null):
            echo '<div id="cdn_form_error" class="alert alert-error" style="margin: 5px;">'.$error_msg.'</div>';
          endif;
          if(isset($success_msg1) && $success_msg1 != null):
              echo '<div id="cdn_form_success1" class="alert alert-success" style="margin: 5px;">Password updated successfully.</div>';
          endif;
         ?>
               <div id="cdn_change_pass" class="alert alert-error" style="margin: 5px; display:none;"></div>
 <div class="container">
  <div class="row">
    <br />
    <div class="col-md-8 col-md-offset-2 panel panel-default">
        <div class="panel-body">
               <form id="changepassform" name="changepassform" class="form-horizontal form-top-magin" method="POST" action="/users/changepassword">
        <fieldset>
        <div class="form-group">
          <label class="control-label col-sm-3" for="password">Old Password: </label>
          <div class="controls col-sm-7"><input type="password" class="input-medium form-control" name="old_password" id="old_password" class="input-mini"></div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-3" for="password">New Password: </label>
          <div class="controls col-sm-7"><input type="password" class="input-medium form-control" name="password" id="password"></div>
        </div>
        <div class="form-group">
          <label class="control-label col-sm-3" for="confirm_password">Confirm password:</label>
          <div class="controls col-sm-7"><input type="password" name="confirm_password" class="input-medium form-control" id="confirm_password"></div>
        </div>
         <div class="form-group text-center">
          <input type="submit" class="btn btn-primary" name="update" value="Change Password" />
        </div>
        </fieldset>
        <input type="hidden" name="user_id" value="<?php echo $user_data->user_id;?>">
      </form>
              </div>
            </div>
          </div>
          </div>
          </div>
          </div>
          </div>
