<?php
$this->headScript()->prependFile($this->basePath() . '/static/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/AppTable.js');
?>
<div class="docs-header">
  <div class="topic">
    <div class="container-fluid">
       <div class="row">
        <div class="col-xs-10 col-xs-offset-1">
          <div ><h4>Advertiser List</h4></div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid mrg20T">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <div class="panel">
        <div class="panel-body">
          <div class="table-filter row">
          </div>
            <!-- <div class="steps-container step1"> -->
                <!-- <div id="selection-results" class="steps-box"> -->
               <!-- <div class="formbox">   -->
                <table class="table table-striped table-bordered table-margin" id="advertiser-table" data-url="<?php echo $this->basePath() ?>/users/customerslist">
                  <thead>
                      <tr>
                     <th>
          				     ID
                     </th>
                     <th>
                          Customer Name
                     </th>
                     <th>
                          Customer Username
                     </th>
                     <th>
                      	Email	
                     </th>
                     <th>
                      	Total Charge	
                     </th>
                      <th>
                      	Total Spend
                     </th>
                      <th>
                        Bgate Revenue
                     </th>
                     <th>
                     	    Approval
                     </th>
                     </tr>
                  </thead>
          	  
                </table>
        </div>
      </div>
    </div>
  </div>
</div>


<div style="clear:both"></div>

<input  type="hidden" name="user_type" id="user_type" value="<?php echo $user_type;?>" />
<!-- Publisher Accept Modal -->
<div class="modal fade" id="UserAcceptModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Customer Accept.</h4>
      </div>
      <div class="modal-body">
      <div id="user_accept_alert_msg" class="alert alert-success" style="display: none;">Error</div>
		<div class="control-group">
		    <label for="desc" class="control-label" id="msg"></label>
	    </div>
      </div>
      <div class="modal-footer">
      <button type="button" data-loading-text="Processing..." id="user_accept_yes_btn" class="btn btn-primary" onclick="userAcceptConfirm();">Approve</button>
        <button type="button" class="btn btn-default" id="user_accept_no_btn" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- Publisher Accept Modal -->


<!-- Publisher Rejection Modal -->
<input type="hidden" name="modal_user_id" id="modal_user_id" value="0" />
<div class="modal fade" id="UserRejectionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Customer Rejection</h4>
      </div>
      <div class="modal-body">
      <div id="user_rejection_alert_msg" class="alert alert-success" style="display: none;">Error</div>
		<div class="control-group">
		    <label for="desc" class="control-label" id="msg"></label>
	    </div>
		<div class="control-group">
		    <label for="desc" class="control-label">Reason for Rejection:</label>
		    <div class="controls">
		    <textarea  id="description" name="description" style="width: 500px;height:130px;"></textarea>    </div>
	    </div>
	<!--<h5 style="color: #b94a48;">This action is IMMEDIATE and NOT REVERSABLE!</h5>-->
      </div>
      <div class="modal-footer">
      <button type="button" data-loading-text="Processing..." id="user_rejection_yes_btn" class="btn btn-primary" onclick="userRejectionConfirm();">Yes</button>
        <button type="button" class="btn btn-default" id="user_rejection_no_btn" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>
<!-- Publisher Rejection Modal -->

<!-- Customer Ban Modal -->
<input type="hidden" name="ban_user_id" id="ban_user_id" value="0" />
<div class="modal fade" id="UserBanModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Customer Ban</h4>
      </div>
      <div class="modal-body">
      <div id="user_ban_alert_msg" class="alert alert-success" style="display: none;">Error</div>
    <div class="control-group">
        <label for="desc" class="control-label" id="msg"></label>
      </div>
    <div class="control-group">
        <label for="desc" class="control-label">Reason for Ban:</label>
        <div class="controls">
        <textarea  id="description" name="description" style="width: 500px;height:130px;"></textarea>    </div>
      </div>
  <!--<h5 style="color: #b94a48;">This action is IMMEDIATE and NOT REVERSABLE!</h5>-->
      </div>
      <div class="modal-footer">
      <button type="button" data-loading-text="Processing..." id="user_ban_yes_btn" class="btn btn-primary" onclick="userBanConfirm();">Yes</button>
        <button type="button" class="btn btn-default" id="user_ban_no_btn" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>
<!-- Customer Rejection Modal -->