<div class="docs-header">
  <div class="topic">
        <div class="container">
          <h4>Profile Information</h4>
        </div>
  </div>
</div>

<?php
$this->headScript()->prependFile($this->basePath() . '/js/script.js');
?>

<div class="bs-docs-example">
      <?php 
      if(isset($success_msg) && $success_msg != null):
            echo '<div id="cdn_form_success" class="alert alert-success" style="margin: 5px;">Profile updated successfully.</div>';
        endif;
        ?>

<div id="cdn_form_msg" class="alert alert-error" style="margin: 5px; display:none;"></div>
<div class="container">
  <div class="row">
    <br />
    <div class="col-md-8 col-md-offset-2 panel panel-default">
        <div class="panel-body">
      <form id="accountform" name="accountform" class="form-horizontal form-top-magin" method="POST" action="<?php echo $this->basePath();?>/users/profile">
        <fieldset>
          <div class="form-group mrg20B mrg10T underline">
            <h4 class="mrg0A">Account Information</h4>    
          </div>

          <div class="form-group">
              <label for="Email" class="control-label col-sm-3">Email</label>
              <div class="controls col-sm-7">
              <input type="text" class="form-control" name="email" value="<?php echo $demand_customer_info->Email;?>" readonly="readonly">
              </div>
          </div>

          <div class="form-group">
              <label for="name" class="control-label col-sm-3">Username</label>
              <div class="controls col-sm-7">
              <input id="name" type="text" class="form-control" name="name" value="<?php echo $demand_customer_info->Name;?>" >
              </div>
          </div>
          <div class="form-group">
              <label for="user_fullname" class="control-label col-sm-3">Full Name</label>
              <div class="controls col-sm-7">
              <input id="user_fullname" type="text" class="form-control" name="user_fullname" value="<?php echo $user_data->user_fullname;?>" >
              </div>
          </div>
          <div class="form-group">
              <label for="name" class="control-label col-sm-3">Password</label>
              <div class="controls col-sm-7 mrg5T">
                <a class="" href="<?php echo $this->basePath() ?>/users/changepassword">Change your password</a>
              </div>
          </div>
          <div class="form-group mrg20B underline">
              <h4 class="mrg0A">Invoice Information</h4>    
            </div>
            <div class="form-group">
                <label for="Company" class="control-label col-sm-3">Company Name</label>
                <div class="controls col-sm-7">
                <input type="text"  class="form-control" name="company" id="Company" value="<?php echo $demand_customer_info->Company ?>">    
                </div>
            </div>
            <div class="form-group">
                <label for="ContactNo" class="control-label col-sm-3">Contact No</label>
                <div class="controls col-sm-7">
                <input type="text" value="<?php echo $demand_customer_info->ContactNo ?>" class="form-control" maxlength="100" name="contactNo" id="ContactNo">    
                </div>
            </div>
            <div class="form-group">
                <label for="Debuty" class="control-label col-sm-3">Debuty</label>
                <div class="controls col-sm-7">
                <input type="text" value="<?php echo $demand_customer_info->Debuty ?>" class="form-control"name="debuty" id="Debuty">    
                </div>
            </div>
            <div class="form-group">
                <label for="Title" class="control-label col-sm-3">Title</label>
                <div class="controls col-sm-7">
                <input type="text" value="<?php echo $demand_customer_info->Title ?>" class="form-control" maxlength="100" name="title" id="Title"> </div>
            </div>
            <div class="form-group">
                <label for="Address" class="control-label col-sm-3">Address</label>
                <div class="controls col-sm-7">
                <input type="text" value="<?php echo $demand_customer_info->Address ?>" class="form-control" maxlength="255" name="address" id="Address">    
                </div>
            </div>
            <div class="form-group">
                <label for="Name" class="control-label col-sm-3">Tax No</label>
                <div class="controls col-sm-7">
                <input type="text" value="<?php echo $demand_customer_info->Tax ?>" class="form-control" maxlength="100" name="tax" id="Tax" placeholder="Name">    
                </div>
            </div>
            <div class="form-group">
                <label for="Phone" class="control-label col-sm-3">Phone number</label>
                <div class="controls col-sm-7">
                <input type="text" value="<?php echo $demand_customer_info->Phone ?>" class="form-control" maxlength="50" name="phone" id="Phone" placeholder="example.com">    
                </div>
            </div>

            <div class="form-group">
                <label for="locale" class="control-label col-sm-3">Language</label>
                <div class="controls col-sm-7">
                <select id="locale" class="form-control" name="locale" id="locale">
                      <option <?php if($locale == "vi_VN") echo "selected" ?> value="vi_VN">Vietnamese</option>
                      <option <?php if($locale == "en_US") echo "selected" ?> value="en_US">English</option>
                </select> 

                </div>
            </div>
            
          <hr>
          <div class="form-group text-center">
             <input type="submit" class="btn btn-primary" name="update" value="Update account" />
          </div>
        </fieldset>
        <input type="hidden" name="user_id" value="<?php echo $user_data->user_id;?>">
        </form>        
         
     </div>
     </div>
     </div>
     </div>
     </div>

