<?php
$this->headScript()->prependFile($this->basePath() . '/static/js/script.js');
?>

 <?php
              if (isset($_SESSION['user']['message'])):
                 echo '<div id="cdn_form_msg" class="alert alert-danger" style="margin: 5px;">'.$_SESSION['user']['message'].'</div>';
                 unset($_SESSION['user']['message']);
              endif;
              if(isset($success_msg) && $success_msg != null):
                
                  echo '<div id="cdn_form_success" class="alert alert-success" style="margin: 5px;">Account created successfully. You will receive a welcome email when your account is approved by our Ad Operations Team</div>';
                endif;
              ?>  
<div class="container">
  
  <div class="row">
    <br />
    <div class="col-md-6 col-md-offset-3">
      <div class="panel panel-warning">
        <div id="legend" class="panel-heading text-center">
          <h3 class="loginhead mrg0A">Forgot your password?</h3>
        </div> 
        <div class="panel-body">
          <form class="" method="POST" action="<?php echo $this->basePath() ?>/auth/recover" name="revocerform" id="revocerform" >
            <fieldset>
              


              <div class="form-group form-group-lg">
                <!-- Username -->
                <label class="control-label"  for="username">Email Address</label>
                <div class="controls">
                  <input type="text" id="username" name="username" placeholder="" class="form-control">
                </div>
              </div>
                           

              <div class="form-group">
              <!-- Button -->
                <div class="form-group text-center">
                   <input type="submit" class="btn btn-success btn-lg" value="Send password" name="B1">
                </div>
              </div>

            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
  <div class="row text-center">
    Trying to <a href="<?php echo $this->basePath() ?>/auth/login">sign in ?</a>
    <br>
    Don't have an account? 
    <a href="<?php echo $this->basePath() ?>/signup">Publisher Register</a> or
    <a href="<?php echo $this->basePath() ?>/signup/advertiser">Advertiser Register</a>
    <br><br>
  </div>
</div>




