<?php
$this->headScript()->prependFile($this->basePath() . '/static/js/script.js');
?>

<div class="docs-header">
  <div class="topic container-fluid">
    <div class="row">
      <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-6"><h4>Websites List</h4></div>
    </div>
  </div>
</div>

<div class="steps-container step1">
  <div class="container-fluid">
  <div class="row mrg20T">
    <div class="col-md-10 col-md-offset-1 col-sm-12 panel">
        <div class="formbox">      
          <br clear="all"/>
            <table class="table table-hover table-striped table-bordered table-margin">
                <tr>
               <th>
    				      #
               </th>
               <th>
                  Website
               </th>
               <th>
                	IAB Category	
               </th>
                <th>
                	Date Created
               </th>
               <th style="width: 13%;">
               	    Status
               </th>
               </tr>

        	   <?php 
        	   $i=1;
        	   foreach ($pending_list as $website):
        	   		$userData = $PublisherInfoFactory->get_row(array("PublisherInfoID" => $website->DomainOwnerID));
        	   ?>   
               <tr id="sites_row_<?php echo $website->PublisherWebsiteID;?>">
               <td>
                <?php echo $i; ?>
               </td>
               <td id="wb_site_<?php echo $website->PublisherWebsiteID;?>">
                <?php echo $website->WebDomain; ?>
                </td>
               <td>
                <?php echo $vertical_map[$website->IABCategory]; ?>
               </td>
               <td>
                <?php echo $website->DateCreated; ?>
               </td>
               <td>
               <?php if($website->ApprovalFlag == 0): 
               			echo '<span class="label label-info">Waiting for Approval</span>';
               		 elseif($website->ApprovalFlag == 1):
               		 	echo '<span class="label label-success">Approved</span>';
               		 else:
               		 	echo '<span class="label label-important">Denied</span>';	
                     endif;
               ?>
               </td>
               </tr>
          <?php 
          	 $i++;
          	endforeach;
          ?>
          </table>
        </div>
    </div>
  </div>
  </div>
</div>