<?php
$this->headScript()->prependFile($this->basePath() . '/static/js/script.js');
$this->headScript()->prependFile($this->basePath() . '/static/js/signup.js');
?>


<div class="docs-header">
	<div class="topic">
        <div class="container">
			<div class="col-md-8">
			  <h3>Create Demand Customer Account.</h3>
			</div>
			<div class="col-md-4">
			
          </div>
        </div>
        <div class="topic__infos">
          <div class="container">
          		<a href="<?php echo $this->basePath() ?>/signup">Publishers Sign-up Here</a>
          </div>
        </div>
      </div>
</div>

<div class="container">
	<div class="row">
		<br />
		<div class="col-md-6 col-md-offset-3">
				<form id="customersignupform" name="customersignupform" class="form-horizontal form-top-magin" method="post" action="<?php echo $this->basePath() ?>/signup/customer">
					<?php 
					    if(isset($error_msg) && $error_msg != null):
					    
						    echo '<div id="cdn_form_error" class="alert alert-error" style="margin: 5px;">'.$error_msg.'</div>';
					    endif;
					    if(isset($success_msg) && $success_msg != null):
					    
						    echo '<div id="cdn_form_success" class="alert alert-success" style="margin: 5px;">Account created successfully. You will receive a welcome email when your account is approved by our Ad Operations Team</div>';
					    endif;
					?>
					<div id="cdn_form_dynamic_msg" class="alert alert-error" style="margin: 5px; display:none;"></div>
					<div id="cdn_form_msg" class="alert alert-error" style="margin: 5px; display:none;"></div>

					<div class="form-group form-group-lg">
					    <label for="Customer Name" class="control-label">Customer Name</label>
					    <div class="controls">
					    <input type="text" value="" class="form-control" maxlength="100" name="customer_name" id="customer_name" placeholder="Name">    </div>
					</div>
					<div class="form-group form-group-lg">
					    <label for="Email" class="control-label">Email</label>
					    <div class="controls">
					    <input type="text" value="" class="form-control" maxlength="50" name="email" id="email" placeholder="me@example.com">
					    </div>
					</div>
					<div class="form-group form-group-lg">
					    <label for="Company" class="control-label">Company</label>
					    <div class="controls">
					    <input type="text" value="" class="form-control" maxlength="50" name="company" id="company" placeholder="Company">    </div>
					</div>
					<div class="form-group form-group-lg">
					    <label for="Website" class="control-label">Website Domain</label>
					    <div class="controls">
					    <input type="text" value="" class="form-control" maxlength="50" name="website" id="website" placeholder="example.com">    </div>
					</div>
					<div class="form-group form-group-lg">
					    <label for="Partner Type" class="control-label">Partner Type</label>
					    <div class="controls">
					    <select id="partner_type" class="form-control" name="partner_type">
					     <?php 
					     foreach($partner_type as $key=>$value): 
						 	echo '<option value="'. $key .'">'. $value .'</option>';
						 endforeach;
						 ?>
						</select>
						</div>
					    </div> 
					<div class="form-group form-group-lg">
					    <label for="Username" class="control-label">Username</label>
					    <div class="controls">
					    	<input type="text" value="" class="form-control" maxlength="50" name="user_login" id="user_login" placeholder="username">
					    </div>
					</div>
				    
				    <div class="form-group form-group-lg">
					    <label for="Password" class="control-label">Password</label>
					    <div class="controls">
					    <input type="password" value="" class="form-control" name="password" id="password">    </div>
					</div> 
					
					<div class="form-group form-group-lg">
					    <label for="Confirm Password" class="control-label">Confirm Password</label>
					    <div class="controls">
					    <input type="Password" value="" class="form-control"  name="confirm_password" id="confirm_password">    </div>
					</div> 
					
						<div class="text-center">
					    	<button name="b1" type="button" class="btn btn-success btn-lg btn-margin customersignupform" id="submitbutton" >Create Account</button>
					    </div>
				</form>

		</div>
	</div>
</div>

<br />
