<?php
$this->headScript()->appendFile($this->basePath() . '/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/js/qtip/jquery.qtip.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/css/qtip/jquery.qtip.min.css');

$this->headScript()->captureStart() ?>
function submitForm() {
	$('#loginas').submit();
}

$(document).ready(function () {

    $('span[title]').qtip();
    
});

<?php $this->headScript()->captureEnd();  
$effective_user_in_dashboard = false;
?>

<div class="container-fluid main-board">
  <div class="row">
      <div class="col-md-4 col-md-offset-8">
           <?php if ($is_admin === true): ?>
          
           <form name="loginas" id="loginas" action="<?php echo $this->basePath() ?>/demand/loginas" class="form-inline" >
            <span style="font-size: 12px; font-weight: bold;">LOG IN AS USER</span>
            <select name="userid" onchange="submitForm();" class="form-control">
              <option value="0">Admin (<?php echo $true_user_name; ?>)</option>
              <?php foreach ($user_id_list as $user_info_id => $user_info_name): ?>
                <option <?php 
                if ($user_info_id == $effective_id): 
                  $effective_user_in_dashboard = true; 
                  echo 'selected="selected"'; 
                endif; ?> value="<?php echo $user_info_id;?>"><?php echo $user_info_name;?></option>
              <?php endforeach; ?>
            </select>
           </form>
           <?php endif; ?>
      </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      
      <div class="pull-left" style="margin: 10px 0 0 10px;">
      <?php if ($effective_id != 0 && $effective_user_in_dashboard === true): ?>

                <form name="changeusermarkup" id="changeusermarkup" action="<?php echo $this->basePath() ?>/demand/changeusermarkup"class="form-inline" >
                  <input type="hidden" name="markupuserid" value="<?php echo $effective_id;?>" />
              
                <span style="font-size: 12px; font-weight: bold;">User Markup Rate:</span>
                <input type="text"  style="text-align: right; width: 50px" name="user-markup" class="form-control" value="<?php echo $user_markup_rate;?>">%
                  <div style="display: inline;">
                    <input type="submit" name="user-markup-submit" class="btn actv  btn-small" value="Change User Markup" style="margin-left: 8px; margin-bottom: 10px;" title="The Rate that the Impressions Will be Marked up from the Bid Price (Your Profit)" />
                  </div>
                </form>

            <?php endif; ?>
       
        </div>

    </div>
  </div>

  <div class="row">
    <div class="col-md-12" style=" overflow: auto;">
      
      <table class="table table-striped table-bordered">
         <tr>
      <?php if ($is_admin === true): ?>
             <th>
              USER ID
             </th>
             <th>
              ADMIN ACTION
             </th>
    <?php endif; ?>
    <?php if ($is_admin === true && $effective_id != 0): ?>
             <th>
              CAMPAIGN MARKUP
             </th>
    <?php endif; ?>
             <th>
              STATUS
             </th>
             <th>
              A_ID
             </th>
             <th>
              Name
             </th>
             <th>
              StartDate/EndDate
             </th>
             <!--
             <th>
              Customer
             </th>
             <th>
              CustomerID
             </th>
              -->
             <th>
              ImpressionsCounter
             </th>
             <th>
              MaxImpressions
             </th>
             <th>
              CurrentSpend
             </th>
             <th>
              MaxSpend
             </th>
             <!--
             <th>
              Date Created
             </th>
             -->
            <?php if (($is_admin === true && $effective_id != 0) || $is_admin === false): ?>
             <th>
              Modify Campaign
             </th>
             <th>
              Modify Banner
             </th>
             <?php endif; ?>
             </tr>

      <?php foreach ($ad_campaigns as $ad_campaign) :
          $preview_query = isset($ad_campaign->AdCampaignPreviewID) ? "?ispreview=true" : "";
          if (isset($ad_campaign->AdCampaignPreviewID)):
            $campaign_id = $ad_campaign->AdCampaignPreviewID;
          else:
            $campaign_id = $ad_campaign->AdCampaignID;
          endif;
      ?>
              <tr>
      <?php if ($is_admin === true): ?>
             <td>
                <?php if (isset($user_id_list[$ad_campaign->UserID])): ?>
            <?php echo $user_id_list[$ad_campaign->UserID]; ?>
                <?php else: ?>
            User Unknown
                <?php endif; ?>
             </td>
             <?php if (isset($ad_campaign->AdCampaignPreviewID)): ?>
             <td>
                <a href="<?php echo $this->basePath() ?>/demand/approvecampaign/<?php echo $ad_campaign->AdCampaignPreviewID;?>" onclick="return confirm('Are you sure?');">APPROVE CAMPAIGN CHANGES</a>
                <hr /><a href="<?php echo $this->basePath() ?>/demand/rejectcampaign/<?php echo $ad_campaign->AdCampaignPreviewID; ?>" onclick="return confirm('Are you sure?');">REJECT CAMPAIGN CHANGES</a>
             </td>
             <?php else: ?>
             <td>
                N/A
             </td>
             <?php endif; ?>

    <?php if ($is_admin === true && $effective_id != 0): ?>
             <td>
                <?php if (isset($ad_campaign->AdCampaignID) && $ad_campaign->AdCampaignID != null && isset($campaign_markup_rate_list[$ad_campaign->AdCampaignID])): ?>
            <form name="change-campaign-markup-<?php echo $ad_campaign->AdCampaignID;?>" class="change-campaign-markup form-inline" action="<?php echo $this->basePath() ?>/demand/changecampaignmarkup">
              <input type="hidden" name="markupcampaignid" value="<?php echo $ad_campaign->AdCampaignID;?>" />
              <div class="form-group">
                <input type="text" style="text-align: right; width: 50px" name="campaign-markup" class="form-control" value="<?php echo $campaign_markup_rate_list[$ad_campaign->AdCampaignID];?>">%
                <input type="submit" name="campaign-markup-submit" class="btn btn-warning btn-mini" value="Update Markup" style="" />
              </div>
              <div>
                
              </div>
            </form>
          <?php else: ?>
            NOT AVAILABLE
          <?php endif; ?>
             </td>
    <?php endif; ?>


    <?php endif; ?>
             <td>
              <?php if (!isset($ad_campaign->AdCampaignPreviewID)): ?>
                <?php echo '<span class="label label-success">APROVED</span>'; ?>
              <?php elseif (isset($ad_campaign->Deleted) && $ad_campaign->Deleted == 1): ?>
                <?php echo '<span class="label label-error">DELETED</span>'; ?>
                <?php if ($is_admin === false): ?>
                  <hr /><a href="<?php echo $this->basePath() ?>/demand/cancelcampaign/<?php echo $ad_campaign->AdCampaignPreviewID; ?>" onclick="return confirm('Are you sure?');">CANCEL CAMPAIGN CHANGES</a>
                <?php endif; ?>
              <?php else: ?>
                <?php echo '<span style="color:brown; font-weight: bold;">PENDING APPROVAL</span>'; ?>
                <?php if ($is_admin === false): ?>
                  <hr /><a href="<?php echo $this->basePath() ?>/demand/cancelcampaign/<?php echo $ad_campaign->AdCampaignPreviewID; ?>" onclick="return confirm('Are you sure?');">CANCEL CAMPAIGN CHANGES</a>
                <?php endif; ?>
              <?php endif; ?>
             </td>
             <td>
              <?php
              if (isset($ad_campaign->AdCampaignID)):
                echo '<span style="color:black;">' . $ad_campaign->AdCampaignID . '</span>';
              elseif (isset($ad_campaign->Deleted) && $ad_campaign->Deleted == 1):
                echo '<span style="color:red; font-weight: bold;">DELETED</span>';
              else:
                echo '<span style="color:black; font-weight: bold;">PENDING ASSIGNMENT</span>';
              endif;
              ?>
             </td>
             <td>
              <?php echo $ad_campaign->Name; ?>
             </td>
             <td>
              <?php echo $ad_campaign->StartDate; ?><hr /><?php echo $ad_campaign->EndDate; ?>
             </td>
             <td>
              <?php if (!isset($ad_campaign->AdCampaignPreviewID)): ?>
                <?php echo number_format($ad_campaign->ImpressionsCounter); ?>
              <?php else: ?>
          N/A in Edit Mode
              <?php endif; ?>
             </td>
             <td>
             <?php echo number_format($ad_campaign->MaxImpressions); ?>
             </td>
             <td>
              <?php if (!isset($ad_campaign->AdCampaignPreviewID)): ?>
                $<?php echo number_format($ad_campaign->CurrentSpend, 4, '.', ','); ?>
              <?php else: ?>
          N/A in Edit Mode
              <?php endif; ?>

             </td>
             <td>
             $<?php echo number_format($ad_campaign->MaxSpend, 2, '.', ','); ?>
             </td>
              <?php if (($is_admin === true && $effective_id != 0) || $is_admin === false): ?>
             <td>
              <a href="<?php echo $this->basePath() ?>/demand/editcampaign/<?php echo $campaign_id; ?><?php echo $preview_query; ?>">Edit Ad Campaign</a>
              <hr />
             
              <a href="javascript:void(0);" onclick="deleteCampaignModal('/demand/deletecampaign/<?php echo $campaign_id; ?><?php echo $preview_query;?>','<?php echo $ad_campaign->Name;?>');">Delete Ad Campaign</a>
             </td>
             <td>
              <a href="<?php echo $this->basePath() ?>/demand/createbanner/<?php echo $campaign_id; ?><?php echo $preview_query;?>">Create Banner</a>
              <hr /><a href="<?php echo $this->basePath() ?>/demand/viewbanner/<?php echo $campaign_id; ?><?php echo $preview_query;?>">View Banners</a>
             </td>
             <?php endif; ?>
             </tr>
      <?php endforeach; ?>
      </table>

    </div>
  </div>


</div>


<div style="clear:both"></div>
<!-- Campaign Delete Modal -->
<input  type="hidden" name="modal_campaign_id" id="modal_campaign_id" value="0" />
<div class="modal fade" id="DeleteCampaignModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel">Delete Campaign</h4>
      </div>
      <div class="modal-body">
      <div id="campaign_alert_msg" class="alert alert-error" style="display: none;">Error</div>
		<p id="msg"></p>
<h5 style="color: #b94a48;">This action is a preview and must be approved!</h5>
      </div>
      <div class="modal-footer">
      <button type="button" data-loading-text="Processing..." id="campaign_yes_btn" class="btn btn-primary" onclick="deleteCampaignConfirm();">Yes</button>
        <button type="button" class="btn btn-default" id="campaign_no_btn" data-dismiss="modal">No</button>
      </div>
    </div>
  </div>
</div>
<!-- Campaign Delete Modal -->