
<div class="docs-header">
  <div class="topic container-fluid">
    <div class="row">
      <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-12"><h4><?php echo $this->layout()->_t->translate("Admin's Dashboard");?></h4></div>
      <div class="col-md-5 col-sm-5 text-right col-xs-12"></div>
    </div>
  </div>
</div>

<div class="container-fluid">

<div class="row mrg20T">
  <div class="col-xs-10 col-xs-offset-1">
    <div class="panel">
      <div class="panel-body">
        <div class="col-xs-4">
          <strong><i class='glyphicon glyphicon-user'></i> MEMBERS </strong>
        </div>
        <div class="col-xs-4">
          <strong>Publishers: </strong><?php echo $publishers_number;?>
        </div>
        <div class="col-xs-4">
          <strong>Advertisers: </strong><?php echo $advertisers_number;?>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <div class="panel">
      <div class="panel-body">
        
        <div class="row mrg10T">
          
          <div class="col-sm-4 mrg10B">
            <div class="box no-border bg-custom-success tiles-information">
              <i class="glyphicon glyphicon-globe icon-bg"></i>
              <div class="box-inner text-center bright-text">
                <h3><?php echo $this->layout()->_t->translate("Domains");?></h3>
                <hr class="mrg5T mrg5B">
                <div class="text-right">
                  <a class="bright-text tooltip-item" title="Domain List" href="<?php echo $this->basePath() ?>/publisher"><i class="glyphicon glyphicon-th-list"></i></a>&nbsp;
                </div>
              </div>
            </div>
          </div> 

          <div class="col-sm-4 mrg10B">
            <div class="box no-border bg-custom-primary tiles-information">
              <i class="glyphicon glyphicon-th-large icon-bg"></i>
              <div class="box-inner text-center">
                <h3 class="bright-text"><?php echo $this->layout()->_t->translate("Ad-zones");?></h3>
                <hr class="mrg5T mrg5B bright-text">
                <div class="text-right">
                  <div class="toggle-item display-inline tooltip-item" title="Ad-zone List">
                    <a class="dropdown-toggle bright-text"  data-toggle="dropdown" href="#">
                      <i class="glyphicon glyphicon-th-list"></i>&nbsp;
                    </a>

                    <ul class="dropdown-menu pull-right"  role="menu" aria-labelledby="dropdownMenu">
                      
                      <?php foreach ($domain_list as $key => $val): ?>
                      <li> <a tabindex="-1" class="disabled" href="<?php echo $this->basePath() ?>/publisher/zone/<?php echo $val->PublisherWebsiteID ?>"><?php echo $val->WebDomain ?></a>

                      </li>
                      <?php endforeach; ?>
                      
                      
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>  

          <div class="col-sm-4 mrg10B">
            <div class="box no-border bg-custom-warning tiles-information">
              <i class="glyphicon glyphicon-list-alt icon-bg"></i>
              <div class="box-inner text-center bright-text">
                <h3><a class="bright-text" href="<?php echo $this->basePath() ?>/manager/revenue"><?php echo $this->layout()->_t->translate("Revenue Report");?></a>
                </h3>
                <hr class="mrg5T mrg5B">
                <div class="text-right">
                  <a class="bright-text tooltip-item" title="Revenue Report" href="<?php echo $this->basePath() ?>/manager/revenue"><i class="glyphicon glyphicon-th-list"></i></a>&nbsp;
                </div>
              </div>
            </div>
          </div>  

        </div>
        
        <div class="row mrg10T">
          
          <div class="col-sm-4 mrg10B">
            <div class="box no-border bg-custom-girl tiles-information">
              <i class="glyphicon glyphicon-globe icon-bg"></i>
              <div class="box-inner text-center bright-text">
                <h3><?php echo $this->layout()->_t->translate("Campaigns");?></h3>
                <hr class="mrg5T mrg5B">
                <div class="text-right">
                  <a class="bright-text tooltip-item" title="Campaigns List" href="<?php echo $this->basePath() ?>/demand"><i class="glyphicon glyphicon-th-list"></i></a>&nbsp;
                </div>
              </div>
            </div>
          </div> 

          <div class="col-sm-4 mrg10B">
            <div class="box no-border bg-custom-danger tiles-information">
              <i class="glyphicon glyphicon-th-large icon-bg"></i>
              <div class="box-inner text-center">
                <h3 class="bright-text"><?php echo $this->layout()->_t->translate("Banners");?></h3>
                <hr class="mrg5T mrg5B bright-text">
                <div class="text-right">
                  <div class="toggle-item display-inline tooltip-item" title="Banners List">
                    <a class="dropdown-toggle bright-text"  data-toggle="dropdown" href="#">
                      <i class="glyphicon glyphicon-th-list"></i>&nbsp;
                    </a>

                    <ul class="dropdown-menu pull-right"  role="menu" aria-labelledby="dropdownMenu">
                      
                      <?php foreach ($campaigns_list as $key => $val): ?>
                      <li> <a tabindex="-1" class="disabled" href="<?php echo $this->basePath() ?>/demand/campaign/<?php echo $val->AdCampaignPreviewID ?>/?ispreview=true"><?php echo $val->Name ?></a>

                      </li>
                      <?php endforeach; ?>
                      
                      
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </div>  

          <div class="col-sm-4 mrg10B">
            <div class="box no-border bg-custom-more tiles-information">
              <i class="glyphicon glyphicon-list-alt icon-bg"></i>
              <div class="box-inner text-center bright-text">
                <h3><a class="bright-text" href="<?php echo $this->basePath() ?>/manager/userpayout/"><?php echo $this->layout()->_t->translate("User Payout");?></a>
                </h3>
                <hr class="mrg5T mrg5B">
                <br>
              </div>
            </div>
          </div>  

        </div>     

      </div>
      
    </div>
  </div>
</div>

</div>
<script type="text/javascript">
  $(function(){
    $('.tooltip-item').tooltip({placement: "bottom", container: "body"});
  });
</script>