<?php
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/AppTable.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/qtip/jquery.qtip.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/static/css/qtip/jquery.qtip.min.css');

$this->headScript()->captureStart() ?>
function submitForm() {
  $('#loginas').submit();
}

$(document).ready(function () {

    $('span[title]').qtip();
    
});

<?php $this->headScript()->captureEnd();  
$effective_user_in_dashboard = false;
?>

<div class="docs-header">
  <div class="topic container-fluid">
    <div class="row">
      <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-6"><h4><?php echo $this->layout()->_t->translate("Revenue Report");?>  </h4></div>
    </div>
  </div>
</div>


<div class="steps-container step1 ">
  <div class="container-fluid">
    <div class="row mrg20T">
      <div id="revenue-overview" class="col-md-10 col-md-offset-1 panel pad20T">
        <p class="underline mrg0T" style="padding-bottom: 3px;">
          <span class="admin-titles"><?php echo $this->layout()->_t->translate("Revenue Overview");?> </span>
            <select id="income-time" onchange="IncomeTable.reload_table(); OutcomeTable.reload_table(); loadIncomeAdzone(); loadOutcomeAdzone();">
              <option value><?php echo $this->layout()->_t->translate("All time");?></option>
              <option value="0"><?php echo $this->layout()->_t->translate("Today");?></option>
              <option value="1" selected><?php echo $this->layout()->_t->translate("Yesterday");?></option>
              <option value="2"><?php echo $this->layout()->_t->translate("This week");?></option>
              <option value="3"><?php echo $this->layout()->_t->translate("Last week");?></option>
              <option value="4"><?php echo $this->layout()->_t->translate("This month");?></option>
              <option value="5"><?php echo $this->layout()->_t->translate("Last month");?></option>
              <option value="6"><?php echo $this->layout()->_t->translate("This year");?></option>
            </select>
        </p>
        <div class="row">
          <div class="col-sm-3"><?php echo $this->layout()->_t->translate("Income");?>: <strong>$<span id="outcome-value"></span></strong></div>
          <div class="col-sm-3"><a id="income-action" onclick="viewIncomeList();" href="javascript:void(0);"></a></div>
          <div class="col-sm-3"><?php echo $this->layout()->_t->translate("Outcome");?>: <strong>$<span id="income-value"></span></strong></div>
        </div>
        
        <hr>
      
        <div id="outcome-list" >
          <strong class=" mrg5B  mrg0T"><?php echo $this->layout()->_t->translate("System Income List");?></strong>
          <table class="table table-hover table-striped table-bordered table-margin" data-url="<?php echo $this->basePath() ?>/manager/outcomelist" id="outcome-table">
            <thead>
              <tr >
                <th class="text-center">#</th>
                <th class="text-center"><?php echo $this->layout()->_t->translate("Time");?></th>
                <th class="text-center"><?php echo $this->layout()->_t->translate("Campaign Name");?></th>
                <th class="text-center"><?php echo $this->layout()->_t->translate("Banner Name");?></th>
                <th class="text-center"><?php echo $this->layout()->_t->translate("Click Count");?></th>
                <th class="text-center"><?php echo $this->layout()->_t->translate("Imp Count");?></th>
                <th class="text-center"><?php echo $this->layout()->_t->translate("Income");?></th>
              </tr>
            </thead>
          </table>
        </div>

        <hr>
        
        <div id="income-list" >
          <strong class=" mrg5B mrg0T"><?php echo $this->layout()->_t->translate("System Outcome List");?></strong>
          <table class="table table-hover table-striped table-bordered table-margin" data-url="<?php echo $this->basePath() ?>/manager/incomelist" id="income-table">
            <thead>
              <tr >
                <th class="text-center">#</th>
                <th class="text-center"><?php echo $this->layout()->_t->translate("Time");?></th>
                <th class="text-center"><?php echo $this->layout()->_t->translate("Domain");?></th>
                <th class="text-center"><?php echo $this->layout()->_t->translate("AdZone Name");?></th>
                <th class="text-center"><?php echo $this->layout()->_t->translate("Click Count");?></th>
                <th class="text-center"><?php echo $this->layout()->_t->translate("Imp Count");?></th>
                <th class="text-center"><?php echo $this->layout()->_t->translate("Outcome");?></th>
              </tr>
            </thead>
          </table>
        </div>

      </div>

    </div>
  </div>

    <div class="container-fluid">
    <div class="row mrg20T">
      <div id="revenue-overview" class="col-md-10 col-md-offset-1 panel pad20T">
        <p class="underline mrg0T" style="padding-bottom: 3px;">          
        <span class="admin-titles"><?php echo $this->layout()->_t->translate("Transaction");?> </span>
            <select id="time-filter" onchange="PaymentTable.reload_table()">
              <option selected value><?php echo $this->layout()->_t->translate("All time");?></option>
              <option value="0"><?php echo $this->layout()->_t->translate("Today");?></option>
              <option value="1"><?php echo $this->layout()->_t->translate("Yesterday");?></option>
              <option value="2"><?php echo $this->layout()->_t->translate("This week");?></option>
              <option value="3"><?php echo $this->layout()->_t->translate("Last week");?></option>
              <option value="4"><?php echo $this->layout()->_t->translate("This month");?></option>
              <option value="5"><?php echo $this->layout()->_t->translate("Last month");?></option>
              <option value="6"><?php echo $this->layout()->_t->translate("This year");?></option>
            </select> 
        </p>
        <div class="row">
          <div class="col-sm-6"><?php echo $this->layout()->_t->translate("Total Charge");?>: <strong>$<span id="total-charge-value"></span></strong></div>
          <div class="col-sm-6"><?php echo $this->layout()->_t->translate("Total Expenditure");?>: <strong>$<span id="total-expenditure-value"></span></strong></div>
        </div>
        <div class="">
          <table id="payment-table" class="table table-striped table-bordered table-margin" data-url="<?php echo $this->basePath() ?>/payment/paymentinit?view_all=true">
            <thead>
              <tr>
               <th>
                  <?php echo $this->layout()->_t->translate("ID");?>
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("Payment Method");?>  
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("Type");?>  
               </th>
                <th>
                  <?php echo $this->layout()->_t->translate("Amount");?>
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("Description");?>  
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("DateCreated");?>  
               </th>
              </tr>
            </thead>
          </table>
        </div>
        <br>
      </div>

    </div>
  </div>
  

  <div class="container-fluid">
    <div class="row mrg20T">
      <div id="revenue-overview" class="col-md-10 col-md-offset-1 panel pad20T">
        <p class="underline mrg0T" style="padding-bottom: 3px;">          
        <span class="admin-titles"><?php echo $this->layout()->_t->translate("Revenue Statistics");?> </span>
            <select id="internal-time" onchange="InternalIncomeTable.reload_table(); InternalOutcomeTable.reload_table()">
              <option selected value><?php echo $this->layout()->_t->translate("All time");?></option>
              <option value="0"><?php echo $this->layout()->_t->translate("Today");?></option>
              <option value="1"><?php echo $this->layout()->_t->translate("Yesterday");?></option>
              <option value="2"><?php echo $this->layout()->_t->translate("This week");?></option>
              <option value="3"><?php echo $this->layout()->_t->translate("Last week");?></option>
              <option value="4"><?php echo $this->layout()->_t->translate("This month");?></option>
              <option value="5"><?php echo $this->layout()->_t->translate("Last month");?></option>
              <option value="6"><?php echo $this->layout()->_t->translate("This year");?></option>
            </select> 
        </p>
        <div class="row">
          <div class="col-sm-6"><?php echo $this->layout()->_t->translate("BGate Campaign Profit");?>: <strong>$<span id="total-income-value"></span></strong></div>
          <div class="col-sm-6"><?php echo $this->layout()->_t->translate("BGate Website Profit");?>: <strong>$<span id="total-outcome-value"></span></strong></div>
        </div>
        <hr>
        <div class="">
          <strong class=" mrg5B  mrg0T"><?php echo $this->layout()->_t->translate("Monthy Campaign Income");?></strong>
          <table id="internal-income-table" class="table table-striped table-bordered table-margin" data-url="<?php echo $this->basePath() ?>/manager/internallist?type=0">
            <thead>
              <tr>
               <th>
                  <?php echo $this->layout()->_t->translate("#");?>
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("Name");?>  
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("Type");?>  
               </th>
                <th>
                  <?php echo $this->layout()->_t->translate("Transaction Type");?>
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("User Name");?>  
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("Gross Money");?>  
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("Net Money");?>  
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("Markup");?>  
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("DateCreated");?>  
               </th>
              </tr>
            </thead>
          </table>
          <hr>
          <strong class=" mrg5B  mrg0T"><?php echo $this->layout()->_t->translate("Monthy Website Outcome");?></strong>
          <table id="internal-outcome-table" class="table table-striped table-bordered table-margin" data-url="<?php echo $this->basePath() ?>/manager/internallist?type=1">
            <thead>
              <tr>
               <th>
                  <?php echo $this->layout()->_t->translate("#");?>
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("Name");?>  
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("Type");?>  
               </th>
                <th>
                  <?php echo $this->layout()->_t->translate("Transaction Type");?>
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("User Name");?>  
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("Gross Money");?>  
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("Net Money");?>  
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("Markup");?>  
               </th>
               <th>
                  <?php echo $this->layout()->_t->translate("DateCreated");?>  
               </th>
              </tr>
            </thead>
          </table>
        </div>
        <br>
      </div>

    </div>
  </div>

 <!--  <div class="container-fluid">
    <div class="row mrg20T">
      <div  class="col-md-10 col-md-offset-1 panel pad20T">
        
      </div>
    </div>
  </div> -->


</div>