<?php
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/AppTable.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/qtip/jquery.qtip.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/static/css/qtip/jquery.qtip.min.css');

$this->headScript()->captureStart() ?>
function submitForm() {
  $('#loginas').submit();
}

$(document).ready(function () {

    $('span[title]').qtip();
    
});

<?php $this->headScript()->captureEnd();  
$effective_user_in_dashboard = false;
?>

<div class="docs-header">
  <div class="topic container-fluid">
    <div class="row">
      <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-6"><h4>Revenue Report  </h4></div>
    </div>
  </div>
</div>


<div class="steps-container step1 ">
  <div class="container-fluid">
    <div class="row mrg20T">
      <div id="revenue-overview" class="col-md-10 col-md-offset-1 panel pad20T">
        <p class="underline mrg0T" style="padding-bottom: 3px;">
          <span class="admin-titles">Revenue Overview </span>
            <select id="income-time" onchange="IncomeTable.reload_table(); loadIncomeAdzone();">
              <option value>All time</option>
              <option value="0">Today</option>
              <option value="1">Yesterday</option>
              <option value="2">This week</option>
              <option value="3">Last week</option>
              <option value="4">This month</option>
              <option value="5">Last month</option>
              <option value="6">This year</option>
            </select>
        </p>
        <div class="row">
          <div class="col-sm-3">Income: <strong>$<span id="income-value"></span></strong></div>
          <div class="col-sm-3"><a id="income-action" onclick="viewIncomeList();" href="javascript:void(0);">Hide income list</a></div>
          <div class="col-sm-3">Outcome: <strong>$112,322</strong></div>
          <div class="col-sm-3"><a id="outcome-action" onclick="viewOutcomeList();" href="javascript:void(0);">Hide outcome list</a></div>
        </div>
        <br>
      </div>

    </div>
  </div>

  <div class="container-fluid">
    <div class="row mrg20T">
      <div id="income-list" class="col-md-10 col-md-offset-1 panel pad20T">
        <h4 class="underline mrg0T">Income List</h4>
        <table class="table table-hover table-striped table-bordered table-margin" data-url="<?php echo $this->basePath() ?>/manager/incomelist" id="income-table">
          <thead>
            <tr >
              <th class="text-center">#</th>
              <th class="text-center">Time</th>
              <th class="text-center">Ad Name</th>
              <th class="text-center">Click Count</th>
              <th class="text-center">Imp Count</th>
              <th class="text-center">Income</th>
            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>

  <div class="container-fluid">
    <div class="row mrg20T">
      <div id="outcome-list" class="col-md-10 col-md-offset-1 panel pad20T">
        <h4 class="underline mrg0T">Outcome List</h4>
        <table class="table table-bordered table-hover" data-url="" id="income-table">
          <thead>
            <tr >
              <th class="text-center">#</th>
              <th class="text-center">Time</th>
              <th class="text-center">Ad Name</th>
              <th class="text-center">Click Count</th>
              <th class="text-center">Imp Count</th>
              <th class="text-center">Outcome</th>
            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>
</div>