<?php
$this->headScript()->appendFile($this->basePath() . '/static/js/script.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/AppTable.js');
$this->headScript()->appendFile($this->basePath() . '/static/js/qtip/jquery.qtip.min.js');
$this->headLink()->appendStylesheet($this->basePath() . '/static/css/qtip/jquery.qtip.min.css');

$this->headScript()->captureStart() ?>
function submitForm() {
  $('#loginas').submit();
}

$(document).ready(function () {

    $('span[title]').qtip();
    
});

<?php $this->headScript()->captureEnd();  
$effective_user_in_dashboard = false;
?>
<div class="docs-header">
  <div class="topic">
    <div class="row">
      <div class="col-md-5 col-md-offset-1 col-sm-5 col-sm-offset-1 col-xs-6"><h4><?php echo $this->layout()->_t->translate("User Payout");?></h4></div>
      
    </div>
  </div>
</div>
<div class="steps-container step1 ">

  <div class="container-fluid">
    <div class="row mrg20T">
      <div id="income-list" class="col-md-10 col-md-offset-1 panel pad20T">
        <p class="underline mrg0T" style="padding-bottom: 3px;">
          <span class="admin-titles"> <?php echo $this->layout()->_t->translate("User Payout");?></span>
        <table id="user-payout-table" class="table table-hover table-striped table-bordered table-margin" data-url="<?php echo $this->basePath() ?>/publisher/payoutlist">
          <thead>
            <tr >
              <th class="text-center">#</th>
              <th class="text-center"><?php echo $this->layout()->_t->translate("Date");?></th>
              <th class="text-center"><?php echo $this->layout()->_t->translate("Name");?></th>
              <th class="text-center"><?php echo $this->layout()->_t->translate("Amount");?></th>
              <th class="text-center"><?php echo $this->layout()->_t->translate("Status");?></th>
            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>

</div>


<!-- User Payout Modal -->
<div class="modal fade" id="PayoutModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" style="display: none;">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="myModalLabel"><?php echo $this->layout()->_t->translate("Withdraw");?></h4>
        <hr>
      </div>
      <div class="modal-body">
        <form id="domain" class="form-horizontal form-top-magin" name="domain" method="post" action="/bgate/publisher/payoutprocess" novalidate="novalidate">
          <input type="hidden" value="" name="UserPayoutID">
          <div class="form-group">
            <label for="Amount" class="control-label col-sm-3"><?php echo $this->layout()->_t->translate("Amount");?></label>
            <div class="controls col-sm-7">
              <input type="text" value="" maxlength="255" class="form-control" id="Amount" name="Amount">    
            </div>
          </div>
          <hr>
          <div class="form-group text-center">
            <div class="controls">
              <button name="submit" type="submit" class="btn btn-primary btn-margin" id="submitbutton"><?php echo $this->layout()->_t->translate("Submit");?></button> &nbsp;
              <a class="btn btn-margin" data-dismiss="modal"><?php echo $this->layout()->_t->translate("Cancel");?></a>
            </div>
          </div>
          </form>
      </div>
      <div class="modal-footer">
      </div>
    </div>
  </div>
</div>



