<?php
$this->headScript()->prependFile($this->basePath() . '/js/script.js');
?>


<div class="docs-header">
	<div class="topic">
        <div class="container">
			<div class="col-md-8">
			  <h3>Create Demand Customer Account.</h3>
			</div>
			<div class="col-md-4">
			
          </div>
        </div>
        <div class="topic__infos">
          <div class="container">
          		<a href="<?php echo $this->basePath() ?>/signup">Publishers Sign-up Here</a>
          </div>
        </div>
      </div>
</div>

<div class="container">
	<div class="row">
		<br />
		<div class="col-md-6 col-md-offset-3">
			<form class="form-horizontal" method="POST" action="<?php echo $this->basePath() ?>/auth/authenticate" name="loginform" id="loginform" >
				<fieldset>
					<div id="legend" class="headbreadcrumb">
						<h1 class="loginhead">Login</h1>
					</div>  
					<?php
					if (isset($_SESSION['user']['message'])):
					   echo '<div id="cdn_form_msg" class="alert alert-error" style="margin: 5px;">'.$_SESSION['user']['message'].'</div>';
					   unset($_SESSION['user']['message']);
					endif;
					?>  
					<div class="form-group form-group-lg">
						<!-- Username -->
						<label class="control-label"  for="username">Email Address</label>
						<div class="controls">
							<input type="text" id="username" name="username" placeholder="" class="form-control">
						</div>
					</div>
					
					<div class="form-group form-group-lg">
						<!-- Password-->
						<label class="control-label" for="password">Password</label>
						<div class="controls">
							<input type="password" id="password" name="password" placeholder="" class="form-control">
						</div>
					</div>
					
					<div class="form-group">
						<!-- Password-->
						
						<div class="controls">
							<label  style="display: inline; float: left; margin-right: 10px;" for="password" class="icheckbox_flat checked"> <input type="checkbox" name="rememberme" class="iCheck-helper" /></label><label for="rememberme"  style="float: left; margin-top: 4px;">Remember Me</label>
						</div>
					</div>
					
					
					<br />
					<div class="form-group">
					<!-- Button -->
						<div class="form-group text-center">
							 <input type="submit" class="btn btn-success btn-lg" value="Login to Dashboard" name="B1">
						</div>
					</div>

					<br />
					<br />

				</fieldset>
			</form>
		</div>
	</div>
</div>

















<style>
#main-container.centerj {
    width: 45%;
}
	
</style>
<div class="loginbox">
       
</div>					